Repository MetaMask/core, pull requests merged in 2023-09, with the labels that each got.

#1637 feat: accounts controller
  packages/accounts-controller/CHANGELOG.md
  packages/accounts-controller/LICENSE
  packages/accounts-controller/README.md
  packages/accounts-controller/jest.config.js
  packages/accounts-controller/package.json
  packages/accounts-controller/src/AccountsController.test.ts
  packages/accounts-controller/src/AccountsController.ts
  packages/accounts-controller/src/index.ts
  packages/accounts-controller/tsconfig.build.json
  packages/accounts-controller/tsconfig.json
  packages/accounts-controller/typedoc.json
  tsconfig.build.json
  tsconfig.json
  yarn.lock
Labels: team-accounts

#1676 TokensController.addToken use networkClientId
  packages/assets-controllers/src/TokenBalancesController.test.ts
  packages/assets-controllers/src/TokenDetectionController.test.ts
  packages/assets-controllers/src/TokensController.test.ts
  packages/assets-controllers/src/TokensController.ts
Labels: team-devex

#1714 Add `test:clean` build script that clears jest cache before running tests
  constraints.pro
  package.json
  packages/accounts-controller/package.json
  packages/address-book-controller/package.json
  packages/announcement-controller/package.json
  packages/approval-controller/package.json
  packages/assets-controllers/package.json
  packages/base-controller/package.json
  packages/composable-controller/package.json
  packages/controller-utils/package.json
  packages/ens-controller/package.json
  packages/gas-fee-controller/package.json
  packages/keyring-controller/package.json
  packages/logging-controller/package.json
  packages/message-manager/package.json
  packages/name-controller/package.json
  packages/network-controller/package.json
  packages/notification-controller/package.json
  packages/permission-controller/package.json
  packages/phishing-controller/package.json
  packages/polling-controller/package.json
  packages/preferences-controller/package.json
  packages/rate-limit-controller/package.json
  packages/selected-network-controller/package.json
  packages/signature-controller/package.json
  packages/transaction-controller/package.json
Labels: enhancement, team-shared-libraries

#1673 Integrate PollingController mixin with GasFeeController
  packages/gas-fee-controller/src/GasFeeController.test.ts
  packages/gas-fee-controller/src/GasFeeController.ts
  packages/gas-fee-controller/tsconfig.build.json
  packages/gas-fee-controller/tsconfig.json
  packages/network-controller/src/NetworkController.ts
  yarn.lock
Labels: team-devex
