Repository MetaMask/core, pull requests merged in 2023-10, with the labels that each got.

#1737 Migrate `eth-json-rpc-provider` into core monorepo (1/2)
  merged-packages/eth-json-rpc-provider/.depcheckrc.json
  merged-packages/eth-json-rpc-provider/.editorconfig
  merged-packages/eth-json-rpc-provider/.eslintrc.js
  merged-packages/eth-json-rpc-provider/.gitattributes
  merged-packages/eth-json-rpc-provider/.github/CODEOWNERS
  merged-packages/eth-json-rpc-provider/.github/dependabot.yml
  merged-packages/eth-json-rpc-provider/.github/pull_request_template.md
  merged-packages/eth-json-rpc-provider/.github/workflows/build-lint-test.yml
  merged-packages/eth-json-rpc-provider/.github/workflows/create-release-pr.yml
  merged-packages/eth-json-rpc-provider/.github/workflows/main.yml
  merged-packages/eth-json-rpc-provider/.github/workflows/publish-docs.yml
  merged-packages/eth-json-rpc-provider/.github/workflows/publish-main-docs.yml
  merged-packages/eth-json-rpc-provider/.github/workflows/publish-rc-docs.yml
  merged-packages/eth-json-rpc-provider/.github/workflows/publish-release.yml
  merged-packages/eth-json-rpc-provider/.gitignore
  merged-packages/eth-json-rpc-provider/.nvmrc
  merged-packages/eth-json-rpc-provider/.prettierrc.js
  merged-packages/eth-json-rpc-provider/.yarn/plugins/@yarnpkg/plugin-allow-scripts.cjs
  merged-packages/eth-json-rpc-provider/.yarn/releases/yarn-3.2.1.cjs
  merged-packages/eth-json-rpc-provider/.yarnrc.yml
  merged-packages/eth-json-rpc-provider/CHANGELOG.md
  merged-packages/eth-json-rpc-provider/LICENSE
  merged-packages/eth-json-rpc-provider/README.md
  merged-packages/eth-json-rpc-provider/jest.config.js
  merged-packages/eth-json-rpc-provider/package.json
  merged-packages/eth-json-rpc-provider/scripts/get.sh
  merged-packages/eth-json-rpc-provider/scripts/prepack.sh
  merged-packages/eth-json-rpc-provider/src/index.test.ts
  merged-packages/eth-json-rpc-provider/src/index.ts
  merged-packages/eth-json-rpc-provider/src/provider-from-engine.test.ts
  merged-packages/eth-json-rpc-provider/src/provider-from-engine.ts
  merged-packages/eth-json-rpc-provider/src/provider-from-middleware.test.ts
  merged-packages/eth-json-rpc-provider/src/provider-from-middleware.ts
  merged-packages/eth-json-rpc-provider/src/safe-event-emitter-provider.test.ts
  merged-packages/eth-json-rpc-provider/src/safe-event-emitter-provider.ts
  merged-packages/eth-json-rpc-provider/tsconfig.build.json
  merged-packages/eth-json-rpc-provider/tsconfig.json
  merged-packages/eth-json-rpc-provider/typedoc.json
  merged-packages/eth-json-rpc-provider/yarn.lock
Labels: enhancement, team-shared-libraries

#1755 Migrate eth-json-rpc-provider into core monorepo (1/2)
  merged-packages/eth-json-rpc-provider/.depcheckrc.json
  merged-packages/eth-json-rpc-provider/.editorconfig
  merged-packages/eth-json-rpc-provider/.eslintrc.js
  merged-packages/eth-json-rpc-provider/.gitattributes
  merged-packages/eth-json-rpc-provider/.github/CODEOWNERS
  merged-packages/eth-json-rpc-provider/.github/dependabot.yml
  merged-packages/eth-json-rpc-provider/.github/pull_request_template.md
  merged-packages/eth-json-rpc-provider/.github/workflows/build-lint-test.yml
  merged-packages/eth-json-rpc-provider/.github/workflows/create-release-pr.yml
  merged-packages/eth-json-rpc-provider/.github/workflows/main.yml
  merged-packages/eth-json-rpc-provider/.github/workflows/publish-docs.yml
  merged-packages/eth-json-rpc-provider/.github/workflows/publish-main-docs.yml
  merged-packages/eth-json-rpc-provider/.github/workflows/publish-rc-docs.yml
  merged-packages/eth-json-rpc-provider/.github/workflows/publish-release.yml
  merged-packages/eth-json-rpc-provider/.gitignore
  merged-packages/eth-json-rpc-provider/.nvmrc
  merged-packages/eth-json-rpc-provider/.prettierrc.js
  merged-packages/eth-json-rpc-provider/.yarn/plugins/@yarnpkg/plugin-allow-scripts.cjs
  merged-packages/eth-json-rpc-provider/.yarn/releases/yarn-3.2.1.cjs
  merged-packages/eth-json-rpc-provider/.yarnrc.yml
  merged-packages/eth-json-rpc-provider/CHANGELOG.md
  merged-packages/eth-json-rpc-provider/LICENSE
  merged-packages/eth-json-rpc-provider/README.md
  merged-packages/eth-json-rpc-provider/jest.config.js
  merged-packages/eth-json-rpc-provider/package.json
  merged-packages/eth-json-rpc-provider/scripts/get.sh
  merged-packages/eth-json-rpc-provider/scripts/prepack.sh
  merged-packages/eth-json-rpc-provider/src/index.test.ts
  merged-packages/eth-json-rpc-provider/src/index.ts
  merged-packages/eth-json-rpc-provider/src/provider-from-engine.test.ts
  merged-packages/eth-json-rpc-provider/src/provider-from-engine.ts
  merged-packages/eth-json-rpc-provider/src/provider-from-middleware.test.ts
  merged-packages/eth-json-rpc-provider/src/provider-from-middleware.ts
  merged-packages/eth-json-rpc-provider/src/safe-event-emitter-provider.test.ts
  merged-packages/eth-json-rpc-provider/src/safe-event-emitter-provider.ts
  merged-packages/eth-json-rpc-provider/tsconfig.build.json
  merged-packages/eth-json-rpc-provider/tsconfig.json
  merged-packages/eth-json-rpc-provider/typedoc.json
  merged-packages/eth-json-rpc-provider/yarn.lock
Labels: enhancement, dependencies, team-shared-libraries

#1748 fix(gas-fee-controller): add missing @metamask/polling-controller
  constraints.pro
  packages/gas-fee-controller/package.json
  yarn.lock
Labels: bug, dependencies

#1766 `eth-json-rpc-provider` migration - B3: Align dependencies with monorepo.
  merged-packages/eth-json-rpc-provider/package.json
Labels: enhancement, dependencies, team-shared-libraries

#1767 `eth-json-rpc-provider` migration - B4: Add exceptions in `constraints.pro` for ISC license.
  constraints.pro
Labels: enhancement, team-shared-libraries

#1764 `eth-json-rpc-provider` migration - B1: Remove redundant files and directories.
  merged-packages/eth-json-rpc-provider/.depcheckrc.json
  merged-packages/eth-json-rpc-provider/.editorconfig
  merged-packages/eth-json-rpc-provider/.eslintrc.js
  merged-packages/eth-json-rpc-provider/.gitattributes
  merged-packages/eth-json-rpc-provider/.github/CODEOWNERS
  merged-packages/eth-json-rpc-provider/.github/dependabot.yml
  merged-packages/eth-json-rpc-provider/.github/pull_request_template.md
  merged-packages/eth-json-rpc-provider/.github/workflows/build-lint-test.yml
  merged-packages/eth-json-rpc-provider/.github/workflows/create-release-pr.yml
  merged-packages/eth-json-rpc-provider/.github/workflows/main.yml
  merged-packages/eth-json-rpc-provider/.github/workflows/publish-docs.yml
  merged-packages/eth-json-rpc-provider/.github/workflows/publish-main-docs.yml
  merged-packages/eth-json-rpc-provider/.github/workflows/publish-rc-docs.yml
  merged-packages/eth-json-rpc-provider/.github/workflows/publish-release.yml
  merged-packages/eth-json-rpc-provider/.gitignore
  merged-packages/eth-json-rpc-provider/.nvmrc
  merged-packages/eth-json-rpc-provider/.prettierrc.js
  merged-packages/eth-json-rpc-provider/.yarn/plugins/@yarnpkg/plugin-allow-scripts.cjs
  merged-packages/eth-json-rpc-provider/.yarn/releases/yarn-3.2.1.cjs
  merged-packages/eth-json-rpc-provider/.yarnrc.yml
  merged-packages/eth-json-rpc-provider/scripts/get.sh
  merged-packages/eth-json-rpc-provider/scripts/prepack.sh
  merged-packages/eth-json-rpc-provider/yarn.lock
Labels: enhancement, team-shared-libraries

#1765 `eth-json-rpc-provider` migration - B2: Replace typescript, jest config files.
  merged-packages/eth-json-rpc-provider/jest.config.js
  merged-packages/eth-json-rpc-provider/tsconfig.build.json
  merged-packages/eth-json-rpc-provider/tsconfig.json
  merged-packages/eth-json-rpc-provider/typedoc.json
Labels: enhancement, team-shared-libraries

#1735 Bump/deps @metamask/eth-snap-keyring @metamask/keyring-api @metamask/snaps-controllers @metamask/snaps-utils eth-rpc-errors -> @metamask/rpc-errors in AccountsController
  packages/accounts-controller/package.json
  packages/accounts-controller/tsconfig.build.json
  yarn.lock
Labels: dependencies

#1738 `eth-json-rpc-provider` migration - Integration into `packages/`
  package.json
  packages/eth-json-rpc-provider/CHANGELOG.md
  packages/eth-json-rpc-provider/LICENSE
  packages/eth-json-rpc-provider/README.md
  packages/eth-json-rpc-provider/jest.config.js
  packages/eth-json-rpc-provider/package.json
  packages/eth-json-rpc-provider/src/index.test.ts
  packages/eth-json-rpc-provider/src/index.ts
  packages/eth-json-rpc-provider/src/provider-from-engine.test.ts
  packages/eth-json-rpc-provider/src/provider-from-engine.ts
  packages/eth-json-rpc-provider/src/provider-from-middleware.test.ts
  packages/eth-json-rpc-provider/src/provider-from-middleware.ts
  packages/eth-json-rpc-provider/src/safe-event-emitter-provider.test.ts
  packages/eth-json-rpc-provider/src/safe-event-emitter-provider.ts
  packages/eth-json-rpc-provider/tsconfig.build.json
  packages/eth-json-rpc-provider/tsconfig.json
  packages/eth-json-rpc-provider/typedoc.json
  packages/network-controller/package.json
  packages/network-controller/tests/fake-provider.ts
  packages/network-controller/tsconfig.build.json
  packages/network-controller/tsconfig.json
  tests/fake-block-tracker.ts
  tsconfig.build.json
  tsconfig.json
  yarn.lock
Labels: enhancement, dependencies, team-shared-libraries

#1837 Fix whitespace in `generate-dependency-graph` that causes prettier error
  scripts/generate-dependency-graph.ts
Labels: team-shared-libraries

#1807 Update root README dependency graph with `eth-json-rpc-provider` and changes from recent releases
  README.md
Labels: team-shared-libraries

#1847 Remove outdated `eth-json-rpc-provider` README content
  packages/eth-json-rpc-provider/README.md
Labels: team-shared-libraries

#1855 Record CHANGELOG entries from `eth-json-rpc-provider` migration
  packages/eth-json-rpc-provider/CHANGELOG.md
  packages/network-controller/CHANGELOG.md
Labels: enhancement, team-shared-libraries

#1861 Typing fixes for #1839 (Feat/update on keyring state change in accounts controller)
  packages/accounts-controller/src/AccountsController.ts
Labels: team-shared-libraries

#1865 Remove `for..in` loops and reenable eslint rules: `guard-for-in`, `no-for-in-array`
  .eslintrc.js
  packages/assets-controllers/src/TokenBalancesController.ts
  packages/assets-controllers/src/TokenDetectionController.ts
  packages/base-controller/src/BaseController.ts
  packages/preferences-controller/jest.config.js
  packages/preferences-controller/src/PreferencesController.ts
  packages/transaction-controller/src/TransactionController.test.ts
  packages/transaction-controller/src/utils/etherscan.ts
  packages/transaction-controller/src/utils/utils.ts
Labels: team-shared-libraries

#1872 Migrate json rpc engine
  merged-packages/json-rpc-engine/.depcheckrc.json
  merged-packages/json-rpc-engine/.editorconfig
  merged-packages/json-rpc-engine/.eslintrc.js
  merged-packages/json-rpc-engine/.gitattributes
  merged-packages/json-rpc-engine/.github/CODEOWNERS
  merged-packages/json-rpc-engine/.github/dependabot.yml
  merged-packages/json-rpc-engine/.github/workflows/build-lint-test.yml
  merged-packages/json-rpc-engine/.github/workflows/create-release-pr.yml
  merged-packages/json-rpc-engine/.github/workflows/main.yml
  merged-packages/json-rpc-engine/.github/workflows/publish-docs.yml
  merged-packages/json-rpc-engine/.github/workflows/publish-main-docs.yml
  merged-packages/json-rpc-engine/.github/workflows/publish-rc-docs.yml
  merged-packages/json-rpc-engine/.github/workflows/publish-release.yml
  merged-packages/json-rpc-engine/.gitignore
  merged-packages/json-rpc-engine/.nvmrc
  merged-packages/json-rpc-engine/.prettierrc.js
  merged-packages/json-rpc-engine/.yarn/plugins/@yarnpkg/plugin-allow-scripts.cjs
  merged-packages/json-rpc-engine/.yarn/releases/yarn-3.5.0.cjs
  merged-packages/json-rpc-engine/.yarnrc.yml
  merged-packages/json-rpc-engine/CHANGELOG.md
  merged-packages/json-rpc-engine/LICENSE
  merged-packages/json-rpc-engine/README.md
  merged-packages/json-rpc-engine/jest.config.js
  merged-packages/json-rpc-engine/package.json
  merged-packages/json-rpc-engine/scripts/get.sh
  merged-packages/json-rpc-engine/scripts/prepack.sh
  merged-packages/json-rpc-engine/src/JsonRpcEngine.test.ts
  merged-packages/json-rpc-engine/src/JsonRpcEngine.ts
  merged-packages/json-rpc-engine/src/asMiddleware.test.ts
  merged-packages/json-rpc-engine/src/createAsyncMiddleware.test.ts
  merged-packages/json-rpc-engine/src/createAsyncMiddleware.ts
  merged-packages/json-rpc-engine/src/createScaffoldMiddleware.test.ts
  merged-packages/json-rpc-engine/src/createScaffoldMiddleware.ts
  merged-packages/json-rpc-engine/src/getUniqueId.ts
  merged-packages/json-rpc-engine/src/idRemapMiddleware.test.ts
  merged-packages/json-rpc-engine/src/idRemapMiddleware.ts
  merged-packages/json-rpc-engine/src/index.ts
  merged-packages/json-rpc-engine/src/mergeMiddleware.test.ts
  merged-packages/json-rpc-engine/src/mergeMiddleware.ts
  merged-packages/json-rpc-engine/tsconfig.build.json
  merged-packages/json-rpc-engine/tsconfig.json
  merged-packages/json-rpc-engine/typedoc.json
  merged-packages/json-rpc-engine/yarn.lock
Labels: team-shared-libraries

#1907 Adds `constraints.pro` rule that removes `prepack` build scripts
  constraints.pro
Labels: team-shared-libraries

#1908 Typing fixes for `PermissionLogController`
  packages/permission-log-controller/src/PermissionLog.ts
  packages/permission-log-controller/src/permissions.ts
Labels: team-shared-libraries

#1954 Typing fixes for `TransactionController.test.ts`
  packages/transaction-controller/src/TransactionController.test.ts
  packages/transaction-controller/src/types.ts
Labels: team-shared-libraries
