Repository MetaMask/core, pull requests merged in 2023-12, with the labels that each got.

#3608 Remove superfluous typescript reference paths
  packages/approval-controller/tsconfig.build.json
  packages/approval-controller/tsconfig.json
  packages/composable-controller/tsconfig.build.json
  packages/composable-controller/tsconfig.json
  packages/keyring-controller/tsconfig.build.json
  packages/keyring-controller/tsconfig.json
  packages/logging-controller/tsconfig.build.json
  packages/logging-controller/tsconfig.json
  packages/notification-controller/tsconfig.build.json
  packages/notification-controller/tsconfig.json
  packages/permission-log-controller/tsconfig.build.json
  packages/permission-log-controller/tsconfig.json
Labels: team-shared-libraries

#3601 Add user operation controller
  packages/user-operation-controller/CHANGELOG.md
  packages/user-operation-controller/LICENSE
  packages/user-operation-controller/README.md
  packages/user-operation-controller/jest.config.js
  packages/user-operation-controller/package.json
  packages/user-operation-controller/src/UserOperationController.test.ts
  packages/user-operation-controller/src/UserOperationController.ts
  packages/user-operation-controller/src/constants.ts
  packages/user-operation-controller/src/helpers/Bundler.test.ts
  packages/user-operation-controller/src/helpers/Bundler.ts
  packages/user-operation-controller/src/index.ts
  packages/user-operation-controller/src/logger.ts
  packages/user-operation-controller/src/types.ts
  packages/user-operation-controller/src/utils/validation.test.ts
  packages/user-operation-controller/src/utils/validation.ts
  packages/user-operation-controller/tsconfig.build.json
  packages/user-operation-controller/tsconfig.json
  packages/user-operation-controller/typedoc.json
  tsconfig.build.json
  tsconfig.json
  yarn.lock
Labels: team-confirmations-system

#3592 Update releasing process
  docs/contributing.md
  package.json
  yarn.lock
Labels: team-shared-libraries

#3641 fix: update forgetQRDevice method
  packages/keyring-controller/src/KeyringController.test.ts
  packages/keyring-controller/src/KeyringController.ts
Labels: team-accounts, needs-dev-review

#3590 Upgrade `ComposableController` to extend `BaseControllerV2`
  packages/base-controller/src/BaseControllerV2.ts
  packages/composable-controller/CHANGELOG.md
  packages/composable-controller/src/ComposableController.test.ts
  packages/composable-controller/src/ComposableController.ts
  packages/composable-controller/src/index.ts
Labels: enhancement, team-shared-libraries

#3653 Update 'token contract address' -> 'token address'
  packages/assets-controllers/CHANGELOG.md
  packages/assets-controllers/src/TokenRatesController.test.ts
  packages/assets-controllers/src/TokenRatesController.ts
  packages/assets-controllers/src/token-prices-service/abstract-token-prices-service.ts
  packages/assets-controllers/src/token-prices-service/codefi-v2.test.ts
  packages/assets-controllers/src/token-prices-service/codefi-v2.ts
Labels: team-shared-libraries

#3676 Fix transaction status incorrectly set to dropped, submitted, or failed
  packages/transaction-controller/jest.config.js
  packages/transaction-controller/src/TransactionController.test.ts
  packages/transaction-controller/src/TransactionController.ts
  packages/transaction-controller/src/helpers/PendingTransactionTracker.test.ts
  packages/transaction-controller/src/helpers/PendingTransactionTracker.ts
Labels: team-confirmations-system

#3668 Add script to update changelogs of a release candidate
  constraints.pro
  package.json
  packages/accounts-controller/package.json
  packages/address-book-controller/package.json
  packages/announcement-controller/package.json
  packages/approval-controller/package.json
  packages/assets-controllers/package.json
  packages/base-controller/package.json
  packages/build-utils/package.json
  packages/composable-controller/package.json
  packages/controller-utils/package.json
  packages/ens-controller/package.json
  packages/eth-json-rpc-provider/package.json
  packages/gas-fee-controller/package.json
  packages/json-rpc-engine/package.json
  packages/json-rpc-middleware-stream/package.json
  packages/keyring-controller/package.json
  packages/logging-controller/package.json
  packages/message-manager/package.json
  packages/name-controller/package.json
  packages/network-controller/package.json
  packages/notification-controller/package.json
  packages/permission-controller/package.json
  packages/permission-log-controller/package.json
  packages/phishing-controller/package.json
  packages/polling-controller/package.json
  packages/preferences-controller/package.json
  packages/queued-request-controller/package.json
  packages/rate-limit-controller/package.json
  packages/selected-network-controller/package.json
  packages/signature-controller/package.json
  packages/transaction-controller/package.json
  packages/user-operation-controller/package.json
  scripts/create-package/package-template/package.json
  scripts/update-changelog.sh
  yarn.lock
Labels: team-shared-libraries

#3662 feat: simplify permission log controller
  packages/permission-log-controller/package.json
  packages/permission-log-controller/src/PermissionLogController.ts
  packages/permission-log-controller/tests/PermissionLogController.test.ts
  yarn.lock
Labels: team-shared-libraries

#3609 Upgrade `TokenDetectionController` to extend `BaseControllerV2`, `StaticIntervalPollingController`
  packages/assets-controllers/CHANGELOG.md
  packages/assets-controllers/jest.config.js
  packages/assets-controllers/src/TokenDetectionController.test.ts
  packages/assets-controllers/src/TokenDetectionController.ts
  packages/assets-controllers/src/TokenListController.ts
  packages/assets-controllers/src/index.ts
Labels: enhancement, team-shared-libraries

#3607 Recategorize controller dependencies as devDependencies if only imports are messaging system-related types
  packages/accounts-controller/CHANGELOG.md
  packages/accounts-controller/package.json
  packages/ens-controller/CHANGELOG.md
  packages/ens-controller/package.json
  packages/keyring-controller/CHANGELOG.md
  packages/keyring-controller/package.json
  packages/permission-controller/CHANGELOG.md
  packages/permission-controller/package.json
  packages/queued-request-controller/CHANGELOG.md
  packages/queued-request-controller/package.json
  yarn.lock
Labels: dependencies, team-shared-libraries
