Repository MetaMask/core, pull requests merged in 2023-11, with the labels that each got.

#1973 Advance time utility function
  packages/assets-controllers/src/CurrencyRateController.test.ts
  packages/assets-controllers/src/NftDetectionController.test.ts
  packages/assets-controllers/src/TokenBalancesController.test.ts
  packages/assets-controllers/src/TokenDetectionController.test.ts
  packages/assets-controllers/src/TokenDetectionController.ts
  packages/assets-controllers/src/TokenListController.test.ts
  packages/assets-controllers/tsconfig.json
  packages/polling-controller/package.json
  packages/polling-controller/src/PollingController.test.ts
  packages/polling-controller/tsconfig.json
  tests/helpers.ts
  yarn.lock
Labels: team-devex

#1895 move json-rpc-engine from merged-packages to packages
  constraints.pro
  package.json
  packages/eth-json-rpc-provider/package.json
  packages/eth-json-rpc-provider/tsconfig.build.json
  packages/eth-json-rpc-provider/tsconfig.json
  packages/json-rpc-engine/CHANGELOG.md
  packages/json-rpc-engine/LICENSE
  packages/json-rpc-engine/README.md
  packages/json-rpc-engine/jest.config.js
  packages/json-rpc-engine/package.json
  packages/json-rpc-engine/src/JsonRpcEngine.test.ts
  packages/json-rpc-engine/src/JsonRpcEngine.ts
  packages/json-rpc-engine/src/asMiddleware.test.ts
  packages/json-rpc-engine/src/createAsyncMiddleware.test.ts
  packages/json-rpc-engine/src/createAsyncMiddleware.ts
  packages/json-rpc-engine/src/createScaffoldMiddleware.test.ts
  packages/json-rpc-engine/src/createScaffoldMiddleware.ts
  packages/json-rpc-engine/src/getUniqueId.ts
  packages/json-rpc-engine/src/idRemapMiddleware.test.ts
  packages/json-rpc-engine/src/idRemapMiddleware.ts
  packages/json-rpc-engine/src/index.ts
  packages/json-rpc-engine/src/mergeMiddleware.test.ts
  packages/json-rpc-engine/src/mergeMiddleware.ts
  packages/json-rpc-engine/tsconfig.build.json
  packages/json-rpc-engine/tsconfig.json
  packages/json-rpc-engine/typedoc.json
  packages/network-controller/package.json
  packages/network-controller/tsconfig.build.json
  packages/network-controller/tsconfig.json
  packages/permission-controller/package.json
  packages/permission-controller/tsconfig.build.json
  packages/permission-controller/tsconfig.json
  packages/queued-request-controller/package.json
  packages/queued-request-controller/tsconfig.build.json
  packages/queued-request-controller/tsconfig.json
  packages/selected-network-controller/package.json
  packages/selected-network-controller/tsconfig.build.json
  packages/selected-network-controller/tsconfig.json
  tsconfig.build.json
  tsconfig.json
  yarn.lock
Labels: team-shared-libraries

#1983 Fix `lint:fix` build script so it doesn't need to be run multiple times
  package.json
Labels: team-shared-libraries

#1802 Add script for tag porting when migrating libraries into the core monorepo
  docs/migrate-tags.md
  scripts/migrate-tags.sh
  scripts/semver.sh
Labels: enhancement, team-shared-libraries

#1990 Update `@metamask/json-rpc-engine` README to reflect migration into monorepo subpackage
  packages/json-rpc-engine/README.md
Labels: team-shared-libraries

#1762 moving json-rpc-middleware-stream from merged-packages to actual pack…
  constraints.pro
  merged-packages/json-rpc-middleware-stream/.depcheckrc.json
  merged-packages/json-rpc-middleware-stream/.editorconfig
  merged-packages/json-rpc-middleware-stream/.eslintrc.js
  merged-packages/json-rpc-middleware-stream/.gitattributes
  merged-packages/json-rpc-middleware-stream/.github/CODEOWNERS
  merged-packages/json-rpc-middleware-stream/.github/dependabot.yml
  merged-packages/json-rpc-middleware-stream/.github/workflows/build-test.yml
  merged-packages/json-rpc-middleware-stream/.github/workflows/create-release-pr.yml
  merged-packages/json-rpc-middleware-stream/.github/workflows/publish-release.yml
  merged-packages/json-rpc-middleware-stream/.gitignore
  merged-packages/json-rpc-middleware-stream/.nvmrc
  merged-packages/json-rpc-middleware-stream/.prettierrc.js
  merged-packages/json-rpc-middleware-stream/.yarn/plugins/@yarnpkg/plugin-allow-scripts.cjs
  merged-packages/json-rpc-middleware-stream/.yarn/plugins/@yarnpkg/plugin-constraints.cjs
  merged-packages/json-rpc-middleware-stream/.yarn/releases/yarn-3.6.3.cjs
  merged-packages/json-rpc-middleware-stream/.yarnrc.yml
  merged-packages/json-rpc-middleware-stream/README.md
  merged-packages/json-rpc-middleware-stream/jest.config.js
  merged-packages/json-rpc-middleware-stream/package.json
  merged-packages/json-rpc-middleware-stream/tsconfig.build.json
  merged-packages/json-rpc-middleware-stream/tsconfig.json
  merged-packages/json-rpc-middleware-stream/yarn.lock
  packages/json-rpc-middleware-stream/CHANGELOG.md
  packages/json-rpc-middleware-stream/LICENSE
  packages/json-rpc-middleware-stream/README.md
  packages/json-rpc-middleware-stream/jest.config.js
  packages/json-rpc-middleware-stream/package.json
  packages/json-rpc-middleware-stream/src/createEngineStream.ts
  packages/json-rpc-middleware-stream/src/createStreamMiddleware.ts
  packages/json-rpc-middleware-stream/src/index.test.ts
  packages/json-rpc-middleware-stream/src/index.ts
  packages/json-rpc-middleware-stream/tsconfig.build.json
  packages/json-rpc-middleware-stream/tsconfig.json
  packages/json-rpc-middleware-stream/typedoc.json
  tsconfig.build.json
  tsconfig.json
  yarn.lock
Labels: team-shared-libraries

#1991 Update root README dependency graph with `@metamask/json-rpc-{engine,middleware-stream}`
  README.md
Labels: team-shared-libraries

#1871 Import permission log controller
  README.md
  constraints.pro
  packages/permission-log-controller/CHANGELOG.md
  packages/permission-log-controller/LICENSE
  packages/permission-log-controller/README.md
  packages/permission-log-controller/jest.config.js
  packages/permission-log-controller/package.json
  packages/permission-log-controller/src/PermissionLogController.ts
  packages/permission-log-controller/src/enums.ts
  packages/permission-log-controller/src/index.ts
  packages/permission-log-controller/tests/PermissionLogController.test.ts
  packages/permission-log-controller/tests/helpers.ts
  packages/permission-log-controller/tests/index.test.ts
  packages/permission-log-controller/tsconfig.build.json
  packages/permission-log-controller/tsconfig.json
  packages/permission-log-controller/typedoc.json
  tsconfig.build.json
  tsconfig.json
  yarn.lock
Labels: team-shared-libraries

#2003 Record CHANGELOG entries from `@metamask/json-rpc-{engine,middleware-stream}` migrations
  packages/eth-json-rpc-provider/CHANGELOG.md
  packages/json-rpc-engine/CHANGELOG.md
  packages/json-rpc-middleware-stream/CHANGELOG.md
  packages/permission-controller/CHANGELOG.md
  packages/selected-network-controller/CHANGELOG.md
Labels: team-shared-libraries

#2011 Release 90.0.0
  package.json
  packages/eth-json-rpc-provider/CHANGELOG.md
  packages/eth-json-rpc-provider/package.json
  packages/json-rpc-engine/CHANGELOG.md
  packages/json-rpc-engine/package.json
  packages/json-rpc-middleware-stream/CHANGELOG.md
  packages/json-rpc-middleware-stream/package.json
  packages/network-controller/package.json
  packages/permission-controller/CHANGELOG.md
  packages/permission-controller/package.json
  packages/permission-log-controller/package.json
  packages/queued-request-controller/package.json
  packages/selected-network-controller/CHANGELOG.md
  packages/selected-network-controller/package.json
  yarn.lock
Labels: enhancement, dependencies, team-shared-libraries

#2013 Add `json-rpc-middleware-stream` to root `tsconfig` files
  tsconfig.build.json
  tsconfig.json
Labels: team-shared-libraries

#2014 Release 90.0.0
  package.json
  packages/eth-json-rpc-provider/CHANGELOG.md
  packages/eth-json-rpc-provider/package.json
  packages/json-rpc-engine/CHANGELOG.md
  packages/json-rpc-engine/package.json
  packages/json-rpc-middleware-stream/CHANGELOG.md
  packages/json-rpc-middleware-stream/package.json
  packages/network-controller/package.json
  packages/permission-controller/CHANGELOG.md
  packages/permission-controller/package.json
  packages/permission-log-controller/package.json
  packages/queued-request-controller/package.json
  packages/selected-network-controller/CHANGELOG.md
  packages/selected-network-controller/package.json
  yarn.lock
Labels: enhancement, dependencies, team-shared-libraries

#1727 fix: add name and symbol to getDetails
  packages/assets-controllers/src/AssetsContractController.test.ts
  packages/assets-controllers/src/Standards/NftStandards/ERC1155/ERC1155Standard.ts
Labels: needs-dev-review

#2006 Add optional `networkClientId` and `userAddress` args to remaining `NftController` public methods
  packages/assets-controllers/jest.config.js
  packages/assets-controllers/src/NftController.test.ts
  packages/assets-controllers/src/NftController.ts
  packages/assets-controllers/src/NftDetectionController.test.ts
  packages/assets-controllers/src/NftDetectionController.ts
Labels: team-devex

#1890 [`base-controller`] Fix all `any` usage, apply universal supertype for functions
  packages/base-controller/src/BaseControllerV2.ts
  packages/base-controller/src/ControllerMessenger.ts
  packages/rate-limit-controller/src/RateLimitController.ts
Labels: team-shared-libraries

#2030 [`base-controller`] Fix single-letter type param names
  packages/base-controller/src/BaseControllerV2.ts
  packages/base-controller/src/ControllerMessenger.ts
Labels: team-shared-libraries

#2037 Fix misaligned mock eth query types in controller tests
  packages/controller-utils/src/util.test.ts
  packages/gas-fee-controller/src/fetchBlockFeeHistory.test.ts
  packages/gas-fee-controller/src/fetchGasEstimatesViaEthFeeHistory.test.ts
  packages/transaction-controller/src/utils/transaction-type.test.ts
Labels: team-shared-libraries

#2044 Release 91.0.0
  package.json
  packages/assets-controllers/CHANGELOG.md
  packages/assets-controllers/package.json
  packages/ens-controller/CHANGELOG.md
  packages/ens-controller/package.json
  packages/gas-fee-controller/CHANGELOG.md
  packages/gas-fee-controller/package.json
  packages/network-controller/CHANGELOG.md
  packages/network-controller/package.json
  packages/polling-controller/CHANGELOG.md
  packages/polling-controller/package.json
  packages/queued-request-controller/CHANGELOG.md
  packages/queued-request-controller/package.json
  packages/selected-network-controller/CHANGELOG.md
  packages/selected-network-controller/package.json
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/package.json
  yarn.lock
Labels: team-shared-libraries

#2029 Refactor controllers to use `"getState"` action, `"stateChange"` event types defined in `base-controller`
  packages/accounts-controller/src/AccountsController.ts
  packages/announcement-controller/package.json
  packages/announcement-controller/src/AnnouncementController.ts
  packages/approval-controller/package.json
  packages/approval-controller/src/ApprovalController.ts
  packages/assets-controllers/package.json
  packages/assets-controllers/src/CurrencyRateController.ts
  packages/assets-controllers/src/TokenListController.ts
  packages/base-controller/src/index.ts
  packages/gas-fee-controller/package.json
  packages/gas-fee-controller/src/GasFeeController.ts
  packages/name-controller/package.json
  packages/name-controller/src/NameController.ts
  packages/network-controller/src/NetworkController.ts
  packages/notification-controller/package.json
  packages/notification-controller/src/NotificationController.ts
  packages/permission-controller/src/PermissionController.ts
  packages/permission-controller/src/SubjectMetadataController.ts
  packages/rate-limit-controller/package.json
  packages/rate-limit-controller/src/RateLimitController.test.ts
  packages/rate-limit-controller/src/RateLimitController.ts
  packages/signature-controller/package.json
  packages/signature-controller/src/SignatureController.ts
  yarn.lock
Labels: team-shared-libraries

#2052 Release 92.0.0
  package.json
  packages/accounts-controller/CHANGELOG.md
  packages/accounts-controller/package.json
  packages/keyring-controller/CHANGELOG.md
  packages/keyring-controller/package.json
  packages/signature-controller/CHANGELOG.md
  packages/signature-controller/package.json
  yarn.lock
Labels: team-shared-libraries

#2058 [`base-controller`] Add `RestrictedControllerMessenger` tests for runtime error handling
  packages/base-controller/jest.config.js
  packages/base-controller/src/RestrictedControllerMessenger.test.ts
  packages/base-controller/src/RestrictedControllerMessenger.ts
Labels: team-shared-libraries

#2074 Fix main branch CI failure by increasing jest `testTimeout` option
  jest.config.packages.js
Labels: bug, team-shared-libraries

#2078 Deprecate `BaseControllerV1` and use `BaseControllerV2` as default
  packages/accounts-controller/src/AccountsController.ts
  packages/address-book-controller/src/AddressBookController.ts
  packages/announcement-controller/src/AnnouncementController.ts
  packages/approval-controller/src/ApprovalController.ts
  packages/assets-controllers/src/AccountTrackerController.ts
  packages/assets-controllers/src/AssetsContractController.ts
  packages/assets-controllers/src/NftController.ts
  packages/assets-controllers/src/TokenBalancesController.ts
  packages/assets-controllers/src/TokensController.ts
  packages/base-controller/src/BaseControllerV1.test.ts
  packages/base-controller/src/BaseControllerV1.ts
  packages/base-controller/src/index.ts
  packages/composable-controller/src/ComposableController.test.ts
  packages/composable-controller/src/ComposableController.ts
  packages/ens-controller/src/EnsController.ts
  packages/keyring-controller/src/KeyringController.ts
  packages/logging-controller/src/LoggingController.ts
  packages/message-manager/src/AbstractMessageManager.ts
  packages/name-controller/src/NameController.ts
  packages/network-controller/src/NetworkController.ts
  packages/notification-controller/src/NotificationController.ts
  packages/permission-controller/src/PermissionController.ts
  packages/permission-controller/src/SubjectMetadataController.ts
  packages/permission-log-controller/src/PermissionLogController.ts
  packages/phishing-controller/src/PhishingController.ts
  packages/polling-controller/src/PollingController.ts
  packages/preferences-controller/src/PreferencesController.ts
  packages/queued-request-controller/src/QueuedRequestController.ts
  packages/rate-limit-controller/src/RateLimitController.ts
  packages/selected-network-controller/src/SelectedNetworkController.ts
  packages/signature-controller/src/SignatureController.ts
  packages/transaction-controller/src/TransactionController.ts
Labels: team-shared-libraries

#1970 [queued-request-controller,selected-network-controller] Apply `MiddlewareMessenger` pattern, fix `any`
  packages/queued-request-controller/CHANGELOG.md
  packages/queued-request-controller/package.json
  packages/queued-request-controller/src/QueuedRequestController.test.ts
  packages/queued-request-controller/src/QueuedRequestController.ts
  packages/queued-request-controller/src/QueuedRequestMiddleware.test.ts
  packages/queued-request-controller/src/QueuedRequestMiddleware.ts
  packages/queued-request-controller/src/index.ts
  packages/queued-request-controller/tests/utils.ts
  packages/selected-network-controller/CHANGELOG.md
  packages/selected-network-controller/package.json
  packages/selected-network-controller/src/SelectedNetworkController.ts
  packages/selected-network-controller/src/SelectedNetworkMiddleware.ts
  packages/selected-network-controller/src/index.ts
  packages/selected-network-controller/tests/SelectedNetworkController.test.ts
  packages/selected-network-controller/tests/SelectedNetworkMiddleware.test.ts
  packages/selected-network-controller/tests/utils.ts
  yarn.lock
Labels: team-shared-libraries

#2071 Add process guide for migrating packages into the core monorepo
  docs/package-migration-process-guide.md
Labels: team-shared-libraries
