Repository MetaMask/core, pull requests merged in 2024-10, with the labels that each got.

#4746 fix(NOTIFY-1171): fix account syncing performance
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
  packages/profile-sync-controller/src/controllers/user-storage/accounts/user-storage.ts
  packages/profile-sync-controller/src/controllers/user-storage/services.ts
  packages/profile-sync-controller/src/controllers/user-storage/utils.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/utils.ts
  packages/profile-sync-controller/src/shared/encryption/cache.ts
  packages/profile-sync-controller/src/shared/encryption/encryption.ts
Labels: team-notifications

#4749 Release 211.0.0
  package.json
  packages/notification-services-controller/CHANGELOG.md
  packages/notification-services-controller/package.json
  packages/profile-sync-controller/CHANGELOG.md
  packages/profile-sync-controller/package.json
  yarn.lock
Labels: team-notifications

#4748 feat: support Etherscan API keys
  packages/transaction-controller/src/TransactionController.ts
  packages/transaction-controller/src/helpers/EtherscanRemoteTransactionSource.test.ts
  packages/transaction-controller/src/helpers/EtherscanRemoteTransactionSource.ts
  packages/transaction-controller/src/utils/etherscan.test.ts
  packages/transaction-controller/src/utils/etherscan.ts
Labels: team-confirmations

#4753 fix: remove boot cleanup on network switch
  packages/transaction-controller/src/TransactionController.ts
Labels: team-confirmations

#4750 chore: Update codeowners to match EM agreed ownership
  .github/CODEOWNERS
Labels: team-wallet-framework

#4755 fix(NOTIFY-1190): key generation bug for react native scrypt
  packages/profile-sync-controller/src/shared/encryption/encryption.ts
  packages/profile-sync-controller/src/shared/encryption/utils.ts
  packages/profile-sync-controller/src/shared/types/encryption.ts
Labels: team-notifications

#4757 Release 213.0.0
  package.json
  packages/notification-services-controller/package.json
  packages/profile-sync-controller/CHANGELOG.md
  packages/profile-sync-controller/package.json
  yarn.lock
Labels: team-notifications

#4758 feat(NOTIFY-1192): add DELETE endpoint support
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
  packages/profile-sync-controller/src/controllers/user-storage/__fixtures__/mockResponses.ts
  packages/profile-sync-controller/src/controllers/user-storage/__fixtures__/mockServices.ts
  packages/profile-sync-controller/src/controllers/user-storage/services.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/services.ts
  packages/profile-sync-controller/src/sdk/__fixtures__/mock-userstorage.ts
  packages/profile-sync-controller/src/sdk/user-storage.test.ts
  packages/profile-sync-controller/src/sdk/user-storage.ts
Labels: team-notifications

#4765 Release 215.0.0
  package.json
  packages/notification-services-controller/package.json
  packages/profile-sync-controller/CHANGELOG.md
  packages/profile-sync-controller/package.json
  yarn.lock
Labels: team-notifications

#4777 fix: do not sync imported accounts
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
Labels: team-notifications

#4776 feat(NOTIFY-1214): add support for DELETE ONE endpoint
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
  packages/profile-sync-controller/src/controllers/user-storage/__fixtures__/mockResponses.ts
  packages/profile-sync-controller/src/controllers/user-storage/__fixtures__/mockServices.ts
  packages/profile-sync-controller/src/controllers/user-storage/services.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/services.ts
  packages/profile-sync-controller/src/sdk/__fixtures__/mock-userstorage.ts
  packages/profile-sync-controller/src/sdk/user-storage.test.ts
  packages/profile-sync-controller/src/sdk/user-storage.ts
Labels: team-notifications

#4780 Feat/new mock web3 notifications
  packages/notification-services-controller/src/NotificationServicesController/__fixtures__/mock-raw-notifications.ts
  packages/notification-services-controller/src/NotificationServicesController/constants/notification-schema.ts
  packages/notification-services-controller/src/NotificationServicesController/types/on-chain-notification/on-chain-notification.ts
  packages/notification-services-controller/src/NotificationServicesController/types/on-chain-notification/schema.ts
Labels: team-notifications

#4783 Release 218.0.0
  package.json
  packages/notification-services-controller/CHANGELOG.md
  packages/notification-services-controller/package.json
Labels: team-notifications

#4790 feat: :sparkles: add the ability to view draft content for Contentful
  packages/notification-services-controller/src/NotificationServicesController/NotificationServicesController.ts
  packages/notification-services-controller/src/NotificationServicesController/services/feature-announcements.test.ts
  packages/notification-services-controller/src/NotificationServicesController/services/feature-announcements.ts
Labels: team-notifications

#4794 Release 219.0.0
  package.json
  packages/notification-services-controller/CHANGELOG.md
  packages/notification-services-controller/package.json
Labels: team-notifications

#4773 deps(json-rpc-engine): @metamask/rpc-errors@^6.3.1->^7.0.0
  packages/json-rpc-engine/package.json
  yarn.config.cjs
  yarn.lock
Labels: team-wallet-api-platform, team-wallet-framework

#4781 feat: add and use Accounts API for Account balance calls
  packages/assets-controllers/src/TokenDetectionController.test.ts
  packages/assets-controllers/src/TokenDetectionController.ts
  packages/assets-controllers/src/multi-chain-accounts-service/index.ts
  packages/assets-controllers/src/multi-chain-accounts-service/mocks/mock-get-balances.ts
  packages/assets-controllers/src/multi-chain-accounts-service/mocks/mock-get-supported-networks.ts
  packages/assets-controllers/src/multi-chain-accounts-service/multi-chain-accounts.test.ts
  packages/assets-controllers/src/multi-chain-accounts-service/multi-chain-accounts.ts
  packages/assets-controllers/src/multi-chain-accounts-service/types.ts
Labels: team-assets

#4818 feat: :sparkles: update notification types and tests
  packages/notification-services-controller/src/NotificationServicesController/__fixtures__/mock-raw-notifications.ts
  packages/notification-services-controller/src/NotificationServicesController/types/on-chain-notification/on-chain-notification.ts
  packages/notification-services-controller/src/NotificationServicesController/types/on-chain-notification/schema.ts
Labels: team-notifications

#4769 deps: @metamask/rpc-errors@^6.3.1->^7.0.0
  package.json
  packages/approval-controller/package.json
  packages/assets-controllers/package.json
  packages/eth-json-rpc-provider/src/safe-event-emitter-provider.test.ts
  packages/network-controller/package.json
  packages/permission-controller/package.json
  packages/queued-request-controller/package.json
  packages/rate-limit-controller/package.json
  packages/transaction-controller/package.json
  packages/user-operation-controller/package.json
  yarn.lock
Labels: team-wallet-framework, team-assets, team-confirmations, team-snaps

#4823 feat: passing fcmToken when using mobile
  packages/notification-services-controller/src/NotificationServicesPushController/NotificationServicesPushController.test.ts
  packages/notification-services-controller/src/NotificationServicesPushController/NotificationServicesPushController.ts
  packages/notification-services-controller/src/NotificationServicesPushController/services/services.test.ts
  packages/notification-services-controller/src/NotificationServicesPushController/services/services.ts
Labels: team-notifications

#4822 fix: add missing signature controller types for mobile
  packages/signature-controller/src/SignatureController.test.ts
  packages/signature-controller/src/SignatureController.ts
  packages/signature-controller/src/types.ts
Labels: team-confirmations

#4819 Release 224.0.0
  package.json
  packages/notification-services-controller/CHANGELOG.md
  packages/notification-services-controller/package.json
Labels: team-notifications

#4827 feat(controller-utils): support BigNumber as input to BNToHex
  packages/controller-utils/package.json
  packages/controller-utils/src/util.test.ts
  packages/controller-utils/src/util.ts
  yarn.lock
Labels: team-wallet-framework, team-security

#4828 deps(notification-services-controller): bignumber.js@^4.1.0->^9.1.2
  packages/controller-utils/package.json
  packages/notification-services-controller/package.json
  yarn.lock
Labels: team-wallet-framework, team-security, team-notifications

#4797 feat: remove global network from signature controller
  packages/signature-controller/package.json
  packages/signature-controller/src/SignatureController.test.ts
  packages/signature-controller/src/SignatureController.ts
  packages/signature-controller/src/types.ts
  packages/signature-controller/tsconfig.build.json
  packages/signature-controller/tsconfig.json
  yarn.lock
Labels: team-confirmations

#4820 fix: phishing detector validation to drop invalid configs from detector
  packages/phishing-controller/src/PhishingDetector.test.ts
  packages/phishing-controller/src/utils.test.ts
  packages/phishing-controller/src/utils.ts
Labels: team-product-safety

#4848 Release 229.0.0
  package.json
  packages/phishing-controller/CHANGELOG.md
  packages/phishing-controller/package.json
Labels: team-product-safety

#4850 chore: lower c2 blocklist fetch interval
  packages/phishing-controller/src/PhishingController.ts
Labels: team-product-safety

#4851 Release/230.0.0
  package.json
  packages/phishing-controller/CHANGELOG.md
  packages/phishing-controller/package.json
Labels: team-product-safety

#4842 Fix typos in controller guidelines
  docs/writing-controllers.md
Labels: team-wallet-framework

#4844 feat(controller-utils): support bn.js v4 input to BN functions
  packages/controller-utils/package.json
  packages/controller-utils/src/util.test.ts
  packages/controller-utils/src/util.ts
  yarn.lock
Labels: team-wallet-framework, team-security

#4853 fix: extension performance issues
  packages/phishing-controller/src/PhishingDetector.test.ts
  packages/phishing-controller/src/PhishingDetector.ts
  packages/phishing-controller/src/utils.test.ts
  packages/phishing-controller/src/utils.ts
Labels: team-product-safety

#4859 Release/231.0.0
  package.json
  packages/phishing-controller/CHANGELOG.md
  packages/phishing-controller/package.json
Labels: team-product-safety

#4876 Add `phishing-controller` to package release section of CODEOWNERS file
  .github/CODEOWNERS
Labels: team-wallet-framework

#4874 feat: add staking transaction types
  packages/transaction-controller/src/types.ts
  packages/user-operation-controller/src/utils/validation.test.ts
Labels: team-confirmations
