Repository MetaMask/core, pull requests merged in 2024-05, with the labels that each got.

#4216 Add estimate gas fee method
  packages/transaction-controller/jest.config.js
  packages/transaction-controller/src/TransactionController.test.ts
  packages/transaction-controller/src/TransactionController.ts
  packages/transaction-controller/src/gas-flows/DefaultGasFeeFlow.test.ts
  packages/transaction-controller/src/gas-flows/DefaultGasFeeFlow.ts
  packages/transaction-controller/src/gas-flows/LineaGasFeeFlow.test.ts
  packages/transaction-controller/src/gas-flows/LineaGasFeeFlow.ts
  packages/transaction-controller/src/gas-flows/TestGasFeeFlow.test.ts
  packages/transaction-controller/src/gas-flows/TestGasFeeFlow.ts
  packages/transaction-controller/src/helpers/GasFeePoller.test.ts
  packages/transaction-controller/src/helpers/GasFeePoller.ts
  packages/transaction-controller/src/index.ts
  packages/transaction-controller/src/types.ts
  packages/transaction-controller/src/utils/gas-fees.test.ts
  packages/transaction-controller/src/utils/gas-fees.ts
  packages/transaction-controller/src/utils/gas-flow.test.ts
  packages/transaction-controller/src/utils/gas-flow.ts
Labels: team-confirmations

#4257 refactor(accounts-controller): remove extra filter for normal accounts
  packages/accounts-controller/src/AccountsController.ts
  packages/accounts-controller/src/utils.ts
Labels: team-accounts

#4256 feat: add patch code from PR 23903 to keyringController.
  packages/keyring-controller/src/KeyringController.ts
Labels: team-shared-libraries, needs-dev-review

#4230 fix: Fix `StaticIntervalPollingController` not properly stopping polling if `_executePoll` was still pending
  packages/polling-controller/src/StaticIntervalPollingController.test.ts
  packages/polling-controller/src/StaticIntervalPollingController.ts
Labels: team-wallet-api-platform

#4265 Release 149.0.0
  package.json
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/package.json
  packages/user-operation-controller/package.json
  yarn.lock
Labels: team-confirmations

#4272 Release 149.0.0
  package.json
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/package.json
  packages/user-operation-controller/CHANGELOG.md
  packages/user-operation-controller/package.json
  yarn.lock
Labels: team-confirmations

#4277 deps(keyring-controller): Bump @keystonehq/metamask-airgapped-keyring to ^0.14.1
  packages/keyring-controller/package.json
  yarn.lock
Labels: dependencies

#4283 Add `useTransactionSimulations` preference
  packages/preferences-controller/src/PreferencesController.test.ts
  packages/preferences-controller/src/PreferencesController.ts
Labels: team-confirmations

#4285 Release 151.0.0
  package.json
  packages/assets-controllers/package.json
  packages/ens-controller/package.json
  packages/gas-fee-controller/package.json
  packages/network-controller/CHANGELOG.md
  packages/network-controller/package.json
  packages/polling-controller/package.json
  packages/queued-request-controller/package.json
  packages/selected-network-controller/package.json
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/package.json
  packages/user-operation-controller/package.json
  yarn.lock
Labels: team-transactions

#4227 feat: add ChainController
  README.md
  packages/chain-controller/CHANGELOG.md
  packages/chain-controller/LICENSE
  packages/chain-controller/README.md
  packages/chain-controller/jest.config.js
  packages/chain-controller/package.json
  packages/chain-controller/src/ChainController.test.ts
  packages/chain-controller/src/ChainController.ts
  packages/chain-controller/src/SnapChainProviderClient.test.ts
  packages/chain-controller/src/SnapChainProviderClient.ts
  packages/chain-controller/src/SnapHandlerClient.test.ts
  packages/chain-controller/src/SnapHandlerClient.ts
  packages/chain-controller/src/index.ts
  packages/chain-controller/tsconfig.build.json
  packages/chain-controller/tsconfig.json
  packages/chain-controller/typedoc.json
  tsconfig.build.json
  yarn.lock
Labels: team-accounts

#4282 feat(keyring-controller): allow non-evm addresses for non-evm methods/functions
  packages/keyring-controller/src/KeyringController.test.ts
  packages/keyring-controller/src/KeyringController.ts
Labels: team-accounts

#4242 feat: add new rates controller for non-EVM chains
  packages/assets-controllers/README.md
  packages/assets-controllers/src/CurrencyRateController.ts
  packages/assets-controllers/src/RatesController/RatesController.test.ts
  packages/assets-controllers/src/RatesController/RatesController.ts
  packages/assets-controllers/src/RatesController/index.ts
  packages/assets-controllers/src/RatesController/types.ts
  packages/assets-controllers/src/TokenRatesController.ts
  packages/assets-controllers/src/crypto-compare-service/crypto-compare.test.ts
  packages/assets-controllers/src/crypto-compare-service/crypto-compare.ts
  packages/assets-controllers/src/crypto-compare-service/index.ts
  packages/assets-controllers/src/crypto-compare.ts
  packages/assets-controllers/src/index.ts
Labels: team-accounts

#4301 fix: Migrate API usage from *.metafi & *.metaswap subdomains to *.cx.metamsk.io"
  packages/assets-controllers/src/TokenDetectionController.test.ts
  packages/assets-controllers/src/TokenListController.test.ts
  packages/assets-controllers/src/TokensController.test.ts
  packages/assets-controllers/src/assetsUtil.test.ts
  packages/assets-controllers/src/assetsUtil.ts
  packages/assets-controllers/src/token-prices-service/codefi-v2.test.ts
  packages/assets-controllers/src/token-prices-service/codefi-v2.ts
  packages/assets-controllers/src/token-service.ts
  packages/controller-utils/src/constants.ts
  packages/name-controller/src/providers/token.test.ts
  packages/name-controller/src/providers/token.ts
  packages/phishing-controller/src/PhishingController.ts
Labels: team-shared-libraries

#4313 Release/154.0.0
  package.json
  packages/phishing-controller/CHANGELOG.md
  packages/phishing-controller/package.json
Labels: team-shared-libraries

#4309 deps(network-controller): eth-block-tracker@8 -> @metamask/eth-block-tracker@9
  package.json
  packages/network-controller/package.json
  packages/network-controller/src/create-network-client.ts
  packages/network-controller/src/types.ts
  packages/transaction-controller/package.json
  packages/transaction-controller/src/TransactionController.test.ts
  packages/transaction-controller/src/TransactionController.ts
  packages/transaction-controller/src/helpers/MultichainTrackingHelper.test.ts
  packages/transaction-controller/src/helpers/MultichainTrackingHelper.ts
  packages/transaction-controller/src/utils/nonce.test.ts
  packages/transaction-controller/src/utils/nonce.ts
  tests/fake-block-tracker.ts
  yarn.lock
Labels: bug, dependencies

#4326 feat(accounts-controller): add getNextAvailableAccountName public method
  packages/accounts-controller/src/AccountsController.test.ts
  packages/accounts-controller/src/AccountsController.ts
Labels: team-accounts

#4292 chore(devDependencies): @lavamoat/allow-scripts@^3.0.2>^3.0.4
  package.json
  packages/json-rpc-engine/package.json
  packages/keyring-controller/package.json
  yarn.lock
Labels: dependencies

#4303 Add simulation data support to mobile transaction controller patch
  packages/transaction-controller/jest.config.js
  packages/transaction-controller/src/TransactionController.ts
  packages/transaction-controller/src/constants.ts
  packages/transaction-controller/src/errors.ts
  packages/transaction-controller/src/types.ts
  packages/transaction-controller/src/utils/simulation-api.test.ts
  packages/transaction-controller/src/utils/simulation-api.ts
  packages/transaction-controller/src/utils/simulation.test.ts
  packages/transaction-controller/src/utils/simulation.ts
Labels: team-confirmations

#4304 feat: migrate TokensController to BaseControllerV2
  packages/assets-controllers/src/TokenBalancesController.test.ts
  packages/assets-controllers/src/TokenBalancesController.ts
  packages/assets-controllers/src/TokenDetectionController.test.ts
  packages/assets-controllers/src/TokenRatesController.test.ts
  packages/assets-controllers/src/TokenRatesController.ts
  packages/assets-controllers/src/TokensController.test.ts
  packages/assets-controllers/src/TokensController.ts
  packages/assets-controllers/src/index.ts
Labels: team-wallet-framework

#4312 feat: migrate NftDetectionController to BaseControllerV2
  packages/assets-controllers/src/NftDetectionController.test.ts
  packages/assets-controllers/src/NftDetectionController.ts
  packages/controller-utils/src/constants.ts
Labels: team-wallet-framework

#3952 [composable-controller] Narrow class and messenger types by parameterizing over child controllers list
  packages/address-book-controller/src/AddressBookController.ts
  packages/assets-controllers/src/AccountTrackerController.ts
  packages/assets-controllers/src/AssetsContractController.ts
  packages/assets-controllers/src/NftController.ts
  packages/assets-controllers/src/TokenRatesController.ts
  packages/composable-controller/CHANGELOG.md
  packages/composable-controller/src/ComposableController.test.ts
  packages/composable-controller/src/ComposableController.ts
  packages/composable-controller/src/index.ts
  packages/message-manager/src/DecryptMessageManager.ts
  packages/message-manager/src/EncryptionPublicKeyManager.ts
  packages/message-manager/src/MessageManager.ts
  packages/message-manager/src/PersonalMessageManager.ts
  packages/message-manager/src/TypedMessageManager.ts
Labels: team-wallet-framework

#4310 feat: migrate NftController to BaseControllerV2
  packages/assets-controllers/src/NftController.test.ts
  packages/assets-controllers/src/NftController.ts
  packages/assets-controllers/src/NftDetectionController.test.ts
  packages/assets-controllers/src/NftDetectionController.ts
  packages/assets-controllers/src/index.ts
Labels: team-wallet-framework

#4335 deps: async-mutex@^0.2.6->^0.5.0
  packages/assets-controllers/package.json
  packages/keyring-controller/package.json
  packages/name-controller/package.json
  packages/network-controller/package.json
  packages/transaction-controller/package.json
  yarn.lock
Labels: dependencies, team-security

#4330 feat: add getSelectedMultichainAccount and listMultichainAccounts
  packages/accounts-controller/jest.config.js
  packages/accounts-controller/src/AccountsController.test.ts
  packages/accounts-controller/src/AccountsController.ts
  packages/accounts-controller/src/index.ts
  packages/accounts-controller/src/tests/mocks.test.ts
  packages/accounts-controller/src/tests/mocks.ts
Labels: team-accounts

#4343 fix: TransactionController afterSign hook should be allowed to modify the transaction
  packages/transaction-controller/src/TransactionController.ts
Labels: team-transactions

#3611 Bump min Node version to 18.18; use LTS for dev
  .github/workflows/lint-build-test.yml
  .nvmrc
  constraints.pro
  docs/contributing.md
  package.json
  packages/accounts-controller/package.json
  packages/address-book-controller/package.json
  packages/announcement-controller/package.json
  packages/approval-controller/package.json
  packages/assets-controllers/package.json
  packages/base-controller/package.json
  packages/build-utils/package.json
  packages/chain-controller/package.json
  packages/composable-controller/package.json
  packages/controller-utils/package.json
  packages/ens-controller/package.json
  packages/eth-json-rpc-provider/package.json
  packages/gas-fee-controller/package.json
  packages/json-rpc-engine/package.json
  packages/json-rpc-middleware-stream/package.json
  packages/keyring-controller/package.json
  packages/logging-controller/package.json
  packages/message-manager/package.json
  packages/name-controller/package.json
  packages/network-controller/package.json
  packages/notification-controller/package.json
  packages/permission-controller/package.json
  packages/permission-log-controller/package.json
  packages/phishing-controller/package.json
  packages/polling-controller/package.json
  packages/preferences-controller/package.json
  packages/profile-sync-controller/package.json
  packages/queued-request-controller/package.json
  packages/rate-limit-controller/package.json
  packages/selected-network-controller/package.json
  packages/signature-controller/package.json
  packages/transaction-controller/package.json
  packages/user-operation-controller/package.json
Labels: team-wallet-framework
