Repository MetaMask/core, pull requests merged in 2024-04, with the labels that each got.

#4131 Release 134.0.0
  package.json
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/package.json
  packages/user-operation-controller/package.json
  yarn.lock
Labels: team-confirmations-system

#4122 Support wrapped ERC20 and legacy ERC721 in simulations
  packages/transaction-controller/src/constants.ts
  packages/transaction-controller/src/utils/simulation.test.ts
  packages/transaction-controller/src/utils/simulation.ts
Labels: team-confirmations-system

#4090 Update snap and keyring api dependencies and fix tests
  packages/accounts-controller/package.json
  packages/assets-controllers/package.json
  packages/keyring-controller/package.json
  packages/keyring-controller/src/KeyringController.test.ts
  packages/keyring-controller/src/KeyringController.ts
  packages/user-operation-controller/src/UserOperationController.test.ts
  packages/user-operation-controller/src/UserOperationController.ts
  packages/user-operation-controller/src/helpers/SnapSmartContractAccount.test.ts
  packages/user-operation-controller/src/helpers/SnapSmartContractAccount.ts
  packages/user-operation-controller/src/types.ts
  packages/user-operation-controller/src/utils/chain-id.test.ts
  packages/user-operation-controller/src/utils/chain-id.ts
  yarn.lock
Labels: team-accounts

#4149 Fix layer 1 gas fee polling
  packages/transaction-controller/jest.config.js
  packages/transaction-controller/src/TransactionController.test.ts
  packages/transaction-controller/src/TransactionController.ts
  packages/transaction-controller/src/helpers/GasFeePoller.test.ts
  packages/transaction-controller/src/helpers/GasFeePoller.ts
  packages/transaction-controller/src/utils/layer1-gas-fee-flow.ts
Labels: team-confirmations-system

#4089 fix(accounts): fix normal account indexing naming with index gap
  packages/accounts-controller/src/AccountsController.test.ts
  packages/accounts-controller/src/AccountsController.ts
  packages/accounts-controller/src/utils.ts
Labels: team-accounts

#4165 Fix/flush on revoke perms 2
  packages/queued-request-controller/src/QueuedRequestController.test.ts
  packages/queued-request-controller/src/QueuedRequestController.ts
Labels: team-wallet-api-platform, amon-hen-blocker

#4130 Fix: Keep proxies in sync across "Select networks for each site" toggling on/off
  packages/selected-network-controller/src/SelectedNetworkController.ts
  packages/selected-network-controller/tests/SelectedNetworkController.test.ts
Labels: team-wallet-api-platform, amon-hen-blocker

#4168 fix: add HD keyring check to `persistAllKeyrings`
  packages/keyring-controller/src/KeyringController.test.ts
  packages/keyring-controller/src/KeyringController.ts
  packages/keyring-controller/src/constants.ts
Labels: team-accounts

#4181 [keyring-controller] Avoid calling mutable public functions internally
  packages/keyring-controller/jest.config.js
  packages/keyring-controller/src/KeyringController.test.ts
  packages/keyring-controller/src/KeyringController.ts
Labels: team-shared-libraries

#4209 comment: add TODO comment for ApprovalRequest type to use ApprovalType
  packages/approval-controller/src/ApprovalController.ts
Labels: team-confirmations

#4210 Remove fee history fallback
  packages/gas-fee-controller/jest.config.js
  packages/gas-fee-controller/src/GasFeeController.test.ts
  packages/gas-fee-controller/src/GasFeeController.ts
  packages/gas-fee-controller/src/determineGasFeeCalculations.test.ts
  packages/gas-fee-controller/src/determineGasFeeCalculations.ts
  packages/gas-fee-controller/src/fetchBlockFeeHistory.test.ts
  packages/gas-fee-controller/src/fetchBlockFeeHistory.ts
  packages/gas-fee-controller/src/fetchGasEstimatesViaEthFeeHistory.test.ts
  packages/gas-fee-controller/src/fetchGasEstimatesViaEthFeeHistory.ts
  packages/gas-fee-controller/src/fetchGasEstimatesViaEthFeeHistory/calculateGasFeeEstimatesForPriorityLevels.test.ts
  packages/gas-fee-controller/src/fetchGasEstimatesViaEthFeeHistory/calculateGasFeeEstimatesForPriorityLevels.ts
  packages/gas-fee-controller/src/fetchGasEstimatesViaEthFeeHistory/fetchLatestBlock.ts
  packages/gas-fee-controller/src/fetchGasEstimatesViaEthFeeHistory/medianOf.ts
  packages/gas-fee-controller/src/fetchGasEstimatesViaEthFeeHistory/types.ts
Labels: team-confirmations

#4217 fix: simulation should handle NFT mints
  packages/transaction-controller/src/utils/simulation.test.ts
  packages/transaction-controller/src/utils/simulation.ts
Labels: team-confirmations-system
