Repository MetaMask/core, pull requests merged in 2024-01, with the labels that each got.

#3705 Addition of "fallback" Variation to the NameController for Petnames
  packages/name-controller/src/NameController.test.ts
  packages/name-controller/src/NameController.ts
Labels: team-confirmations-system

#3681 Estimate gas fees for user operations
  packages/user-operation-controller/package.json
  packages/user-operation-controller/src/UserOperationController.test.ts
  packages/user-operation-controller/src/UserOperationController.ts
  packages/user-operation-controller/src/helpers/Bundler.ts
  packages/user-operation-controller/src/helpers/PendingUserOperationTracker.ts
  packages/user-operation-controller/src/types.ts
  packages/user-operation-controller/src/utils/gas-fees.test.ts
  packages/user-operation-controller/src/utils/gas-fees.ts
  packages/user-operation-controller/src/utils/gas.test.ts
  packages/user-operation-controller/src/utils/gas.ts
  packages/user-operation-controller/src/utils/transaction.test.ts
  packages/user-operation-controller/src/utils/transaction.ts
  packages/user-operation-controller/tsconfig.build.json
  packages/user-operation-controller/tsconfig.json
  yarn.lock
Labels: team-confirmations-system

#3750 feat: migrate token balances controller to base controller v2
  packages/assets-controllers/src/TokenBalancesController.test.ts
  packages/assets-controllers/src/TokenBalancesController.ts
  packages/assets-controllers/src/TokenRatesController.test.ts
  packages/assets-controllers/src/index.ts
  packages/transaction-controller/src/TransactionController.test.ts
  tests/helpers.ts
Labels: team-shared-libraries

#3802 fix: quick succession of submit password causing Accounts Controller state to be cleared
  packages/accounts-controller/src/AccountsController.test.ts
  packages/accounts-controller/src/AccountsController.ts
Labels: team-accounts

#3803 fix: custody keyring name
  packages/keyring-controller/src/KeyringController.ts
Labels: team-accounts

#3810 Release/110.0.0
  package.json
  packages/accounts-controller/CHANGELOG.md
  packages/accounts-controller/package.json
  packages/keyring-controller/CHANGELOG.md
  packages/keyring-controller/package.json
  packages/signature-controller/CHANGELOG.md
  packages/signature-controller/package.json
  yarn.lock
Labels: team-accounts

#3844 Use account snap by default in user operations
  packages/user-operation-controller/package.json
  packages/user-operation-controller/src/UserOperationController.test.ts
  packages/user-operation-controller/src/UserOperationController.ts
  packages/user-operation-controller/src/helpers/SnapSmartContractAccount.test.ts
  packages/user-operation-controller/src/helpers/SnapSmartContractAccount.ts
  packages/user-operation-controller/src/types.ts
  packages/user-operation-controller/src/utils/transaction.test.ts
  packages/user-operation-controller/src/utils/transaction.ts
  packages/user-operation-controller/src/utils/validation.test.ts
  packages/user-operation-controller/src/utils/validation.ts
  packages/user-operation-controller/tsconfig.build.json
  packages/user-operation-controller/tsconfig.json
  yarn.lock
Labels: team-confirmations-system
