Repository MetaMask/core, pull requests merged in 2024-12, with the labels that each got.

#5011 chore: Update `@ts-bridge/cli` to `0.6.1`
  package.json
  tsconfig.build.json
  tsconfig.json
  yarn.lock
Labels: team-wallet-framework

#4996 Don't export Allowed{Actions,Events} in example controllers
  examples/example-controllers/src/gas-prices-controller.ts
  examples/example-controllers/src/pet-names-controller.ts
Labels: team-wallet-framework

#4981 feat: revamp user storage encryption process
  packages/profile-sync-controller/src/controllers/user-storage/__fixtures__/mockResponses.ts
  packages/profile-sync-controller/src/controllers/user-storage/services.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/services.ts
  packages/profile-sync-controller/src/sdk/__fixtures__/mock-userstorage.ts
  packages/profile-sync-controller/src/sdk/user-storage.test.ts
  packages/profile-sync-controller/src/sdk/user-storage.ts
  packages/profile-sync-controller/src/shared/encryption/cache.ts
  packages/profile-sync-controller/src/shared/encryption/constants.ts
  packages/profile-sync-controller/src/shared/encryption/encryption.test.ts
  packages/profile-sync-controller/src/shared/encryption/encryption.ts
Labels: team-identity

#4968 [composable-controller] perf: Optimize expensive reduce operations, fix metadata instantiation
  packages/composable-controller/CHANGELOG.md
  packages/composable-controller/src/ComposableController.test.ts
  packages/composable-controller/src/ComposableController.ts
Labels: team-wallet-framework, team-tiger, area-performance

#4927 feat: detect incoming transactions using accounts API
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/jest.config.js
  packages/transaction-controller/src/TransactionController.test.ts
  packages/transaction-controller/src/TransactionController.ts
  packages/transaction-controller/src/TransactionControllerIntegration.test.ts
  packages/transaction-controller/src/api/accounts-api.test.ts
  packages/transaction-controller/src/api/accounts-api.ts
  packages/transaction-controller/src/constants.ts
  packages/transaction-controller/src/helpers/AccountsApiRemoteTransactionSource.test.ts
  packages/transaction-controller/src/helpers/AccountsApiRemoteTransactionSource.ts
  packages/transaction-controller/src/helpers/EtherscanRemoteTransactionSource.test.ts
  packages/transaction-controller/src/helpers/EtherscanRemoteTransactionSource.ts
  packages/transaction-controller/src/helpers/IncomingTransactionHelper.test.ts
  packages/transaction-controller/src/helpers/IncomingTransactionHelper.ts
  packages/transaction-controller/src/helpers/MultichainTrackingHelper.test.ts
  packages/transaction-controller/src/helpers/MultichainTrackingHelper.ts
  packages/transaction-controller/src/index.ts
  packages/transaction-controller/src/types.ts
  packages/transaction-controller/src/utils/etherscan.test.ts
  packages/transaction-controller/src/utils/etherscan.ts
  packages/transaction-controller/tests/EtherscanMocks.ts
Labels: team-confirmations

#5023 Release 263.0.0
  package.json
  packages/composable-controller/CHANGELOG.md
  packages/composable-controller/package.json
Labels: team-wallet-framework

#5028 fix: Fixes in signature decoding functionality
  packages/signature-controller/src/utils/decoding-api.test.ts
  packages/signature-controller/src/utils/decoding-api.ts
  packages/signature-controller/src/utils/normalize.test.ts
  packages/signature-controller/src/utils/normalize.ts
Labels: team-confirmations

#5042 Add label for use in github project auto add workflow
  .github/workflows/create-update-issues.yaml
Labels: team-wallet-framework

#4695 refactor: use new `@metamask/keyring-api` layout (split packages)
  packages/accounts-controller/package.json
  packages/accounts-controller/src/AccountsController.test.ts
  packages/accounts-controller/src/AccountsController.ts
  packages/accounts-controller/src/tests/mocks.ts
  packages/assets-controllers/package.json
  packages/assets-controllers/src/AccountTrackerController.test.ts
  packages/assets-controllers/src/NftController.test.ts
  packages/assets-controllers/src/NftController.ts
  packages/assets-controllers/src/TokenDetectionController.test.ts
  packages/assets-controllers/src/TokenRatesController.test.ts
  packages/assets-controllers/src/TokenRatesController.ts
  packages/assets-controllers/src/TokensController.test.ts
  packages/assets-controllers/src/TokensController.ts
  packages/chain-controller/package.json
  packages/chain-controller/src/ChainController.test.ts
  packages/chain-controller/src/ChainController.ts
  packages/chain-controller/src/SnapHandlerClient.ts
  packages/keyring-controller/package.json
  packages/keyring-controller/src/KeyringController.test.ts
  packages/keyring-controller/src/KeyringController.ts
  packages/keyring-controller/tests/mocks/mockErc4337Keyring.ts
  packages/keyring-controller/tests/mocks/mockKeyring.ts
  packages/profile-sync-controller/package.json
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
  packages/profile-sync-controller/src/controllers/user-storage/__fixtures__/mockAccounts.ts
  packages/profile-sync-controller/src/controllers/user-storage/accounts/user-storage.ts
  yarn.lock
Labels: team-accounts

#5051 feat(3742): Feature Flag Values with Scope Based on threshold
  packages/remote-feature-flag-controller/CHANGELOG.md
  packages/remote-feature-flag-controller/package.json
  packages/remote-feature-flag-controller/src/remote-feature-flag-controller-types.ts
  packages/remote-feature-flag-controller/src/remote-feature-flag-controller.test.ts
  packages/remote-feature-flag-controller/src/remote-feature-flag-controller.ts
  packages/remote-feature-flag-controller/src/utils/user-segmentation-utils.test.ts
  packages/remote-feature-flag-controller/src/utils/user-segmentation-utils.ts
  yarn.lock
Labels: team-extension-platform

#5086 chore(codeowners): Add Wallet API team as CODEOWNERS for multichain package
  .github/CODEOWNERS
Labels: team-wallet-api-platform, team-wallet-framework

#5093 fix: Prevent invalid gas limit
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/src/utils/validation.test.ts
  packages/transaction-controller/src/utils/validation.ts
Labels: team-confirmations

#5095 Release 275.0.0
  package.json
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/package.json
  packages/user-operation-controller/package.json
  yarn.lock
Labels: team-confirmations
