Repository MetaMask/core, pull requests merged in 2024-06, with the labels that each got.

#4270 fix: Mutex never gets released on refresh function of AccountTrackerController
  packages/assets-controllers/src/AccountTrackerController.ts
Labels: needs-dev-review

#4355 deps: @metamask/keyring-api@^6.1.1->^6.4.0
  packages/accounts-controller/package.json
  packages/accounts-controller/src/AccountsController.test.ts
  packages/accounts-controller/src/tests/mocks.ts
  packages/assets-controllers/package.json
  packages/chain-controller/package.json
  packages/keyring-controller/package.json
  yarn.lock
Labels: dependencies, team-security

#4364 fix: remove value from price api call
  packages/assets-controllers/src/TokenRatesController.test.ts
  packages/assets-controllers/src/TokenRatesController.ts
  packages/assets-controllers/src/assetsUtil.test.ts
  packages/assets-controllers/src/assetsUtil.ts
  packages/assets-controllers/src/token-prices-service/abstract-token-prices-service.ts
  packages/assets-controllers/src/token-prices-service/codefi-v2.test.ts
  packages/assets-controllers/src/token-prices-service/codefi-v2.ts
Labels: team-assets

#4349 fix: support skipping updates to the simulation history for clients with disabled history
  packages/transaction-controller/src/TransactionController.ts
Labels: team-confirmations

#4345 chore(test): Refactor FakeBlockTracker provider injection
  packages/assets-controllers/src/NftDetectionController.test.ts
  packages/network-controller/tests/NetworkController.test.ts
  packages/network-controller/tests/helpers.ts
  packages/transaction-controller/package.json
  packages/transaction-controller/src/TransactionController.test.ts
  tests/fake-block-tracker.ts
  yarn.lock
Labels: team-security

#4225 refactor: update account tracker to use selected account
  packages/assets-controllers/src/AccountTrackerController.test.ts
  packages/assets-controllers/src/AccountTrackerController.ts
Labels: team-accounts

#4388 fix: add `SelectedNetworkController` setNetworkClientId useRequestQueuePreference guard
  packages/selected-network-controller/src/SelectedNetworkController.ts
  packages/selected-network-controller/tests/SelectedNetworkController.test.ts
Labels: team-wallet-api-platform

#4405 chore(deps): bump @metamask/{keyring-api,eth-snap-keyring}
  packages/accounts-controller/package.json
  packages/assets-controllers/package.json
  packages/chain-controller/package.json
  packages/keyring-controller/package.json
  packages/transaction-controller/package.json
  yarn.lock
Labels: team-accounts

#4363 fix: remove setting new account as the last selected account
  packages/accounts-controller/src/AccountsController.test.ts
  packages/accounts-controller/src/AccountsController.ts
Labels: team-accounts

#4407 feat: upgrade AccountTrackerController to BaseControllerV2
  packages/assets-controllers/src/AccountTrackerController.test.ts
  packages/assets-controllers/src/AccountTrackerController.ts
  packages/assets-controllers/src/index.ts
Labels: team-wallet-framework

#4423 feat: change `queued-request-controller` methods array params to callbacks
  packages/queued-request-controller/src/QueuedRequestController.test.ts
  packages/queued-request-controller/src/QueuedRequestController.ts
  packages/queued-request-controller/src/QueuedRequestMiddleware.test.ts
  packages/queued-request-controller/src/QueuedRequestMiddleware.ts
Labels: team-wallet-api-platform

#4431 Release 162.0.0
  package.json
  packages/queued-request-controller/CHANGELOG.md
  packages/queued-request-controller/package.json
Labels: team-wallet-api-platform

#4437 refactor: update notification package exports
  packages/notification-services-controller/src/NotificationServicesController/NotificationServicesController.test.ts
  packages/notification-services-controller/src/NotificationServicesController/NotificationServicesController.ts
  packages/notification-services-controller/src/NotificationServicesController/index.ts
  packages/notification-services-controller/src/NotificationServicesPushController/NotificationServicesPushController.test.ts
  packages/notification-services-controller/src/NotificationServicesPushController/NotificationServicesPushController.ts
  packages/notification-services-controller/src/NotificationServicesPushController/index.ts
  packages/profile-sync-controller/src/controllers/authentication/index.ts
  packages/profile-sync-controller/src/controllers/user-storage/encryption/index.ts
  packages/profile-sync-controller/src/controllers/user-storage/index.ts
  packages/profile-sync-controller/src/sdk/encryption.ts
Labels: team-notifications

#4436 Release 163.0.0
  package.json
  packages/notification-services-controller/package.json
  packages/profile-sync-controller/CHANGELOG.md
  packages/profile-sync-controller/package.json
  yarn.lock
Labels: team-notifications

#4439 refactor: add back profile sync dependency
  packages/notification-services-controller/package.json
  yarn.lock
Labels: team-notifications

#4380 docs: document TransactionStatus enum
  packages/transaction-controller/src/types.ts
Labels: team-transactions

#4219 fix: update tokens controllers to use selectedAccountId instead of selectedAddress
  packages/assets-controllers/src/TokenBalancesController.test.ts
  packages/assets-controllers/src/TokenBalancesController.ts
  packages/assets-controllers/src/TokenDetectionController.test.ts
  packages/assets-controllers/src/TokenDetectionController.ts
  packages/assets-controllers/src/TokenRatesController.test.ts
  packages/assets-controllers/src/TokenRatesController.ts
  packages/assets-controllers/src/TokensController.test.ts
  packages/assets-controllers/src/TokensController.ts
Labels: team-accounts

#4456 feat: Focus approval request UI when a request is queued
  packages/queued-request-controller/src/QueuedRequestController.test.ts
  packages/queued-request-controller/src/QueuedRequestController.ts
Labels: team-wallet-api-platform

#4322 fix: update handleAccountRemoved logic
  packages/accounts-controller/src/AccountsController.test.ts
  packages/accounts-controller/src/AccountsController.ts
  packages/accounts-controller/src/utils.ts
Labels: team-accounts

#4460 Release/166.0.0
  package.json
  packages/accounts-controller/CHANGELOG.md
  packages/accounts-controller/package.json
  packages/assets-controllers/CHANGELOG.md
  packages/assets-controllers/package.json
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/package.json
  packages/user-operation-controller/CHANGELOG.md
  packages/user-operation-controller/package.json
  yarn.lock
Labels: team-accounts

#4463 chore: reduce diffs to GasFeeController.test.ts introduced by 2b1841c
  packages/gas-fee-controller/src/GasFeeController.test.ts
Labels: team-transactions

#4441 fix: notification services controller mobile fixes
  packages/notification-services-controller/src/NotificationServicesController/NotificationServicesController.ts
  packages/notification-services-controller/src/NotificationServicesController/__fixtures__/index.ts
  packages/notification-services-controller/src/NotificationServicesController/constants/notification-schema.ts
  packages/notification-services-controller/src/NotificationServicesController/index.ts
  packages/notification-services-controller/src/NotificationServicesController/ui/constants.ts
  packages/notification-services-controller/src/NotificationServicesController/ui/index.ts
  packages/notification-services-controller/src/NotificationServicesPushController/NotificationServicesPushController.ts
  packages/notification-services-controller/src/NotificationServicesPushController/__fixtures__/index.ts
  packages/notification-services-controller/src/NotificationServicesPushController/services/push/push-web.ts
  packages/notification-services-controller/tsconfig.json
  packages/profile-sync-controller/src/controllers/authentication/AuthenticationController.ts
  packages/profile-sync-controller/src/controllers/authentication/__fixtures__/index.ts
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
  packages/profile-sync-controller/src/controllers/user-storage/__fixtures__/index.ts
  packages/profile-sync-controller/src/sdk/authentication-jwt-bearer/types.ts
  packages/profile-sync-controller/src/sdk/env.ts
Labels: team-notifications

#4469 Release/168.0.0
  packages/notification-services-controller/CHANGELOG.md
  packages/notification-services-controller/package.json
  packages/profile-sync-controller/CHANGELOG.md
  packages/profile-sync-controller/package.json
  yarn.lock
Labels: team-notifications

#4473 Release/168.0.0
  package.json
  packages/notification-services-controller/CHANGELOG.md
  packages/notification-services-controller/package.json
  packages/profile-sync-controller/CHANGELOG.md
  packages/profile-sync-controller/package.json
  yarn.lock
Labels: team-notifications
