Repository MetaMask/core, pull requests merged in 2024-09, with the labels that each got.

#4626 feat(NOTIFY-998): add logic around the new get all feature entries endpoint
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
  packages/profile-sync-controller/src/controllers/user-storage/__fixtures__/mockResponses.ts
  packages/profile-sync-controller/src/controllers/user-storage/__fixtures__/mockServices.ts
  packages/profile-sync-controller/src/controllers/user-storage/schema.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/schema.ts
  packages/profile-sync-controller/src/controllers/user-storage/services.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/services.ts
  packages/profile-sync-controller/src/sdk/__fixtures__/mock-userstorage.ts
  packages/profile-sync-controller/src/sdk/user-storage.test.ts
  packages/profile-sync-controller/src/sdk/user-storage.ts
Labels: team-notifications

#4604 refactor: add multiple file exports for notifications controllers
  packages/notification-services-controller/notification-services/constants/package.json
  packages/notification-services-controller/notification-services/mocks/package.json
  packages/notification-services-controller/notification-services/package.json
  packages/notification-services-controller/notification-services/processors/package.json
  packages/notification-services-controller/notification-services/types/package.json
  packages/notification-services-controller/notification-services/ui/package.json
  packages/notification-services-controller/package.json
  packages/notification-services-controller/push-services/mocks/package.json
  packages/notification-services-controller/push-services/package.json
  packages/notification-services-controller/push-services/types/package.json
  packages/notification-services-controller/push-services/utils/package.json
  packages/notification-services-controller/src/NotificationServicesController/index.ts
  packages/notification-services-controller/src/NotificationServicesPushController/index.ts
  packages/notification-services-controller/src/NotificationServicesPushController/utils/get-notification-message.test.ts
  packages/profile-sync-controller/auth/mocks/package.json
  packages/profile-sync-controller/auth/package.json
  packages/profile-sync-controller/package.json
  packages/profile-sync-controller/sdk/package.json
  packages/profile-sync-controller/src/controllers/authentication/index.ts
  packages/profile-sync-controller/src/controllers/authentication/services.ts
  packages/profile-sync-controller/src/controllers/user-storage/index.ts
  packages/profile-sync-controller/src/controllers/user-storage/services.ts
  packages/profile-sync-controller/user-storage/mocks/package.json
  packages/profile-sync-controller/user-storage/package.json
Labels: team-notifications

#4649 refactor: reuse user storage encryption in profile sync SDK
  packages/profile-sync-controller/src/sdk/encryption.test.ts
  packages/profile-sync-controller/src/sdk/encryption.ts
Labels: team-notifications

#4620 feat: :sparkles: add support for different link types in feature announcements
  packages/notification-services-controller/src/NotificationServicesController/services/feature-announcements.ts
  packages/notification-services-controller/src/NotificationServicesController/types/feature-announcement/feature-announcement.ts
  packages/notification-services-controller/src/NotificationServicesController/types/feature-announcement/type-feature-announcement.ts
  packages/notification-services-controller/src/NotificationServicesController/types/feature-announcement/type-links.ts
Labels: team-notifications

#4650 refactor(notifications): cleanup notification subpath exports
  packages/notification-services-controller/notification-services/constants/package.json
  packages/notification-services-controller/notification-services/mocks/package.json
  packages/notification-services-controller/notification-services/package.json
  packages/notification-services-controller/notification-services/processors/package.json
  packages/notification-services-controller/notification-services/types/package.json
  packages/notification-services-controller/notification-services/ui/package.json
  packages/notification-services-controller/package.json
  packages/notification-services-controller/push-services/mocks/package.json
  packages/notification-services-controller/push-services/package.json
  packages/notification-services-controller/push-services/types/package.json
  packages/notification-services-controller/push-services/utils/package.json
  packages/notification-services-controller/src/NotificationServicesController/index.ts
  packages/notification-services-controller/src/NotificationServicesPushController/index.ts
  packages/profile-sync-controller/auth/mocks/package.json
  packages/profile-sync-controller/auth/package.json
  packages/profile-sync-controller/sdk/package.json
  packages/profile-sync-controller/user-storage/mocks/package.json
  packages/profile-sync-controller/user-storage/package.json
Labels: team-notifications

#4629 feat(NOTIFY-1001): add granular account syncing
  packages/profile-sync-controller/package.json
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
  packages/profile-sync-controller/src/controllers/user-storage/__fixtures__/mockAccounts.ts
  packages/profile-sync-controller/src/controllers/user-storage/accounts/constants.ts
  packages/profile-sync-controller/src/controllers/user-storage/accounts/user-storage.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/accounts/user-storage.ts
  packages/profile-sync-controller/tsconfig.build.json
  packages/profile-sync-controller/tsconfig.json
  yarn.lock
Labels: team-notifications

#4657 Release 195.0.0
  package.json
  packages/notification-services-controller/CHANGELOG.md
  packages/notification-services-controller/package.json
  packages/profile-sync-controller/CHANGELOG.md
  packages/profile-sync-controller/package.json
  yarn.lock
Labels: team-notifications

#4659 feat: add throttling to account syncing
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
Labels: team-notifications

#4661 Release 196.0.0
  package.json
  packages/notification-services-controller/CHANGELOG.md
  packages/notification-services-controller/package.json
  packages/profile-sync-controller/CHANGELOG.md
  packages/profile-sync-controller/package.json
  yarn.lock
Labels: team-notifications

#4653 fix: ensure push notifications are able to be subscribed to when the wallet is locked
  packages/notification-services-controller/src/NotificationServicesController/NotificationServicesController.ts
  packages/notification-services-controller/src/NotificationServicesPushController/NotificationServicesPushController.test.ts
  packages/notification-services-controller/src/NotificationServicesPushController/NotificationServicesPushController.ts
  packages/notification-services-controller/src/NotificationServicesPushController/services/services.test.ts
Labels: team-notifications

#4660 feat: add `accountRenamed` event to `AccountsController`
  packages/accounts-controller/src/AccountsController.test.ts
  packages/accounts-controller/src/AccountsController.ts
Labels: team-notifications

#4589 feat(NOTIFY-1016): add `nameLastUpdatedAt` timestamp when setting account name
  packages/accounts-controller/src/AccountsController.test.ts
  packages/accounts-controller/src/AccountsController.ts
Labels: team-notifications

#4666 Release 197.0.0
  package.json
  packages/notification-services-controller/CHANGELOG.md
  packages/notification-services-controller/package.json
Labels: team-notifications

#4665 feat(NOTIFY-1046): attach account sync upwards sync to `AccountsController` events
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
Labels: team-notifications

#4553 Add PhishingDetector to export
  packages/phishing-controller/src/index.ts
Labels: enhancement

#4672 fix: update polygon symbol from MATIC to POL
  packages/notification-services-controller/src/NotificationServicesController/constants/notification-schema.ts
Labels: team-notifications

#4673 refactor: move contentful as a dev dependency
  packages/notification-services-controller/package.json
Labels: team-notifications

#4675 feat(NOTIFY-1079): various account syncing improvements
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
Labels: team-notifications

#4680 Release 200.0.0
  package.json
  packages/accounts-controller/CHANGELOG.md
  packages/accounts-controller/package.json
  packages/assets-controllers/package.json
  packages/profile-sync-controller/package.json
  packages/transaction-controller/package.json
  yarn.lock
Labels: team-notifications

#4684 feat: scaffolding - update storage schema
  packages/profile-sync-controller/src/controllers/user-storage/schema.ts
  packages/profile-sync-controller/src/controllers/user-storage/services.ts
Labels: team-notifications

#4687 feat: network-syncing and user storage controller integration
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
  packages/profile-sync-controller/src/controllers/user-storage/__fixtures__/test-utils.ts
  packages/profile-sync-controller/src/controllers/user-storage/network-syncing/controller-integration.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/network-syncing/controller-integration.ts
Labels: team-notifications

#4690 feat: add a `canSync` check for account syncing
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
Labels: team-notifications

#4693 refactor: use `internalAccount` instead of account address for granular updates
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
Labels: team-notifications

#4694 feat: network sync - add main sync logic
  packages/profile-sync-controller/src/controllers/user-storage/network-syncing/__fixtures__/mockNetwork.ts
  packages/profile-sync-controller/src/controllers/user-storage/network-syncing/controller-integration.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/network-syncing/controller-integration.ts
  packages/profile-sync-controller/src/controllers/user-storage/network-syncing/sync-all.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/network-syncing/sync-all.ts
  packages/profile-sync-controller/src/controllers/user-storage/network-syncing/sync-mutations.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/network-syncing/sync-mutations.ts
  packages/profile-sync-controller/src/controllers/user-storage/network-syncing/types.ts
  packages/profile-sync-controller/src/controllers/user-storage/utils.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/utils.ts
Labels: team-notifications

#4658 fix: transaction controller startup
  packages/transaction-controller/jest.config.js
  packages/transaction-controller/src/TransactionController.test.ts
  packages/transaction-controller/src/TransactionController.ts
  packages/transaction-controller/src/TransactionControllerIntegration.test.ts
  packages/transaction-controller/src/helpers/PendingTransactionTracker.test.ts
  packages/transaction-controller/src/helpers/PendingTransactionTracker.ts
Labels: team-confirmations

#4703 test: remove unused test
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.test.ts
Labels: team-notifications

#4708 refactor: profile-sync-sdk move snap methods to snap auth class
  packages/profile-sync-controller/src/sdk/authentication-jwt-bearer/flow-srp.ts
  packages/profile-sync-controller/src/sdk/authentication.ts
  packages/profile-sync-controller/src/sdk/utils/messaging-signing-snap-requests.test.ts
  packages/profile-sync-controller/src/sdk/utils/messaging-signing-snap-requests.ts
Labels: team-notifications

#4697 Paralellization of add detected tokens instead of sequencial
  packages/assets-controllers/src/TokenDetectionController.ts
Labels: needs-dev-review

#4709 fix: update subpath exports to use new .d.cts definition files.
  packages/notification-services-controller/notification-services/mocks/package.json
  packages/notification-services-controller/notification-services/package.json
  packages/notification-services-controller/notification-services/ui/package.json
  packages/notification-services-controller/package.json
  packages/notification-services-controller/push-services/mocks/package.json
  packages/notification-services-controller/push-services/package.json
  packages/profile-sync-controller/auth/mocks/package.json
  packages/profile-sync-controller/auth/package.json
  packages/profile-sync-controller/package.json
  packages/profile-sync-controller/sdk/package.json
  packages/profile-sync-controller/user-storage/mocks/package.json
  packages/profile-sync-controller/user-storage/package.json
Labels: team-notifications

#4710 Release 203.0.0
  package.json
  packages/notification-services-controller/CHANGELOG.md
  packages/notification-services-controller/package.json
  packages/profile-sync-controller/CHANGELOG.md
  packages/profile-sync-controller/package.json
  yarn.lock
Labels: team-notifications

#4711 fix: update profile-sync notification settings path hash
  packages/notification-services-controller/src/NotificationServicesController/NotificationServicesController.ts
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/__fixtures__/mockResponses.ts
  packages/profile-sync-controller/src/controllers/user-storage/__fixtures__/mockServices.ts
  packages/profile-sync-controller/src/controllers/user-storage/schema.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/schema.ts
  packages/profile-sync-controller/src/controllers/user-storage/services.test.ts
  packages/profile-sync-controller/src/sdk/__fixtures__/mock-userstorage.ts
  packages/profile-sync-controller/src/sdk/user-storage.test.ts
Labels: team-notifications

#4712 Release 204.0.0
  package.json
  packages/notification-services-controller/CHANGELOG.md
  packages/notification-services-controller/package.json
  packages/profile-sync-controller/CHANGELOG.md
  packages/profile-sync-controller/package.json
  yarn.lock
Labels: team-notifications

#4706 feat: align transaction controller with mobile patch
  packages/transaction-controller/jest.config.js
  packages/transaction-controller/src/TransactionController.test.ts
  packages/transaction-controller/src/TransactionController.ts
  packages/transaction-controller/src/helpers/PendingTransactionTracker.test.ts
  packages/transaction-controller/src/helpers/PendingTransactionTracker.ts
  packages/transaction-controller/src/index.ts
  packages/transaction-controller/src/types.ts
Labels: team-confirmations

#4716 chore: add client pull requests to pull request template
  .github/pull_request_template.md
Labels: team-confirmations

#4717 refactor: move and organize shared profile sync dependencies
  packages/profile-sync-controller/src/controllers/authentication/services.ts
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
  packages/profile-sync-controller/src/controllers/user-storage/__fixtures__/mockResponses.ts
  packages/profile-sync-controller/src/controllers/user-storage/__fixtures__/mockServices.ts
  packages/profile-sync-controller/src/controllers/user-storage/__fixtures__/mockStorage.ts
  packages/profile-sync-controller/src/controllers/user-storage/index.ts
  packages/profile-sync-controller/src/controllers/user-storage/services.ts
  packages/profile-sync-controller/src/sdk/__fixtures__/mock-auth.ts
  packages/profile-sync-controller/src/sdk/__fixtures__/mock-userstorage.ts
  packages/profile-sync-controller/src/sdk/__fixtures__/test-utils.ts
  packages/profile-sync-controller/src/sdk/authentication-jwt-bearer/services.ts
  packages/profile-sync-controller/src/sdk/authentication-jwt-bearer/types.ts
  packages/profile-sync-controller/src/sdk/authentication.test.ts
  packages/profile-sync-controller/src/sdk/authentication.ts
  packages/profile-sync-controller/src/sdk/encryption.ts
  packages/profile-sync-controller/src/sdk/index.ts
  packages/profile-sync-controller/src/sdk/user-storage.test.ts
  packages/profile-sync-controller/src/sdk/user-storage.ts
  packages/profile-sync-controller/src/shared/encryption/cache.ts
  packages/profile-sync-controller/src/shared/encryption/encryption.test.ts
  packages/profile-sync-controller/src/shared/encryption/encryption.ts
  packages/profile-sync-controller/src/shared/encryption/index.ts
  packages/profile-sync-controller/src/shared/encryption/utils.ts
  packages/profile-sync-controller/src/shared/env.test.ts
  packages/profile-sync-controller/src/shared/env.ts
  packages/profile-sync-controller/src/shared/storage-schema.test.ts
  packages/profile-sync-controller/src/shared/storage-schema.ts
  packages/profile-sync-controller/src/shared/types/encryption.ts
Labels: team-notifications

#4720 feat: update UI export from MATIC to POL
  packages/notification-services-controller/src/NotificationServicesController/ui/constants.ts
Labels: team-notifications

#4721 fix: profile-sync-controller mobile compilation issues
  packages/profile-sync-controller/src/controllers/user-storage/__fixtures__/mockResponses.ts
Labels: team-notifications

#4722 Release 205.0.0
  package.json
  packages/notification-services-controller/CHANGELOG.md
  packages/notification-services-controller/package.json
  packages/profile-sync-controller/CHANGELOG.md
  packages/profile-sync-controller/package.json
  yarn.lock
Labels: team-notifications

#4713 chore: update 'eth-{simple,hd,snap}-keyring' + 'keyring-api'
  packages/accounts-controller/package.json
  packages/assets-controllers/package.json
  packages/chain-controller/package.json
  packages/keyring-controller/package.json
  packages/profile-sync-controller/package.json
  packages/transaction-controller/package.json
  yarn.lock
Labels: team-accounts

#4730 Release 207.0.0
  package.json
  packages/notification-services-controller/package.json
  packages/profile-sync-controller/CHANGELOG.md
  packages/profile-sync-controller/package.json
  yarn.lock
Labels: team-notifications

#4735 fix(NOTIFY-1166): only fire callback when account name has changed
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
Labels: team-notifications

#4736 Release 209.0.0
  package.json
  packages/notification-services-controller/package.json
  packages/profile-sync-controller/CHANGELOG.md
  packages/profile-sync-controller/package.json
  yarn.lock
Labels: team-notifications

#4737 fix: remove gasPrice property from linea_estimateGas request
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/src/gas-flows/LineaGasFeeFlow.ts
Labels: team-confirmations

#4738 feat: add reset notifications flow
  packages/notification-services-controller/src/NotificationServicesController/NotificationServicesController.test.ts
  packages/notification-services-controller/src/NotificationServicesController/NotificationServicesController.ts
Labels: team-notifications
