Repository MetaMask/core, pull requests merged in 2024-02, with the labels that each got.

#3881 Relax peer dependency constraints
  constraints.pro
Labels: team-shared-libraries

#3775 [token-detection-controller] Consolidate with `DetectTokensController` from extension
  packages/assets-controllers/CHANGELOG.md
  packages/assets-controllers/jest.config.js
  packages/assets-controllers/package.json
  packages/assets-controllers/src/TokenDetectionController.test.ts
  packages/assets-controllers/src/TokenDetectionController.ts
  packages/assets-controllers/tsconfig.build.json
  packages/assets-controllers/tsconfig.json
  yarn.lock
Labels: team-shared-libraries

#3690 [assets-controllers] Upgrade `TokensController` to fully utilize controller-messenger pattern
  packages/assets-controllers/CHANGELOG.md
  packages/assets-controllers/jest.config.js
  packages/assets-controllers/src/TokenBalancesController.test.ts
  packages/assets-controllers/src/TokenBalancesController.ts
  packages/assets-controllers/src/TokenDetectionController.test.ts
  packages/assets-controllers/src/TokenDetectionController.ts
  packages/assets-controllers/src/TokensController.test.ts
  packages/assets-controllers/src/TokensController.ts
  packages/assets-controllers/src/index.ts
Labels: team-shared-libraries

#3867 [token-detection-controller] Add tests for API changes from merge with `DetectTokensController`
  packages/assets-controllers/jest.config.js
  packages/assets-controllers/src/TokenDetectionController.test.ts
Labels: team-shared-libraries

#3800 Check pending txs before submitting cancel
  packages/transaction-controller/src/TransactionController.test.ts
  packages/transaction-controller/src/TransactionController.ts
  packages/transaction-controller/src/helpers/PendingTransactionTracker.test.ts
  packages/transaction-controller/src/helpers/PendingTransactionTracker.ts
Labels: team-confirmations-system

#3899 fix: add wildcard for custody keyring
  packages/accounts-controller/src/AccountsController.test.ts
  packages/accounts-controller/src/utils.ts
  packages/keyring-controller/src/KeyringController.test.ts
  packages/keyring-controller/src/KeyringController.ts
Labels: team-accounts

#3913 Support updated Linea gas fee estimation
  packages/transaction-controller/jest.config.js
  packages/transaction-controller/src/TransactionController.test.ts
  packages/transaction-controller/src/TransactionController.ts
  packages/transaction-controller/src/gas-flows/DefaultGasFeeFlow.test.ts
  packages/transaction-controller/src/gas-flows/DefaultGasFeeFlow.ts
  packages/transaction-controller/src/gas-flows/LineaGasFeeFlow.test.ts
  packages/transaction-controller/src/gas-flows/LineaGasFeeFlow.ts
  packages/transaction-controller/src/helpers/GasFeePoller.test.ts
  packages/transaction-controller/src/helpers/GasFeePoller.ts
  packages/transaction-controller/src/index.ts
  packages/transaction-controller/src/types.ts
  packages/transaction-controller/src/utils/gas-fees.test.ts
  packages/transaction-controller/src/utils/gas-fees.ts
  packages/transaction-controller/src/utils/gas-flow.test.ts
  packages/transaction-controller/src/utils/gas-flow.ts
Labels: team-confirmations-system

#3904 [composable-controller] Better typing for state, messenger, strict type checks for inputs, remove `#controllers` field
  packages/composable-controller/CHANGELOG.md
  packages/composable-controller/package.json
  packages/composable-controller/src/ComposableController.test.ts
  packages/composable-controller/src/ComposableController.ts
  packages/composable-controller/src/index.ts
  packages/composable-controller/tsconfig.json
  yarn.lock
Labels: team-shared-libraries

#3946 fix(preferences-controller): skip sync when locking
  packages/preferences-controller/jest.config.js
  packages/preferences-controller/src/PreferencesController.test.ts
  packages/preferences-controller/src/PreferencesController.ts
Labels: team-shared-libraries

#3853 [keyring-controller] Remove reliance upon the `PreferencesController`
  packages/keyring-controller/CHANGELOG.md
  packages/keyring-controller/jest.config.js
  packages/keyring-controller/src/KeyringController.test.ts
  packages/keyring-controller/src/KeyringController.ts
Labels: team-shared-libraries

#3937 Refactor PermissionLogController tests
  packages/permission-log-controller/src/PermissionLogController.ts
  packages/permission-log-controller/tests/PermissionLogController.test.ts
  packages/permission-log-controller/tests/helpers.ts
Labels: team-shared-libraries

#3950 [transaction-controller] Rename test directory to tests
  packages/transaction-controller/src/TransactionControllerIntegration.test.ts
  packages/transaction-controller/src/helpers/EtherscanRemoteTransactionSource.test.ts
  packages/transaction-controller/tests/EtherscanMocks.ts
  packages/transaction-controller/tests/JsonRpcRequestMocks.ts
Labels: team-shared-libraries

#3953 Update eslint ignore patterns
  .eslintrc.js
Labels: team-shared-libraries

#3978 Release 120.0.0
  package.json
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/package.json
  packages/user-operation-controller/package.json
  yarn.lock
Labels: team-confirmations-system

#3959 [base-controller] Fix `any` usage in `BaseControllerV1`
  packages/base-controller/src/BaseControllerV1.ts
Labels: team-shared-libraries

#3923 [token-detection-controller] Apply recent `DetectTokensController` updates
  packages/assets-controllers/CHANGELOG.md
  packages/assets-controllers/jest.config.js
  packages/assets-controllers/src/TokenDetectionController.test.ts
  packages/assets-controllers/src/TokenDetectionController.ts
Labels: team-shared-libraries

#3994 Release/121.0.0
  package.json
  packages/permission-log-controller/CHANGELOG.md
  packages/permission-log-controller/package.json
Labels: team-shared-libraries
