Repository MetaMask/core, pull requests merged in 2024-08, with the labels that each got.

#4576 Bump `typescript` from `~5.0.4` to `~5.1.6`
  package.json
  packages/accounts-controller/package.json
  packages/address-book-controller/package.json
  packages/announcement-controller/package.json
  packages/approval-controller/package.json
  packages/assets-controllers/package.json
  packages/base-controller/package.json
  packages/build-utils/package.json
  packages/chain-controller/package.json
  packages/composable-controller/package.json
  packages/controller-utils/package.json
  packages/ens-controller/package.json
  packages/eth-json-rpc-provider/package.json
  packages/gas-fee-controller/package.json
  packages/json-rpc-engine/package.json
  packages/json-rpc-middleware-stream/package.json
  packages/keyring-controller/package.json
  packages/logging-controller/package.json
  packages/message-manager/package.json
  packages/name-controller/package.json
  packages/network-controller/package.json
  packages/notification-controller/package.json
  packages/notification-services-controller/package.json
  packages/permission-controller/package.json
  packages/permission-log-controller/package.json
  packages/phishing-controller/package.json
  packages/polling-controller/package.json
  packages/preferences-controller/package.json
  packages/profile-sync-controller/package.json
  packages/queued-request-controller/package.json
  packages/rate-limit-controller/package.json
  packages/rate-limit-controller/src/RateLimitController.ts
  packages/selected-network-controller/package.json
  packages/signature-controller/package.json
  packages/transaction-controller/package.json
  packages/user-operation-controller/package.json
  scripts/create-package/package-template/package.json
  yarn.lock
Labels: team-wallet-framework

#4592 fix: profile-sync-controller - make fixture constants lazy
  packages/notification-services-controller/src/NotificationServicesController/NotificationServicesController.ts
  packages/profile-sync-controller/src/controllers/user-storage/__fixtures__/mockResponses.ts
  packages/profile-sync-controller/src/controllers/user-storage/__fixtures__/mockStorage.ts
  packages/profile-sync-controller/src/controllers/user-storage/services.test.ts
Labels: team-notifications

#4597 Initialize Release 182.0.0
  package.json
  packages/notification-services-controller/CHANGELOG.md
  packages/notification-services-controller/package.json
  packages/profile-sync-controller/CHANGELOG.md
  packages/profile-sync-controller/package.json
  yarn.lock
Labels: team-notifications

#4591 test: fix transaction controller integration tests with nonce tracker 6
  packages/transaction-controller/package.json
  packages/transaction-controller/src/TransactionController.ts
  packages/transaction-controller/src/TransactionControllerIntegration.test.ts
  yarn.lock
Labels: team-confirmations

#4600 Release/182.0.0
  package.json
  packages/notification-services-controller/CHANGELOG.md
  packages/notification-services-controller/package.json
  packages/profile-sync-controller/CHANGELOG.md
  packages/profile-sync-controller/package.json
  yarn.lock
Labels: team-notifications

#4596 fix(TXL-207): fixes gaps in transaction validation and async error logging
  packages/transaction-controller/jest.config.js
  packages/transaction-controller/src/TransactionController.ts
  packages/transaction-controller/src/utils/validation.test.ts
  packages/transaction-controller/src/utils/validation.ts
Labels: team-transactions

#4584 Bump `typescript` from `~5.1.6` to `~5.2.2`
  package.json
  packages/accounts-controller/package.json
  packages/address-book-controller/package.json
  packages/announcement-controller/package.json
  packages/approval-controller/package.json
  packages/assets-controllers/package.json
  packages/base-controller/package.json
  packages/build-utils/package.json
  packages/chain-controller/package.json
  packages/composable-controller/package.json
  packages/controller-utils/package.json
  packages/ens-controller/package.json
  packages/eth-json-rpc-provider/package.json
  packages/gas-fee-controller/package.json
  packages/json-rpc-engine/package.json
  packages/json-rpc-middleware-stream/package.json
  packages/keyring-controller/package.json
  packages/logging-controller/package.json
  packages/message-manager/package.json
  packages/name-controller/package.json
  packages/network-controller/package.json
  packages/notification-controller/package.json
  packages/notification-services-controller/package.json
  packages/permission-controller/package.json
  packages/permission-log-controller/package.json
  packages/phishing-controller/package.json
  packages/polling-controller/package.json
  packages/preferences-controller/package.json
  packages/profile-sync-controller/package.json
  packages/queued-request-controller/package.json
  packages/rate-limit-controller/package.json
  packages/selected-network-controller/package.json
  packages/signature-controller/package.json
  packages/transaction-controller/package.json
  packages/user-operation-controller/package.json
  scripts/create-package/package-template/package.json
  yarn.lock
Labels: team-wallet-framework

#4610 fix: Return error as sent from the UI instead of throwing a new one
  packages/signature-controller/package.json
  packages/signature-controller/src/SignatureController.test.ts
  packages/signature-controller/src/SignatureController.ts
  yarn.lock
Labels: team-confirmations

#4575 feat: add initial tracing to transaction controller
  packages/transaction-controller/src/TransactionController.ts
  packages/transaction-controller/src/types.ts
Labels: team-confirmations, team-tiger

#4619 Release 186.0.0
  package.json
  packages/signature-controller/CHANGELOG.md
  packages/signature-controller/package.json
Labels: team-confirmations

#4621 feat: Remove the Phishfort list from the PhishingController
  packages/phishing-controller/src/PhishingController.test.ts
  packages/phishing-controller/src/PhishingController.ts
  packages/phishing-controller/src/utils.test.ts
Labels: team-product-safety

#4623 fix: handle undefined selectedAccount in updateAccounts
  packages/accounts-controller/src/AccountsController.test.ts
  packages/accounts-controller/src/AccountsController.ts
Labels: team-accounts

#4467 [composable-controller] Fix incorrect behavior and improve type-level safeguards
  packages/composable-controller/package.json
  packages/composable-controller/src/ComposableController.test.ts
  packages/composable-controller/src/ComposableController.ts
  yarn.lock
Labels: team-wallet-framework

#4625 Release 188.0.0
  package.json
  packages/accounts-controller/package.json
  packages/address-book-controller/package.json
  packages/announcement-controller/package.json
  packages/approval-controller/package.json
  packages/assets-controllers/package.json
  packages/base-controller/CHANGELOG.md
  packages/base-controller/package.json
  packages/chain-controller/package.json
  packages/composable-controller/CHANGELOG.md
  packages/composable-controller/package.json
  packages/ens-controller/package.json
  packages/gas-fee-controller/package.json
  packages/keyring-controller/package.json
  packages/logging-controller/package.json
  packages/message-manager/package.json
  packages/name-controller/package.json
  packages/network-controller/package.json
  packages/notification-controller/package.json
  packages/notification-services-controller/package.json
  packages/permission-controller/package.json
  packages/permission-log-controller/package.json
  packages/phishing-controller/package.json
  packages/polling-controller/package.json
  packages/preferences-controller/package.json
  packages/profile-sync-controller/package.json
  packages/queued-request-controller/package.json
  packages/rate-limit-controller/package.json
  packages/selected-network-controller/package.json
  packages/signature-controller/package.json
  packages/transaction-controller/package.json
  packages/user-operation-controller/package.json
  yarn.lock
Labels: team-wallet-framework

#4622 chore: Add export of MarketDataDetails type
  packages/assets-controllers/src/TokenRatesController.ts
  packages/assets-controllers/src/index.ts
Labels: needs-dev-review

#4628 Release/189.0.0
  package.json
  packages/accounts-controller/CHANGELOG.md
  packages/accounts-controller/package.json
  packages/assets-controllers/package.json
  packages/transaction-controller/package.json
  yarn.lock
Labels: team-accounts

#4617 refactor: remove retry validation
  packages/transaction-controller/src/TransactionController.test.ts
  packages/transaction-controller/src/TransactionController.ts
  packages/transaction-controller/src/index.ts
  packages/transaction-controller/src/types.ts
  packages/transaction-controller/src/utils/retry.test.ts
  packages/transaction-controller/src/utils/retry.ts
  packages/transaction-controller/src/utils/utils.test.ts
  packages/transaction-controller/src/utils/utils.ts
Labels: team-confirmations

#4581 Move composable-controller utility types to base-controller
  packages/base-controller/jest.config.js
  packages/base-controller/package.json
  packages/base-controller/src/BaseControllerV1.test.ts
  packages/base-controller/src/BaseControllerV1.ts
  packages/base-controller/src/BaseControllerV2.test.ts
  packages/base-controller/src/BaseControllerV2.ts
  packages/base-controller/src/RestrictedControllerMessenger.ts
  packages/base-controller/src/index.ts
  packages/base-controller/tsconfig.json
  packages/composable-controller/package.json
  packages/composable-controller/src/ComposableController.ts
  packages/composable-controller/src/index.ts
  yarn.lock
Labels: team-wallet-framework

#4631 Release 190.0.0
  package.json
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/package.json
  packages/user-operation-controller/package.json
  yarn.lock
Labels: team-confirmations

#4632 Set yarn resolutions for dependencies affected by dependabot security alerts
  package.json
  yarn.lock
Labels: team-wallet-framework

#4637 Replace yarn resolutions entry for `axios` security patch with version bump
  package.json
  packages/notification-services-controller/package.json
  yarn.lock
Labels: team-wallet-framework

#4633 Fix controllers with missing or incorrect messenger action/event types
  packages/logging-controller/src/LoggingController.ts
  packages/notification-services-controller/src/NotificationServicesController/NotificationServicesController.ts
  packages/phishing-controller/src/PhishingController.ts
  packages/profile-sync-controller/src/controllers/authentication/AuthenticationController.ts
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
Labels: team-wallet-framework

#4641 fix(notification-services-push-controller): Add missing messenger action/events
  packages/notification-services-controller/src/NotificationServicesPushController/NotificationServicesPushController.ts
  packages/notification-services-controller/src/index.ts
Labels: team-wallet-framework

#4644 feat: add allowlist to c2 domain detection
  packages/phishing-controller/src/PhishingController.ts
  packages/phishing-controller/src/PhishingDetector.test.ts
  packages/phishing-controller/src/PhishingDetector.ts
Labels: team-product-safety

#4611 feat: update package constraints to allow multiple files.
  yarn.config.cjs
Labels: team-wallet-framework

#4645 fix: use hostname to check against allowlist
  packages/phishing-controller/src/PhishingController.test.ts
  packages/phishing-controller/src/PhishingController.ts
  packages/phishing-controller/src/utils.test.ts
  packages/phishing-controller/src/utils.ts
Labels: team-product-safety

#4643 Release 193.0.0
  package.json
  packages/accounts-controller/package.json
  packages/address-book-controller/package.json
  packages/announcement-controller/package.json
  packages/approval-controller/CHANGELOG.md
  packages/approval-controller/package.json
  packages/assets-controllers/package.json
  packages/base-controller/CHANGELOG.md
  packages/base-controller/package.json
  packages/chain-controller/package.json
  packages/composable-controller/CHANGELOG.md
  packages/composable-controller/package.json
  packages/ens-controller/package.json
  packages/gas-fee-controller/package.json
  packages/keyring-controller/CHANGELOG.md
  packages/keyring-controller/package.json
  packages/logging-controller/CHANGELOG.md
  packages/logging-controller/package.json
  packages/message-manager/CHANGELOG.md
  packages/message-manager/package.json
  packages/name-controller/package.json
  packages/network-controller/package.json
  packages/notification-controller/package.json
  packages/notification-services-controller/package.json
  packages/permission-controller/package.json
  packages/permission-log-controller/package.json
  packages/phishing-controller/CHANGELOG.md
  packages/phishing-controller/package.json
  packages/polling-controller/package.json
  packages/preferences-controller/package.json
  packages/profile-sync-controller/package.json
  packages/queued-request-controller/package.json
  packages/rate-limit-controller/package.json
  packages/selected-network-controller/package.json
  packages/signature-controller/CHANGELOG.md
  packages/signature-controller/package.json
  packages/transaction-controller/package.json
  packages/user-operation-controller/package.json
  yarn.lock
Labels: team-wallet-framework
