Repository MetaMask/core, pull requests merged in 2024-11, with the labels that each got.

#4854 fix: Add validation to ensure gas fields are valid hexadecimal
  packages/transaction-controller/src/TransactionController.test.ts
  packages/transaction-controller/src/utils/validation.test.ts
  packages/transaction-controller/src/utils/validation.ts
Labels: team-confirmations

#4845 chore: remove `addNewAccountWithoutUpdate`
  packages/keyring-controller/CHANGELOG.md
  packages/keyring-controller/jest.config.js
  packages/keyring-controller/src/KeyringController.test.ts
  packages/keyring-controller/src/KeyringController.ts
Labels: team-wallet-framework

#4885 feat: enable smart transactions by default for new users
  packages/preferences-controller/src/PreferencesController.test.ts
  packages/preferences-controller/src/PreferencesController.ts
Labels: team-transactions

#4855 feat: integrating signature decoding api
  packages/signature-controller/src/SignatureController.test.ts
  packages/signature-controller/src/SignatureController.ts
  packages/signature-controller/src/constants.ts
  packages/signature-controller/src/types.ts
  packages/signature-controller/src/utils/decoding-api.test.ts
  packages/signature-controller/src/utils/decoding-api.ts
  packages/signature-controller/src/utils/normalize.test.ts
  packages/signature-controller/src/utils/normalize.ts
Labels: team-confirmations

#4901 feat: prevent parallel account syncs
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
Labels: team-notifications

#4935 chore: update CODEOWNERS to reflect co-ownership of profile-sync-controller
  .github/CODEOWNERS
Labels: team-notifications, team-identity

#4907 feat(NOTIFY-1146): use better type system for user storage
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
  packages/profile-sync-controller/src/controllers/user-storage/__fixtures__/mockResponses.ts
  packages/profile-sync-controller/src/controllers/user-storage/__fixtures__/mockServices.ts
  packages/profile-sync-controller/src/controllers/user-storage/index.ts
  packages/profile-sync-controller/src/controllers/user-storage/network-syncing/services.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/network-syncing/services.ts
  packages/profile-sync-controller/src/controllers/user-storage/network-syncing/sync-mutations.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/services.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/services.ts
  packages/profile-sync-controller/src/sdk/__fixtures__/mock-userstorage.ts
  packages/profile-sync-controller/src/sdk/index.ts
  packages/profile-sync-controller/src/sdk/user-storage.test.ts
  packages/profile-sync-controller/src/sdk/user-storage.ts
  packages/profile-sync-controller/src/shared/storage-schema.test.ts
  packages/profile-sync-controller/src/shared/storage-schema.ts
Labels: team-notifications, team-identity

#4942 Release 249.0.0
  package.json
  packages/notification-services-controller/package.json
  packages/profile-sync-controller/CHANGELOG.md
  packages/profile-sync-controller/package.json
  yarn.lock
Labels: team-identity

#4944 feat: add account sync analytics & add state helpers
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
Labels: team-identity

#4947 Release 251.0.0
  package.json
  packages/notification-services-controller/package.json
  packages/profile-sync-controller/CHANGELOG.md
  packages/profile-sync-controller/package.json
  yarn.lock
Labels: team-identity

#4953 chore: update transaction polling variables
  packages/transaction-controller/src/helpers/TransactionPoller.ts
Labels: team-confirmations

#4955 chore: remove keyring-api dependency from transaction controller
  packages/transaction-controller/package.json
  packages/transaction-controller/src/TransactionController.test.ts
  packages/transaction-controller/src/TransactionControllerIntegration.test.ts
  packages/transaction-controller/src/types.ts
  yarn.lock
Labels: team-confirmations

#4959 chore: downgrade `snaps-controllers` peer dependency from `^9.10.0` to `^9.7.0`
  packages/accounts-controller/package.json
  yarn.lock
Labels: team-accounts

#4920 refactor: remove global network from transaction controller
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/jest.config.js
  packages/transaction-controller/src/TransactionController.test.ts
  packages/transaction-controller/src/TransactionController.ts
  packages/transaction-controller/src/TransactionControllerIntegration.test.ts
  packages/transaction-controller/src/gas-flows/DefaultGasFeeFlow.test.ts
  packages/transaction-controller/src/gas-flows/LineaGasFeeFlow.test.ts
  packages/transaction-controller/src/gas-flows/OptimismLayer1GasFeeFlow.test.ts
  packages/transaction-controller/src/gas-flows/OracleLayer1GasFeeFlow.test.ts
  packages/transaction-controller/src/gas-flows/ScrollLayer1GasFeeFlow.test.ts
  packages/transaction-controller/src/helpers/EtherscanRemoteTransactionSource.test.ts
  packages/transaction-controller/src/helpers/EtherscanRemoteTransactionSource.ts
  packages/transaction-controller/src/helpers/GasFeePoller.test.ts
  packages/transaction-controller/src/helpers/GasFeePoller.ts
  packages/transaction-controller/src/helpers/IncomingTransactionHelper.test.ts
  packages/transaction-controller/src/helpers/IncomingTransactionHelper.ts
  packages/transaction-controller/src/helpers/MethodDataHelper.test.ts
  packages/transaction-controller/src/helpers/MethodDataHelper.ts
  packages/transaction-controller/src/helpers/MultichainTrackingHelper.test.ts
  packages/transaction-controller/src/helpers/MultichainTrackingHelper.ts
  packages/transaction-controller/src/helpers/PendingTransactionTracker.ts
  packages/transaction-controller/src/types.ts
  packages/transaction-controller/src/utils/etherscan.ts
  packages/transaction-controller/src/utils/gas-flow.test.ts
  packages/transaction-controller/src/utils/history.test.ts
  packages/transaction-controller/src/utils/layer1-gas-fee-flow.test.ts
  packages/transaction-controller/src/utils/nonce.test.ts
  packages/transaction-controller/src/utils/resimulate.test.ts
  packages/transaction-controller/tests/EtherscanMocks.ts
  packages/user-operation-controller/src/utils/transaction.ts
Labels: team-confirmations

#4974 Fix peer dependency warnings
  package.json
  packages/accounts-controller/CHANGELOG.md
  packages/accounts-controller/package.json
  packages/assets-controllers/CHANGELOG.md
  packages/assets-controllers/package.json
  packages/chain-controller/CHANGELOG.md
  packages/chain-controller/package.json
  packages/controller-utils/CHANGELOG.md
  packages/controller-utils/package.json
  packages/gas-fee-controller/CHANGELOG.md
  packages/gas-fee-controller/package.json
  packages/json-rpc-engine/package.json
  packages/keyring-controller/CHANGELOG.md
  packages/keyring-controller/package.json
  packages/notification-services-controller/package.json
  packages/profile-sync-controller/CHANGELOG.md
  packages/profile-sync-controller/package.json
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/package.json
  packages/user-operation-controller/CHANGELOG.md
  packages/user-operation-controller/package.json
  yarn.lock
Labels: team-wallet-framework

#4989 chore: user-operation-controller changelog typo
  packages/user-operation-controller/CHANGELOG.md
Labels: team-wallet-framework

#4652 feat: add lastUpdatedAt to NetworkConfiguration
  packages/network-controller/package.json
  packages/network-controller/src/NetworkController.ts
  packages/network-controller/tests/NetworkController.test.ts
  yarn.lock
Labels: team-notifications

#4698 feat: add NetworkController NetworkConfiguration actions and events
  packages/network-controller/src/NetworkController.ts
  packages/network-controller/src/index.ts
  packages/network-controller/tests/NetworkController.test.ts
Labels: team-notifications

#4701 feat: add main network sync controller integration
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
  packages/profile-sync-controller/src/controllers/user-storage/__fixtures__/mockMessenger.ts
  packages/profile-sync-controller/src/controllers/user-storage/network-syncing/__fixtures__/mockNetwork.ts
  packages/profile-sync-controller/src/controllers/user-storage/network-syncing/add-network-utils.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/network-syncing/add-network-utils.ts
  packages/profile-sync-controller/src/controllers/user-storage/network-syncing/controller-integration.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/network-syncing/controller-integration.ts
  packages/profile-sync-controller/src/controllers/user-storage/network-syncing/controller-integration.update-network.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/network-syncing/services.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/network-syncing/services.ts
  packages/profile-sync-controller/src/controllers/user-storage/network-syncing/sync-all.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/network-syncing/sync-all.ts
  packages/profile-sync-controller/src/controllers/user-storage/network-syncing/sync-mutations.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/network-syncing/sync-mutations.ts
  packages/profile-sync-controller/src/controllers/user-storage/network-syncing/types.ts
  packages/profile-sync-controller/src/controllers/user-storage/network-syncing/update-network-utils.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/network-syncing/update-network-utils.ts
  packages/profile-sync-controller/src/controllers/user-storage/services.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/services.ts
Labels: team-notifications

#4910 Demonstrate state as optional in controller guidelines
  docs/writing-controllers.md
Labels: team-wallet-framework
