Repository MetaMask/core, pull requests merged in 2024-07, with the labels that each got.

#4482 fix: add support for tokenURI encoded images
  packages/assets-controllers/src/NftController.test.ts
  packages/assets-controllers/src/NftController.ts
Labels: needs-dev-review, team-assets

#4494 fix: use `listMultichainAccounts` and set `lastSelected` for initial account
  packages/accounts-controller/src/AccountsController.test.ts
  packages/accounts-controller/src/AccountsController.ts
Labels: team-accounts

#4496 feat: add `accountAdded` and `accountRemoved` events
  packages/accounts-controller/src/AccountsController.test.ts
  packages/accounts-controller/src/AccountsController.ts
  packages/accounts-controller/src/index.ts
Labels: team-accounts

#4498 Release/170.0.0
  package.json
  packages/accounts-controller/CHANGELOG.md
  packages/accounts-controller/package.json
  packages/assets-controllers/package.json
  packages/gas-fee-controller/CHANGELOG.md
  packages/gas-fee-controller/package.json
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/package.json
  packages/user-operation-controller/CHANGELOG.md
  packages/user-operation-controller/package.json
  yarn.lock
Labels: team-accounts

#4422 feat: make SafeEventEmitterProvider compatible with eth req libraries
  packages/assets-controllers/src/AssetsContractController.ts
  packages/eth-json-rpc-provider/package.json
  packages/eth-json-rpc-provider/src/provider-from-engine.test.ts
  packages/eth-json-rpc-provider/src/provider-from-middleware.test.ts
  packages/eth-json-rpc-provider/src/safe-event-emitter-provider.test.ts
  packages/eth-json-rpc-provider/src/safe-event-emitter-provider.ts
  tests/fake-provider.ts
  types/ethjs-query.d.ts
  yarn.lock
Labels: team-wallet-framework

#4508 Release/171.0.0
  package.json
  packages/assets-controllers/CHANGELOG.md
  packages/assets-controllers/package.json
  packages/ens-controller/CHANGELOG.md
  packages/ens-controller/package.json
  packages/eth-json-rpc-provider/CHANGELOG.md
  packages/eth-json-rpc-provider/package.json
  packages/gas-fee-controller/CHANGELOG.md
  packages/gas-fee-controller/package.json
  packages/network-controller/CHANGELOG.md
  packages/network-controller/package.json
  packages/polling-controller/CHANGELOG.md
  packages/polling-controller/package.json
  packages/queued-request-controller/CHANGELOG.md
  packages/queued-request-controller/package.json
  packages/selected-network-controller/CHANGELOG.md
  packages/selected-network-controller/package.json
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/package.json
  packages/user-operation-controller/CHANGELOG.md
  packages/user-operation-controller/package.json
  yarn.lock
Labels: team-wallet-framework

#4516 chore(deps): Bump `@metamask/utils` to `^9.0.0`, `@metamask/rpc-errors` to `^6.3.1`
  jest.config.scripts.js
  package.json
  packages/accounts-controller/package.json
  packages/accounts-controller/src/AccountsController.ts
  packages/address-book-controller/package.json
  packages/approval-controller/package.json
  packages/assets-controllers/package.json
  packages/base-controller/package.json
  packages/build-utils/package.json
  packages/chain-controller/package.json
  packages/controller-utils/package.json
  packages/ens-controller/package.json
  packages/eth-json-rpc-provider/package.json
  packages/gas-fee-controller/package.json
  packages/json-rpc-engine/package.json
  packages/json-rpc-middleware-stream/package.json
  packages/keyring-controller/package.json
  packages/message-manager/package.json
  packages/name-controller/package.json
  packages/network-controller/package.json
  packages/notification-controller/package.json
  packages/permission-controller/package.json
  packages/permission-log-controller/package.json
  packages/polling-controller/package.json
  packages/queued-request-controller/package.json
  packages/rate-limit-controller/package.json
  packages/selected-network-controller/package.json
  packages/signature-controller/package.json
  packages/transaction-controller/package.json
  packages/user-operation-controller/package.json
  yarn.lock
Labels: team-wallet-framework

#4517 Release/172.0.0
  package.json
  packages/accounts-controller/package.json
  packages/address-book-controller/package.json
  packages/announcement-controller/package.json
  packages/approval-controller/CHANGELOG.md
  packages/approval-controller/package.json
  packages/assets-controllers/package.json
  packages/base-controller/CHANGELOG.md
  packages/base-controller/package.json
  packages/chain-controller/package.json
  packages/composable-controller/package.json
  packages/controller-utils/CHANGELOG.md
  packages/controller-utils/package.json
  packages/ens-controller/package.json
  packages/eth-json-rpc-provider/package.json
  packages/gas-fee-controller/package.json
  packages/json-rpc-engine/CHANGELOG.md
  packages/json-rpc-engine/package.json
  packages/json-rpc-middleware-stream/package.json
  packages/keyring-controller/package.json
  packages/logging-controller/package.json
  packages/message-manager/package.json
  packages/name-controller/package.json
  packages/network-controller/package.json
  packages/notification-controller/package.json
  packages/notification-services-controller/package.json
  packages/permission-controller/CHANGELOG.md
  packages/permission-controller/package.json
  packages/permission-log-controller/package.json
  packages/phishing-controller/package.json
  packages/polling-controller/package.json
  packages/preferences-controller/package.json
  packages/profile-sync-controller/package.json
  packages/queued-request-controller/package.json
  packages/rate-limit-controller/package.json
  packages/selected-network-controller/package.json
  packages/signature-controller/package.json
  packages/transaction-controller/package.json
  packages/user-operation-controller/package.json
  yarn.lock
Labels: team-wallet-framework

#4519 Release/173.0.0
  package.json
  packages/eth-json-rpc-provider/CHANGELOG.md
  packages/eth-json-rpc-provider/package.json
  packages/json-rpc-middleware-stream/CHANGELOG.md
  packages/json-rpc-middleware-stream/package.json
  packages/network-controller/package.json
  packages/transaction-controller/package.json
  yarn.lock
Labels: team-wallet-framework

#4523 Release/174.0.0
  package.json
  packages/notification-services-controller/package.json
  packages/profile-sync-controller/CHANGELOG.md
  packages/profile-sync-controller/package.json
  yarn.lock
Labels: team-notifications

#4512 fix: parsing of non-string event arguments from simulation
  packages/transaction-controller/jest.config.js
  packages/transaction-controller/src/utils/simulation.test.ts
  packages/transaction-controller/src/utils/simulation.ts
Labels: team-confirmations

#4465 PhishingDetect to support IPFS CID blocking
  packages/phishing-controller/src/PhishingController.test.ts
  packages/phishing-controller/src/PhishingDetector.test.ts
  packages/phishing-controller/src/PhishingDetector.ts
  packages/phishing-controller/src/tests/utils.ts
  packages/phishing-controller/tsconfig.json
Labels: enhancement

#4529 Bump `@metamask/utils` from `^9.0.0` to `^9.1.0`
  package.json
  packages/accounts-controller/package.json
  packages/address-book-controller/package.json
  packages/approval-controller/package.json
  packages/assets-controllers/package.json
  packages/base-controller/package.json
  packages/build-utils/package.json
  packages/chain-controller/package.json
  packages/controller-utils/package.json
  packages/ens-controller/package.json
  packages/eth-json-rpc-provider/package.json
  packages/gas-fee-controller/package.json
  packages/json-rpc-engine/package.json
  packages/json-rpc-middleware-stream/package.json
  packages/keyring-controller/package.json
  packages/message-manager/package.json
  packages/name-controller/package.json
  packages/network-controller/package.json
  packages/notification-controller/package.json
  packages/permission-controller/package.json
  packages/permission-log-controller/package.json
  packages/polling-controller/package.json
  packages/queued-request-controller/package.json
  packages/rate-limit-controller/package.json
  packages/selected-network-controller/package.json
  packages/signature-controller/package.json
  packages/transaction-controller/package.json
  packages/user-operation-controller/package.json
  yarn.lock
Labels: team-wallet-framework

#4530 fix: notification services controller missing env vars
  packages/notification-services-controller/src/NotificationServicesController/__fixtures__/mock-raw-notifications.ts
  packages/notification-services-controller/src/NotificationServicesController/services/feature-announcements.test.ts
  packages/notification-services-controller/src/NotificationServicesController/services/feature-announcements.ts
Labels: team-notifications

#4531 fix: notification services controller - remove retries
  packages/notification-services-controller/src/NotificationServicesController/services/feature-announcements.ts
  packages/notification-services-controller/src/NotificationServicesController/utils/utils.ts
Labels: team-notifications

#4532 chore: profile sync controller - add snap caching
  packages/profile-sync-controller/src/controllers/authentication/AuthenticationController.ts
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
Labels: team-notifications

#4533 fix: profile sync controller - prevent infinite crashes.
  packages/profile-sync-controller/src/controllers/authentication/AuthenticationController.test.ts
  packages/profile-sync-controller/src/controllers/authentication/AuthenticationController.ts
Labels: team-notifications

#4536 refactor: notification services controller - silently handle push notifications
  packages/notification-services-controller/src/NotificationServicesController/NotificationServicesController.ts
Labels: team-notifications

#4542 Release 178.0.0
  package.json
  packages/notification-services-controller/CHANGELOG.md
  packages/notification-services-controller/package.json
  packages/profile-sync-controller/CHANGELOG.md
  packages/profile-sync-controller/package.json
  yarn.lock
Labels: team-notifications

#4397 [assets-contract-controller] Apply messenger pattern and remove inheritance from `BaseControllerV1`
  packages/assets-controllers/jest.config.js
  packages/assets-controllers/src/AssetsContractController.test.ts
  packages/assets-controllers/src/AssetsContractController.ts
  packages/assets-controllers/src/AssetsContractControllerWithNetworkClientId.test.ts
  packages/assets-controllers/src/NftController.test.ts
  packages/assets-controllers/src/NftController.ts
  packages/assets-controllers/src/TokenBalancesController.test.ts
  packages/assets-controllers/src/TokenBalancesController.ts
  packages/assets-controllers/src/index.ts
Labels: team-wallet-framework

#3645 Upgrade to TypeScript v5.0 and set `module{,Resolution}` option to `Node16`
  .depcheckrc.yml
  .yarn/patches/@metamask-rpc-methods-npm-0.38.1-flask.1-081e1eb5b3.patch
  constraints.pro
  package.json
  packages/accounts-controller/CHANGELOG.md
  packages/accounts-controller/package.json
  packages/accounts-controller/src/AccountsController.test.ts
  packages/accounts-controller/src/AccountsController.ts
  packages/address-book-controller/package.json
  packages/announcement-controller/package.json
  packages/approval-controller/package.json
  packages/assets-controllers/package.json
  packages/assets-controllers/src/AccountTrackerController.test.ts
  packages/assets-controllers/src/NftController.test.ts
  packages/assets-controllers/src/NftController.ts
  packages/assets-controllers/src/TokenDetectionController.test.ts
  packages/assets-controllers/src/TokenRatesController.test.ts
  packages/assets-controllers/src/assetsUtil.test.ts
  packages/assets-controllers/src/assetsUtil.ts
  packages/base-controller/package.json
  packages/build-utils/package.json
  packages/chain-controller/CHANGELOG.md
  packages/chain-controller/package.json
  packages/composable-controller/package.json
  packages/controller-utils/package.json
  packages/ens-controller/package.json
  packages/eth-json-rpc-provider/package.json
  packages/gas-fee-controller/package.json
  packages/json-rpc-engine/package.json
  packages/json-rpc-middleware-stream/package.json
  packages/keyring-controller/package.json
  packages/logging-controller/package.json
  packages/message-manager/package.json
  packages/name-controller/package.json
  packages/network-controller/package.json
  packages/network-controller/src/index.ts
  packages/notification-controller/package.json
  packages/notification-services-controller/package.json
  packages/permission-controller/package.json
  packages/permission-log-controller/package.json
  packages/phishing-controller/package.json
  packages/polling-controller/package.json
  packages/preferences-controller/package.json
  packages/profile-sync-controller/CHANGELOG.md
  packages/profile-sync-controller/package.json
  packages/queued-request-controller/package.json
  packages/rate-limit-controller/package.json
  packages/selected-network-controller/package.json
  packages/signature-controller/package.json
  packages/transaction-controller/package.json
  packages/user-operation-controller/package.json
  packages/user-operation-controller/src/utils/validation.ts
  scripts/create-package/package-template/package.json
  tsconfig.packages.json
  yarn.lock
Labels: team-wallet-framework

#4547 Bump `@metamask/snaps-{controllers,sdk,utils}` and remove yarn resolution for `@metamask/providers`
  package.json
  packages/accounts-controller/CHANGELOG.md
  packages/accounts-controller/package.json
  packages/chain-controller/CHANGELOG.md
  packages/chain-controller/package.json
  packages/profile-sync-controller/CHANGELOG.md
  packages/profile-sync-controller/package.json
  yarn.lock
Labels: team-wallet-framework

#4552 feat: notification-services-controller - add shared notification block explorer domains
  packages/notification-services-controller/src/NotificationServicesController/ui/constants.ts
Labels: team-notifications

#4524 feat: add `getNFTContractInfo`
  packages/assets-controllers/src/NftController.test.ts
  packages/assets-controllers/src/NftController.ts
Labels: team-confirmations

#4548 Release 180.0.0
  package.json
  packages/accounts-controller/CHANGELOG.md
  packages/accounts-controller/package.json
  packages/assets-controllers/CHANGELOG.md
  packages/assets-controllers/package.json
  packages/chain-controller/CHANGELOG.md
  packages/chain-controller/package.json
  packages/ens-controller/CHANGELOG.md
  packages/ens-controller/package.json
  packages/eth-json-rpc-provider/CHANGELOG.md
  packages/eth-json-rpc-provider/package.json
  packages/gas-fee-controller/CHANGELOG.md
  packages/gas-fee-controller/package.json
  packages/json-rpc-engine/CHANGELOG.md
  packages/keyring-controller/CHANGELOG.md
  packages/keyring-controller/package.json
  packages/message-manager/CHANGELOG.md
  packages/message-manager/package.json
  packages/network-controller/CHANGELOG.md
  packages/network-controller/package.json
  packages/notification-services-controller/CHANGELOG.md
  packages/notification-services-controller/package.json
  packages/polling-controller/CHANGELOG.md
  packages/polling-controller/package.json
  packages/preferences-controller/CHANGELOG.md
  packages/preferences-controller/package.json
  packages/profile-sync-controller/CHANGELOG.md
  packages/profile-sync-controller/package.json
  packages/queued-request-controller/CHANGELOG.md
  packages/queued-request-controller/package.json
  packages/selected-network-controller/CHANGELOG.md
  packages/selected-network-controller/package.json
  packages/signature-controller/CHANGELOG.md
  packages/signature-controller/package.json
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/package.json
  packages/user-operation-controller/CHANGELOG.md
  packages/user-operation-controller/package.json
  yarn.lock
Labels: team-wallet-framework

#4546 Convert constraints from Prolog to JavaScript
  .eslintrc.js
  constraints.pro
  package.json
  yarn.config.cjs
  yarn.lock
Labels: team-wallet-framework

#4569 feat: add unlock checks for notification and profile sync controllers
  packages/notification-services-controller/src/NotificationServicesController/NotificationServicesController.test.ts
  packages/notification-services-controller/src/NotificationServicesController/NotificationServicesController.ts
  packages/profile-sync-controller/package.json
  packages/profile-sync-controller/src/controllers/authentication/AuthenticationController.test.ts
  packages/profile-sync-controller/src/controllers/authentication/AuthenticationController.ts
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
  packages/profile-sync-controller/tsconfig.build.json
  packages/profile-sync-controller/tsconfig.json
  yarn.lock
Labels: team-notifications

#4568 feat: add new method `updateAccountMetadata`
  packages/accounts-controller/src/AccountsController.test.ts
  packages/accounts-controller/src/AccountsController.ts
Labels: team-notifications

#4573 feat: update notifications controllers from extension fixes.
  packages/notification-services-controller/src/NotificationServicesController/NotificationServicesController.ts
  packages/notification-services-controller/src/NotificationServicesController/services/onchain-notifications.ts
  packages/notification-services-controller/src/NotificationServicesController/types/on-chain-notification/on-chain-notification.ts
  packages/notification-services-controller/src/NotificationServicesPushController/NotificationServicesPushController.ts
  packages/notification-services-controller/src/NotificationServicesPushController/services/push/push-web.ts
  packages/notification-services-controller/src/shared/to-raw-notification.ts
Labels: team-notifications

#4564 Add public `name` property to `AssetsContractController` class
  packages/assets-controllers/src/AssetsContractController.ts
Labels: team-wallet-framework

#4572 fix: fix RatesController.setCryptoCurrencyList invalid internal field
  packages/assets-controllers/src/RatesController/RatesController.test.ts
  packages/assets-controllers/src/RatesController/RatesController.ts
Labels: team-accounts

#4570 fix: fetch correct price for $OMNI
  packages/assets-controllers/src/crypto-compare-service/crypto-compare.ts
Labels: team-assets

#4571 [DO-NOT-MERGE] `ComposableController` sanity check
  packages/composable-controller/src/ComposableController.ts
Labels: DO-NOT-MERGE
