Repository MetaMask/core, pull requests merged in 2024-03, with the labels that each got.

#3990 Normalize transaction data length
  packages/transaction-controller/jest.config.js
  packages/transaction-controller/src/TransactionController.test.ts
  packages/transaction-controller/src/TransactionController.ts
  packages/transaction-controller/src/index.ts
  packages/transaction-controller/src/utils/utils.test.ts
  packages/transaction-controller/src/utils/utils.ts
Labels: team-confirmations-system

#3938 [token-detection-controller] Refactor `detectTokens` method
  packages/assets-controllers/CHANGELOG.md
  packages/assets-controllers/jest.config.js
  packages/assets-controllers/src/TokenDetectionController.test.ts
  packages/assets-controllers/src/TokenDetectionController.ts
Labels: team-shared-libraries

#4002 queued-request-controller: Add missing CL entries for 0.5.0
  packages/queued-request-controller/CHANGELOG.md
Labels: team-shared-libraries

#3949 [base-controller] Consistently apply `Record<string, Json>` constraint on `BaseControllerV2` state objects and types
  packages/assets-controllers/src/TokensController.ts
  packages/base-controller/CHANGELOG.md
  packages/base-controller/src/BaseControllerV2.ts
  packages/base-controller/src/index.ts
  packages/composable-controller/src/ComposableController.ts
  packages/rate-limit-controller/CHANGELOG.md
  packages/rate-limit-controller/src/RateLimitController.ts
Labels: team-shared-libraries, base-controller-breaking-changes

#3827 Migrate TransactionController to BaseController v2
  packages/transaction-controller/jest.config.js
  packages/transaction-controller/package.json
  packages/transaction-controller/src/TransactionController.test.ts
  packages/transaction-controller/src/TransactionController.ts
  packages/transaction-controller/src/TransactionControllerIntegration.test.ts
  packages/transaction-controller/src/helpers/EtherscanRemoteTransactionSource.test.ts
  packages/transaction-controller/src/helpers/GasFeePoller.ts
  packages/transaction-controller/src/helpers/IncomingTransactionHelper.ts
  packages/transaction-controller/src/helpers/PendingTransactionTracker.test.ts
  packages/transaction-controller/src/helpers/PendingTransactionTracker.ts
  packages/transaction-controller/src/index.ts
  packages/transaction-controller/src/types.ts
  packages/transaction-controller/src/utils/history.ts
  packages/transaction-controller/src/utils/swaps.test.ts
  packages/transaction-controller/src/utils/swaps.ts
  packages/transaction-controller/src/utils/utils.ts
  packages/transaction-controller/tsconfig.json
  yarn.lock
Labels: team-shared-libraries

#4012 Correct type of `selector` arg to `subscribe`
  packages/base-controller/src/ControllerMessenger.test.ts
  packages/base-controller/src/ControllerMessenger.ts
  packages/base-controller/src/RestrictedControllerMessenger.ts
Labels: team-shared-libraries, base-controller-breaking-changes

#4011 Initialize controller state as deeply frozen
  packages/base-controller/src/BaseControllerV2.test.ts
  packages/base-controller/src/BaseControllerV2.ts
  packages/name-controller/src/NameController.test.ts
  packages/transaction-controller/src/TransactionController.test.ts
  packages/user-operation-controller/src/UserOperationController.test.ts
Labels: team-shared-libraries, base-controller-breaking-changes

#4013 Fix `getRestricted` method: aligns runtime and type-level handling of omitted or empty inputs
  packages/announcement-controller/src/AnnouncementController.test.ts
  packages/approval-controller/src/ApprovalController.test.ts
  packages/assets-controllers/src/CurrencyRateController.test.ts
  packages/assets-controllers/src/NftController.test.ts
  packages/assets-controllers/src/TokensController.test.ts
  packages/base-controller/CHANGELOG.md
  packages/base-controller/jest.config.js
  packages/base-controller/src/BaseControllerV2.test.ts
  packages/base-controller/src/ControllerMessenger.ts
  packages/base-controller/src/RestrictedControllerMessenger.test.ts
  packages/base-controller/src/RestrictedControllerMessenger.ts
  packages/composable-controller/src/ComposableController.test.ts
  packages/ens-controller/src/EnsController.test.ts
  packages/logging-controller/src/LoggingController.test.ts
  packages/notification-controller/src/NotificationController.test.ts
  packages/permission-controller/src/PermissionController.test.ts
  packages/permission-controller/src/SubjectMetadataController.test.ts
  packages/permission-log-controller/tests/PermissionLogController.test.ts
  packages/phishing-controller/src/PhishingController.test.ts
  packages/rate-limit-controller/src/RateLimitController.test.ts
Labels: team-shared-libraries, base-controller-breaking-changes

#4020 Simulate transactions
  packages/transaction-controller/jest.config.js
  packages/transaction-controller/package.json
  packages/transaction-controller/src/TransactionController.test.ts
  packages/transaction-controller/src/TransactionController.ts
  packages/transaction-controller/src/types.ts
  packages/transaction-controller/src/utils/simulation-api.test.ts
  packages/transaction-controller/src/utils/simulation-api.ts
  packages/transaction-controller/src/utils/simulation.test.ts
  packages/transaction-controller/src/utils/simulation.ts
  yarn.lock
Labels: team-confirmations-system

#3964 [composable-controller] Subscribe to `stateChange` events of V1 controllers with messenger, type fixes
  packages/composable-controller/CHANGELOG.md
  packages/composable-controller/package.json
  packages/composable-controller/src/ComposableController.ts
  packages/composable-controller/src/index.ts
  yarn.lock
Labels: team-shared-libraries, base-controller-breaking-changes

#4031 Narrow `string` allowlists in `RestrictedControllerMessenger` instances
  packages/accounts-controller/src/AccountsController.test.ts
  packages/accounts-controller/src/AccountsController.ts
  packages/accounts-controller/src/index.ts
  packages/approval-controller/src/ApprovalController.ts
  packages/keyring-controller/src/KeyringController.ts
  packages/network-controller/src/NetworkController.ts
  packages/permission-controller/src/PermissionController.ts
  packages/transaction-controller/jest.config.js
  packages/transaction-controller/src/TransactionControllerIntegration.test.ts
Labels: team-shared-libraries, base-controller-breaking-changes

#3963 [rate-limit-controller] Fix and improve typing, remove `any` usage
  packages/rate-limit-controller/CHANGELOG.md
  packages/rate-limit-controller/package.json
  packages/rate-limit-controller/src/RateLimitController.ts
  packages/rate-limit-controller/src/index.ts
  yarn.lock
Labels: team-shared-libraries, base-controller-breaking-changes

#4036 [base-controller] minor type fixes
  packages/base-controller/src/ControllerMessenger.ts
Labels: team-shared-libraries, base-controller-breaking-changes

#4035 [base-controller] Make `allowed{Actions,Events}` required parameters of `getRestricted`
  packages/announcement-controller/src/AnnouncementController.test.ts
  packages/approval-controller/src/ApprovalController.test.ts
  packages/assets-controllers/src/AssetsContractController.test.ts
  packages/assets-controllers/src/CurrencyRateController.test.ts
  packages/assets-controllers/src/NftController.test.ts
  packages/assets-controllers/src/TokensController.test.ts
  packages/base-controller/src/BaseControllerV2.test.ts
  packages/base-controller/src/ControllerMessenger.ts
  packages/base-controller/src/RestrictedControllerMessenger.test.ts
  packages/composable-controller/src/ComposableController.test.ts
  packages/ens-controller/src/EnsController.test.ts
  packages/keyring-controller/src/KeyringController.test.ts
  packages/logging-controller/src/LoggingController.test.ts
  packages/network-controller/tests/NetworkController.test.ts
  packages/notification-controller/src/NotificationController.test.ts
  packages/permission-controller/src/PermissionController.test.ts
  packages/permission-controller/src/SubjectMetadataController.test.ts
  packages/permission-log-controller/tests/PermissionLogController.test.ts
  packages/phishing-controller/src/PhishingController.test.ts
  packages/preferences-controller/src/PreferencesController.test.ts
  packages/queued-request-controller/src/QueuedRequestController.test.ts
  packages/rate-limit-controller/src/RateLimitController.test.ts
  packages/selected-network-controller/tests/SelectedNetworkMiddleware.test.ts
  packages/transaction-controller/src/TransactionController.test.ts
  packages/transaction-controller/src/utils/swaps.test.ts
Labels: bug, team-shared-libraries, base-controller-breaking-changes

#4040 [base-controller] Narrow return types of `get{Anonymized,Persistent}State`
  packages/base-controller/src/BaseControllerV2.ts
Labels: team-shared-libraries, base-controller-breaking-changes

#4034 Ensure preview build versions are semver-parseable
  docs/contributing.md
  scripts/prepare-preview-builds.jq
Labels: team-shared-libraries

#3944 Support `Layer1GasFeeFlows` and add `layer1GasFee` property to `TransactionMeta`
  packages/transaction-controller/jest.config.js
  packages/transaction-controller/src/TransactionController.test.ts
  packages/transaction-controller/src/TransactionController.ts
  packages/transaction-controller/src/constants.ts
  packages/transaction-controller/src/helpers/GasFeePoller.test.ts
  packages/transaction-controller/src/helpers/GasFeePoller.ts
  packages/transaction-controller/src/types.ts
  packages/transaction-controller/src/utils/layer1-gas-fee-flow.test.ts
  packages/transaction-controller/src/utils/layer1-gas-fee-flow.ts
Labels: team-confirmations-system

#4032 fix: include gas fees in user operations when using a paymaster
  packages/user-operation-controller/src/UserOperationController.test.ts
  packages/user-operation-controller/src/UserOperationController.ts
Labels: team-confirmations-system

#4042 [polling-controller] minor type refactors
  packages/polling-controller/src/AbstractPollingController.ts
  packages/polling-controller/src/BlockTrackerPollingController.ts
  packages/polling-controller/src/StaticIntervalPollingController.ts
  packages/polling-controller/src/index.ts
  packages/polling-controller/src/types.ts
Labels: team-shared-libraries

#4067 Include errors in simulation data
  packages/transaction-controller/jest.config.js
  packages/transaction-controller/package.json
  packages/transaction-controller/src/TransactionController.test.ts
  packages/transaction-controller/src/TransactionController.ts
  packages/transaction-controller/src/TransactionControllerIntegration.test.ts
  packages/transaction-controller/src/index.ts
  packages/transaction-controller/src/types.ts
  packages/transaction-controller/src/utils/simulation-api.test.ts
  packages/transaction-controller/src/utils/simulation-api.ts
  packages/transaction-controller/src/utils/simulation.test.ts
  packages/transaction-controller/src/utils/simulation.ts
  yarn.lock
Labels: team-confirmations-system

#4087 Query networks supporting simulation
  packages/transaction-controller/jest.config.js
  packages/transaction-controller/src/utils/simulation-api.test.ts
  packages/transaction-controller/src/utils/simulation-api.ts
Labels: team-confirmations-system

#4084 Bump TypeScript version to `~4.9.5`
  package.json
  packages/accounts-controller/package.json
  packages/address-book-controller/package.json
  packages/announcement-controller/package.json
  packages/approval-controller/package.json
  packages/assets-controllers/package.json
  packages/base-controller/package.json
  packages/build-utils/package.json
  packages/composable-controller/package.json
  packages/controller-utils/package.json
  packages/ens-controller/package.json
  packages/eth-json-rpc-provider/package.json
  packages/gas-fee-controller/package.json
  packages/json-rpc-engine/package.json
  packages/json-rpc-middleware-stream/package.json
  packages/keyring-controller/package.json
  packages/logging-controller/package.json
  packages/message-manager/package.json
  packages/name-controller/package.json
  packages/network-controller/package.json
  packages/notification-controller/package.json
  packages/permission-controller/package.json
  packages/permission-log-controller/package.json
  packages/phishing-controller/package.json
  packages/polling-controller/package.json
  packages/preferences-controller/package.json
  packages/queued-request-controller/package.json
  packages/rate-limit-controller/package.json
  packages/selected-network-controller/package.json
  packages/signature-controller/package.json
  packages/transaction-controller/package.json
  packages/user-operation-controller/package.json
  scripts/create-package/package-template/package.json
  yarn.lock
Labels: team-shared-libraries

#3906 [json-rpc-engine] Fix any types in catch blocks, refactor
  packages/json-rpc-engine/src/JsonRpcEngine.ts
  packages/json-rpc-engine/src/createAsyncMiddleware.ts
Labels: team-shared-libraries

#4041 Fix prototype-polluting assignments
  packages/address-book-controller/src/AddressBookController.test.ts
  packages/address-book-controller/src/AddressBookController.ts
  packages/controller-utils/jest.config.js
  packages/controller-utils/src/index.ts
  packages/controller-utils/src/util.test.ts
  packages/controller-utils/src/util.ts
  packages/ens-controller/src/EnsController.test.ts
  packages/ens-controller/src/EnsController.ts
  packages/name-controller/package.json
  packages/name-controller/src/NameController.test.ts
  packages/name-controller/src/NameController.ts
  yarn.lock
Labels: bug, team-shared-libraries

#4055 feat: implement `OptimismLayer1GasFeeFlow`
  packages/transaction-controller/jest.config.js
  packages/transaction-controller/package.json
  packages/transaction-controller/src/TransactionController.test.ts
  packages/transaction-controller/src/TransactionController.ts
  packages/transaction-controller/src/constants.ts
  packages/transaction-controller/src/gas-flows/OptimismLayer1GasFeeFlow.test.ts
  packages/transaction-controller/src/gas-flows/OptimismLayer1GasFeeFlow.ts
  packages/transaction-controller/src/helpers/GasFeePoller.test.ts
  packages/transaction-controller/src/helpers/GasFeePoller.ts
  packages/transaction-controller/src/helpers/MultichainTrackingHelper.test.ts
  packages/transaction-controller/src/helpers/MultichainTrackingHelper.ts
  packages/transaction-controller/src/types.ts
  packages/transaction-controller/src/utils/layer1-gas-fee-flow.test.ts
  packages/transaction-controller/src/utils/layer1-gas-fee-flow.ts
  yarn.lock
Labels: team-confirmations-system

#4068 fix: use hardcoded Infura gas API urls
  packages/gas-fee-controller/package.json
  packages/gas-fee-controller/src/GasFeeController.test.ts
  packages/gas-fee-controller/src/GasFeeController.ts
  packages/gas-fee-controller/src/determineGasFeeCalculations.test.ts
  packages/gas-fee-controller/src/determineGasFeeCalculations.ts
  packages/gas-fee-controller/src/gas-util.test.ts
  packages/gas-fee-controller/src/gas-util.ts
  yarn.lock
Labels: team-confirmations-system

#4114 Add GasFeeController and TransactionController to release
  packages/gas-fee-controller/CHANGELOG.md
  packages/gas-fee-controller/package.json
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/package.json
  packages/user-operation-controller/package.json
  yarn.lock
Labels: team-confirmations-system

#4113 Support dynamic enablement of automatic resubmit
  packages/transaction-controller/src/TransactionController.test.ts
  packages/transaction-controller/src/TransactionController.ts
  packages/transaction-controller/src/helpers/PendingTransactionTracker.test.ts
  packages/transaction-controller/src/helpers/PendingTransactionTracker.ts
Labels: team-confirmations-system
