Repository MetaMask/core, pull requests merged in 2025-09, with the labels that each got.

#6427 Release/524.0.0
  package.json
  packages/assets-controllers/package.json
  packages/multichain-account-service/CHANGELOG.md
  packages/multichain-account-service/package.json
  yarn.lock
Labels: no-changelog

#6432 fix(accounts-controller): workaround compiler error for recursive type
  packages/accounts-controller/src/AccountsController.ts
  packages/accounts-controller/src/typing.ts
Labels: no-changelog

#6428 feat: Add isGasFeeIncluded property
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/src/TransactionController.test.ts
  packages/transaction-controller/src/TransactionController.ts
  packages/transaction-controller/src/types.ts
  packages/transaction-controller/src/utils/batch.test.ts
  packages/transaction-controller/src/utils/batch.ts
Labels: team-confirmations

#6410 feat: Add 'gasUsed' to transaction metadata
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/src/TransactionController.test.ts
  packages/transaction-controller/src/TransactionController.ts
  packages/transaction-controller/src/types.ts
  packages/transaction-controller/src/utils/balance-changes.test.ts
  packages/transaction-controller/src/utils/balance-changes.ts
Labels: team-confirmations

#6356 feat: SubscriptionController: get pricing
  packages/subscription-controller/CHANGELOG.md
  packages/subscription-controller/src/SubscriptionController.test.ts
  packages/subscription-controller/src/SubscriptionController.ts
  packages/subscription-controller/src/SubscriptionService.test.ts
  packages/subscription-controller/src/SubscriptionService.ts
  packages/subscription-controller/src/index.ts
  packages/subscription-controller/src/types.ts
Labels: team-web3auth, area-shield

#6422 feat: migrate eip-5792 & capabilities middleware handlers into monorepo
  .github/CODEOWNERS
  README.md
  eslint-warning-thresholds.json
  packages/eip-5792-middleware/CHANGELOG.md
  packages/eip-5792-middleware/LICENSE
  packages/eip-5792-middleware/README.md
  packages/eip-5792-middleware/jest.config.js
  packages/eip-5792-middleware/package.json
  packages/eip-5792-middleware/src/constants.ts
  packages/eip-5792-middleware/src/index.test.ts
  packages/eip-5792-middleware/src/index.ts
  packages/eip-5792-middleware/src/methods/getCallsStatus.test.ts
  packages/eip-5792-middleware/src/methods/getCallsStatus.ts
  packages/eip-5792-middleware/src/methods/getCapabilities.test.ts
  packages/eip-5792-middleware/src/methods/getCapabilities.ts
  packages/eip-5792-middleware/src/methods/processSendCalls.test.ts
  packages/eip-5792-middleware/src/methods/processSendCalls.ts
  packages/eip-5792-middleware/src/types.ts
  packages/eip-5792-middleware/src/utils.test.ts
  packages/eip-5792-middleware/src/utils.ts
  packages/eip-5792-middleware/tsconfig.build.json
  packages/eip-5792-middleware/tsconfig.json
  packages/eip-5792-middleware/typedoc.json
  teams.json
  tsconfig.build.json
  yarn.lock
Labels: no-changelog

#6275 Feat/separate revoke renew refresh token
  packages/seedless-onboarding-controller/CHANGELOG.md
  packages/seedless-onboarding-controller/src/SeedlessOnboardingController.test.ts
  packages/seedless-onboarding-controller/src/SeedlessOnboardingController.ts
  packages/seedless-onboarding-controller/src/types.ts
Labels: team-web3auth

#6363 feat: Add metrics for gasless 7702, refactoring
  packages/bridge-controller/CHANGELOG.md
  packages/bridge-controller/src/__snapshots__/bridge-controller.test.ts.snap
  packages/bridge-controller/src/bridge-controller.test.ts
  packages/bridge-controller/src/selectors.test.ts
  packages/bridge-controller/src/types.ts
  packages/bridge-controller/src/utils/fetch.test.ts
  packages/bridge-controller/src/utils/fetch.ts
  packages/bridge-controller/src/utils/metrics/types.ts
  packages/bridge-controller/src/utils/quote.test.ts
  packages/bridge-controller/src/utils/quote.ts
  packages/bridge-controller/src/utils/validators.ts
  packages/bridge-status-controller/CHANGELOG.md
  packages/bridge-status-controller/src/__snapshots__/bridge-status-controller.test.ts.snap
  packages/bridge-status-controller/src/bridge-status-controller.test.ts
  packages/bridge-status-controller/src/bridge-status-controller.ts
  packages/bridge-status-controller/src/types.ts
  packages/bridge-status-controller/src/utils/metrics.test.ts
  packages/bridge-status-controller/src/utils/metrics.ts
  packages/bridge-status-controller/src/utils/transaction.test.ts
  packages/bridge-status-controller/src/utils/transaction.ts
Labels: team-transactions

#6374 feat: SubscriptionController: trigger token refresh
  packages/subscription-controller/CHANGELOG.md
  packages/subscription-controller/src/SubscriptionController.test.ts
  packages/subscription-controller/src/SubscriptionController.ts
Labels: team-web3auth, area-shield

#6456 Feat/shield create subscription crypto
  packages/subscription-controller/CHANGELOG.md
  packages/subscription-controller/package.json
  packages/subscription-controller/src/SubscriptionController.test.ts
  packages/subscription-controller/src/SubscriptionController.ts
  packages/subscription-controller/src/SubscriptionService.test.ts
  packages/subscription-controller/src/SubscriptionService.ts
  packages/subscription-controller/src/constants.test.ts
  packages/subscription-controller/src/constants.ts
  packages/subscription-controller/src/index.ts
  packages/subscription-controller/src/types.ts
  yarn.lock
Labels: team-web3auth, area-shield

#6501 feat: shield-controller: check signature coverage
  packages/shield-controller/CHANGELOG.md
  packages/shield-controller/package.json
  packages/shield-controller/src/ShieldController.test.ts
  packages/shield-controller/src/ShieldController.ts
  packages/shield-controller/src/backend.test.ts
  packages/shield-controller/src/backend.ts
  packages/shield-controller/src/types.ts
  packages/shield-controller/tests/mocks/backend.ts
  packages/shield-controller/tests/mocks/messenger.ts
  packages/shield-controller/tests/utils.ts
  packages/shield-controller/tsconfig.build.json
  packages/shield-controller/tsconfig.json
  yarn.lock
Labels: team-web3auth, area-shield

#6644 Release/562.0.0
  package.json
  packages/account-tree-controller/CHANGELOG.md
  packages/account-tree-controller/package.json
  packages/assets-controllers/package.json
  packages/earn-controller/package.json
  yarn.lock
Labels: no-changelog

#6663 Release/568.0.0
  package.json
  packages/account-tree-controller/CHANGELOG.md
  packages/account-tree-controller/package.json
  packages/assets-controllers/package.json
  packages/earn-controller/package.json
  packages/multichain-account-service/CHANGELOG.md
  packages/multichain-account-service/package.json
  yarn.lock
Labels: no-changelog

#6664 feat: add generic number format
  packages/assets-controllers/src/utils/formatters.test.ts
  packages/assets-controllers/src/utils/formatters.ts
Labels: no-changelog

#6673 Release/570.0.0
  package.json
  packages/account-tree-controller/CHANGELOG.md
  packages/account-tree-controller/package.json
  packages/assets-controllers/package.json
  packages/earn-controller/package.json
  yarn.lock
Labels: no-changelog

#6712 Release/578.0.0
  package.json
  packages/account-tree-controller/CHANGELOG.md
  packages/account-tree-controller/package.json
  packages/assets-controllers/package.json
  packages/earn-controller/package.json
  packages/multichain-account-service/CHANGELOG.md
  packages/multichain-account-service/package.json
  yarn.lock
Labels: no-changelog

#6720 feat: add crypto payment method error
  packages/subscription-controller/CHANGELOG.md
  packages/subscription-controller/src/types.ts
Labels: team-web3auth, area-shield

#6731 Release/584.0.0
  package.json
  packages/account-tree-controller/CHANGELOG.md
  packages/account-tree-controller/package.json
  packages/assets-controllers/package.json
  packages/earn-controller/package.json
  packages/multichain-account-service/CHANGELOG.md
  packages/multichain-account-service/package.json
  yarn.lock
Labels: no-changelog

#6735 fix: getCryptoApproveTransactionParams pricing from state
  packages/subscription-controller/CHANGELOG.md
  packages/subscription-controller/src/SubscriptionController.test.ts
  packages/subscription-controller/src/SubscriptionController.ts
  packages/subscription-controller/src/index.ts
Labels: team-web3auth, area-shield
