Repository MetaMask/core, pull requests merged in 2025-07, with the labels that each got.

#6057 chore: remove user operation tx submission for swaps/bridge
  packages/bridge-controller/CHANGELOG.md
  packages/bridge-status-controller/package.json
  packages/bridge-status-controller/src/__snapshots__/bridge-status-controller.test.ts.snap
  packages/bridge-status-controller/src/bridge-status-controller.test.ts
  packages/bridge-status-controller/src/bridge-status-controller.ts
  packages/bridge-status-controller/tsconfig.build.json
  packages/bridge-status-controller/tsconfig.json
  yarn.lock
Labels: no-changelog

#6061 Release 455.0.0
  package.json
  packages/assets-controllers/CHANGELOG.md
  packages/assets-controllers/package.json
  packages/bridge-controller/CHANGELOG.md
  packages/bridge-controller/package.json
  yarn.lock
Labels: no-changelog

#6068 feat: add `AuthenticationController:getUserProfileMetaMetrics` new method/action
  packages/profile-sync-controller/CHANGELOG.md
  packages/profile-sync-controller/src/controllers/authentication/AuthenticationController.test.ts
  packages/profile-sync-controller/src/controllers/authentication/AuthenticationController.ts
  packages/profile-sync-controller/src/sdk/__fixtures__/auth.ts
  packages/profile-sync-controller/src/sdk/authentication-jwt-bearer/flow-siwe.ts
  packages/profile-sync-controller/src/sdk/authentication-jwt-bearer/flow-srp.ts
  packages/profile-sync-controller/src/sdk/authentication-jwt-bearer/services.ts
  packages/profile-sync-controller/src/sdk/authentication-jwt-bearer/types.ts
  packages/profile-sync-controller/src/sdk/authentication.test.ts
  packages/profile-sync-controller/src/sdk/authentication.ts
  packages/profile-sync-controller/src/sdk/mocks/auth.ts
Labels: team-identity, no-changelog

#6069 Release/459.0.0
  package.json
  packages/address-book-controller/CHANGELOG.md
  packages/address-book-controller/package.json
  packages/assets-controllers/CHANGELOG.md
  packages/assets-controllers/package.json
  packages/bridge-controller/CHANGELOG.md
  packages/bridge-controller/package.json
  packages/bridge-status-controller/CHANGELOG.md
  packages/bridge-status-controller/package.json
  packages/chain-agnostic-permission/CHANGELOG.md
  packages/chain-agnostic-permission/package.json
  packages/controller-utils/CHANGELOG.md
  packages/controller-utils/package.json
  packages/earn-controller/CHANGELOG.md
  packages/earn-controller/package.json
  packages/eip1193-permission-middleware/CHANGELOG.md
  packages/eip1193-permission-middleware/package.json
  packages/ens-controller/CHANGELOG.md
  packages/ens-controller/package.json
  packages/gas-fee-controller/CHANGELOG.md
  packages/gas-fee-controller/package.json
  packages/logging-controller/CHANGELOG.md
  packages/logging-controller/package.json
  packages/message-manager/CHANGELOG.md
  packages/message-manager/package.json
  packages/multichain-api-middleware/CHANGELOG.md
  packages/multichain-api-middleware/package.json
  packages/multichain-network-controller/CHANGELOG.md
  packages/multichain-network-controller/package.json
  packages/name-controller/CHANGELOG.md
  packages/name-controller/package.json
  packages/network-controller/CHANGELOG.md
  packages/network-controller/package.json
  packages/notification-services-controller/CHANGELOG.md
  packages/notification-services-controller/package.json
  packages/permission-controller/CHANGELOG.md
  packages/permission-controller/package.json
  packages/phishing-controller/CHANGELOG.md
  packages/phishing-controller/package.json
  packages/polling-controller/CHANGELOG.md
  packages/polling-controller/package.json
  packages/preferences-controller/CHANGELOG.md
  packages/preferences-controller/package.json
  packages/remote-feature-flag-controller/CHANGELOG.md
  packages/remote-feature-flag-controller/package.json
  packages/sample-controllers/CHANGELOG.md
  packages/sample-controllers/package.json
  packages/signature-controller/CHANGELOG.md
  packages/signature-controller/package.json
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/package.json
  packages/user-operation-controller/CHANGELOG.md
  packages/user-operation-controller/package.json
  yarn.lock
Labels: no-changelog

#6080 fix: remove buffer usage in seedless controller
  packages/seedless-onboarding-controller/src/SeedlessOnboardingController.ts
Labels: no-changelog, team-web3auth

#6079 chore: Remove preference smartAccountOptInForAccounts as it is not going to be used
  packages/preferences-controller/CHANGELOG.md
  packages/preferences-controller/src/PreferencesController.test.ts
  packages/preferences-controller/src/PreferencesController.ts
Labels: team-confirmations

#6083 Release/461.0.0
  package.json
  packages/assets-controllers/package.json
  packages/preferences-controller/CHANGELOG.md
  packages/preferences-controller/package.json
  yarn.lock
Labels: team-confirmations, no-changelog

#6082 feat: add env option for identity controllers
  packages/profile-sync-controller/CHANGELOG.md
  packages/profile-sync-controller/src/controllers/authentication/AuthenticationController.ts
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
Labels: team-identity

#6087 fix: revert PreferenceController changes
  packages/preferences-controller/CHANGELOG.md
  packages/preferences-controller/src/PreferencesController.test.ts
  packages/preferences-controller/src/PreferencesController.ts
Labels: team-confirmations

#6100 Release 463.0.0
  package.json
  packages/notification-services-controller/CHANGELOG.md
  packages/notification-services-controller/package.json
  packages/profile-sync-controller/CHANGELOG.md
  packages/profile-sync-controller/package.json
  yarn.lock
Labels: no-changelog

#6108 chore(changelog-check): update to latest version with optimized `package.json` validation
  .github/workflows/changelog-check.yml
Labels: team-wallet-framework

#6129 chore: Update README diagram
  README.md
Labels: no-changelog

#6130 fix: Update `create-package` template
  scripts/create-package/package-template/package.json
Labels: no-changelog

#6126 fix: Fix `yarn create-package`
  scripts/create-package/cli.ts
Labels: no-changelog

#6131 docs: Add missing step in "new package" docs
  docs/contributing.md
Labels: no-changelog

#6157 Chore/update toprf sdk
  packages/seedless-onboarding-controller/package.json
  packages/seedless-onboarding-controller/src/SeedlessOnboardingController.test.ts
  packages/seedless-onboarding-controller/src/SeedlessOnboardingController.ts
  yarn.lock
Labels: no-changelog

#6172 Optimize changePassword flow
  packages/seedless-onboarding-controller/package.json
  packages/seedless-onboarding-controller/src/SeedlessOnboardingController.test.ts
  packages/seedless-onboarding-controller/src/SeedlessOnboardingController.ts
  packages/seedless-onboarding-controller/src/constants.ts
  yarn.lock
Labels: no-changelog

#6165 feat(multichain-account-service): re-sync multichain account and wallets on account events
  packages/account-tree-controller/package.json
  packages/multichain-account-service/CHANGELOG.md
  packages/multichain-account-service/package.json
  packages/multichain-account-service/src/MultichainAccountService.test.ts
  packages/multichain-account-service/src/MultichainAccountService.ts
  packages/multichain-account-service/src/providers/BaseAccountProvider.test.ts
  packages/multichain-account-service/src/providers/BaseAccountProvider.ts
  packages/multichain-account-service/src/providers/EvmAccountProvider.ts
  packages/multichain-account-service/src/providers/SolAccountProvider.ts
  packages/multichain-account-service/src/tests/accounts.ts
  packages/multichain-account-service/src/tests/messenger.ts
  packages/multichain-account-service/src/types.ts
  packages/multichain-network-controller/src/MultichainNetworkController/MultichainNetworkController.test.ts
  yarn.lock
Labels: team-accounts

#6189 fix(accounts-controller): allow extra-properties in options BIP-44 Snap accounts
  packages/accounts-controller/CHANGELOG.md
  packages/accounts-controller/src/utils.ts
Labels: team-accounts

#6202 fix: make anvil symlink relative
  packages/foundryup/CHANGELOG.md
  packages/foundryup/src/index.ts
Labels: no-changelog

#6211 fix: rename metametrics lineage endpoint and method
  packages/profile-sync-controller/CHANGELOG.md
  packages/profile-sync-controller/src/controllers/authentication/AuthenticationController.test.ts
  packages/profile-sync-controller/src/controllers/authentication/AuthenticationController.ts
  packages/profile-sync-controller/src/sdk/__fixtures__/auth.ts
  packages/profile-sync-controller/src/sdk/authentication-jwt-bearer/flow-siwe.ts
  packages/profile-sync-controller/src/sdk/authentication-jwt-bearer/flow-srp.ts
  packages/profile-sync-controller/src/sdk/authentication-jwt-bearer/services.ts
  packages/profile-sync-controller/src/sdk/authentication-jwt-bearer/types.ts
  packages/profile-sync-controller/src/sdk/authentication.test.ts
  packages/profile-sync-controller/src/sdk/authentication.ts
  packages/profile-sync-controller/src/sdk/mocks/auth.ts
Labels: team-accounts, team-identity

#6214 refactor(account-tree-controller): add type field for each tree node + improve typing overall
  packages/account-tree-controller/CHANGELOG.md
  packages/account-tree-controller/package.json
  packages/account-tree-controller/src/AccountTreeController.test.ts
  packages/account-tree-controller/src/AccountTreeController.ts
  packages/account-tree-controller/src/AccountTreeGroup.ts
  packages/account-tree-controller/src/AccountTreeRule.ts
  packages/account-tree-controller/src/AccountTreeWallet.ts
  packages/account-tree-controller/src/group.ts
  packages/account-tree-controller/src/index.ts
  packages/account-tree-controller/src/rule.ts
  packages/account-tree-controller/src/rules/entropy.ts
  packages/account-tree-controller/src/rules/keyring.ts
  packages/account-tree-controller/src/rules/snap.ts
  packages/account-tree-controller/src/types.ts
  packages/account-tree-controller/src/wallet.ts
  packages/multichain-account-service/CHANGELOG.md
  packages/multichain-account-service/package.json
  yarn.lock
Labels: team-accounts

#6216 refactor(multichain-account-service)!: move `MultichainAccount{Wallet,Group}` implementations
  packages/account-tree-controller/CHANGELOG.md
  packages/account-tree-controller/package.json
  packages/account-tree-controller/src/AccountTreeController.test.ts
  packages/account-tree-controller/src/group.ts
  packages/account-tree-controller/src/rules/entropy.ts
  packages/account-tree-controller/src/wallet.ts
  packages/multichain-account-service/CHANGELOG.md
  packages/multichain-account-service/package.json
  packages/multichain-account-service/src/MultichainAccountGroup.test.ts
  packages/multichain-account-service/src/MultichainAccountGroup.ts
  packages/multichain-account-service/src/MultichainAccountService.test.ts
  packages/multichain-account-service/src/MultichainAccountService.ts
  packages/multichain-account-service/src/MultichainAccountWallet.test.ts
  packages/multichain-account-service/src/MultichainAccountWallet.ts
  packages/multichain-account-service/src/index.ts
  packages/multichain-account-service/src/tests/accounts.ts
  packages/multichain-account-service/src/tests/index.ts
  packages/multichain-account-service/src/tests/providers.ts
  packages/multichain-account-service/src/types.ts
  yarn.lock
Labels: team-accounts

#6219 refactor(multichain-account-service): remove duplicated function `toMultichainAccountWalletId`
  packages/multichain-account-service/CHANGELOG.md
  packages/multichain-account-service/src/MultichainAccountWallet.ts
Labels: team-accounts

#6220 fix(multichain-account-service): add missing exports
  packages/multichain-account-service/CHANGELOG.md
  packages/multichain-account-service/src/index.ts
Labels: team-accounts
