Repository MetaMask/core, pull requests merged in 2025-03, with the labels that each got.

#5380 feat: add updateAtomicBatchData method
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/src/TransactionController.test.ts
  packages/transaction-controller/src/TransactionController.ts
Labels: team-confirmations

#5385 fix: prevent `PhishingController` invalid API requests with -Infinity timestamp
  eslint-warning-thresholds.json
  packages/phishing-controller/CHANGELOG.md
  packages/phishing-controller/src/PhishingController.test.ts
  packages/phishing-controller/src/PhishingController.ts
Labels: team-wallet-framework

#5442 chore: bump `@metamask/create-release-branch` to `^4.1.0`
  package.json
  yarn.lock
Labels: team-wallet-framework

#5016 Fix since-latest-release + --include-head
  scripts/since-latest-release.sh
Labels: team-wallet-framework

#5396 fix: Override lower bound gas when gasLimit is defined
  packages/transaction-controller/src/gas-flows/OracleLayer1GasFeeFlow.test.ts
  packages/transaction-controller/src/gas-flows/OracleLayer1GasFeeFlow.ts
  packages/transaction-controller/src/types.ts
  packages/transaction-controller/src/utils/utils.test.ts
  packages/transaction-controller/src/utils/utils.ts
Labels: team-confirmations

#5461 Release 324.0.0
  package.json
  packages/bridge-controller/package.json
  packages/bridge-status-controller/package.json
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/package.json
  packages/user-operation-controller/package.json
  yarn.lock
Labels: team-confirmations

#5470 feat: add EIP-7702 signature validations
  eslint-warning-thresholds.json
  packages/signature-controller/package.json
  packages/signature-controller/src/SignatureController.test.ts
  packages/signature-controller/src/SignatureController.ts
  packages/signature-controller/src/types.ts
  packages/signature-controller/src/utils/validation.test.ts
  packages/signature-controller/src/utils/validation.ts
  packages/signature-controller/tsconfig.build.json
  packages/signature-controller/tsconfig.json
  yarn.lock
Labels: team-confirmations

#5363 docs: publish example controllers and service as @metamask/sample-controllers
  .github/CODEOWNERS
  README.md
  eslint-warning-thresholds.json
  examples/example-controllers/src/gas-prices-service/abstract-gas-prices-service.ts
  examples/example-controllers/src/index.ts
  jest.config.packages.js
  packages/assets-controllers/src/MultichainAssetsController/MultichainAssetsController.test.ts
  packages/assets-controllers/src/MultichainBalancesController/MultichainBalancesController.test.ts
  packages/sample-controllers/CHANGELOG.md
  packages/sample-controllers/LICENSE
  packages/sample-controllers/README.md
  packages/sample-controllers/jest.config.js
  packages/sample-controllers/package.json
  packages/sample-controllers/src/index.test.ts
  packages/sample-controllers/src/index.ts
  packages/sample-controllers/src/network-controller-types.ts
  packages/sample-controllers/src/sample-gas-prices-controller.test.ts
  packages/sample-controllers/src/sample-gas-prices-controller.ts
  packages/sample-controllers/src/sample-gas-prices-service/index.test.ts
  packages/sample-controllers/src/sample-gas-prices-service/index.ts
  packages/sample-controllers/src/sample-gas-prices-service/sample-abstract-gas-prices-service.ts
  packages/sample-controllers/src/sample-gas-prices-service/sample-gas-prices-service.test.ts
  packages/sample-controllers/src/sample-gas-prices-service/sample-gas-prices-service.ts
  packages/sample-controllers/src/sample-petnames-controller.test.ts
  packages/sample-controllers/src/sample-petnames-controller.ts
  packages/sample-controllers/tsconfig.build.json
  packages/sample-controllers/tsconfig.json
  packages/sample-controllers/typedoc.json
  teams.json
  tsconfig.build.json
  tsconfig.json
  yarn.lock
Labels: team-extension-platform

#5478 feat: handle primary SRP switch cases
  packages/profile-sync-controller/src/controllers/authentication/AuthenticationController.test.ts
  packages/profile-sync-controller/src/controllers/authentication/AuthenticationController.ts
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
  packages/profile-sync-controller/src/sdk/user-storage.test.ts
  packages/profile-sync-controller/src/sdk/user-storage.ts
Labels: team-identity

#5479 Release 326.0.0
  package.json
  packages/notification-services-controller/package.json
  packages/profile-sync-controller/CHANGELOG.md
  packages/profile-sync-controller/package.json
  yarn.lock
Labels: team-identity

#5488 feat: support transaction batch metrics
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/src/TransactionController.test.ts
  packages/transaction-controller/src/TransactionController.ts
  packages/transaction-controller/src/TransactionControllerIntegration.test.ts
  packages/transaction-controller/src/index.ts
  packages/transaction-controller/src/types.ts
  packages/transaction-controller/src/utils/batch.test.ts
  packages/transaction-controller/src/utils/batch.ts
  packages/transaction-controller/src/utils/eip7702.test.ts
  packages/transaction-controller/src/utils/eip7702.ts
Labels: team-confirmations

#5496 Release 331.0.0
  package.json
  packages/bridge-controller/CHANGELOG.md
  packages/bridge-controller/package.json
  packages/bridge-status-controller/CHANGELOG.md
  packages/bridge-status-controller/package.json
  packages/signature-controller/CHANGELOG.md
  packages/signature-controller/package.json
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/package.json
  packages/user-operation-controller/CHANGELOG.md
  packages/user-operation-controller/package.json
  yarn.lock
Labels: team-confirmations

#5467 docs: add interactive release mode documentation
  docs/contributing.md
Labels: team-wallet-framework

#5492 Expose messenger events & config for RPC failover
  packages/assets-controllers/src/AssetsContractController.test.ts
  packages/controller-utils/CHANGELOG.md
  packages/controller-utils/jest.config.js
  packages/controller-utils/src/create-service-policy.ts
  packages/controller-utils/src/index.test.ts
  packages/controller-utils/src/index.ts
  packages/gas-fee-controller/src/GasFeeController.test.ts
  packages/network-controller/CHANGELOG.md
  packages/network-controller/src/NetworkController.ts
  packages/network-controller/src/create-auto-managed-network-client.test.ts
  packages/network-controller/src/create-auto-managed-network-client.ts
  packages/network-controller/src/create-network-client.ts
  packages/network-controller/src/index.ts
  packages/network-controller/src/rpc-service/abstract-rpc-service.ts
  packages/network-controller/src/rpc-service/rpc-service-chain.test.ts
  packages/network-controller/src/rpc-service/rpc-service-chain.ts
  packages/network-controller/src/rpc-service/rpc-service-requestable.ts
  packages/network-controller/src/rpc-service/rpc-service.test.ts
  packages/network-controller/src/rpc-service/rpc-service.ts
  packages/network-controller/tests/NetworkController.test.ts
  packages/network-controller/tests/helpers.ts
  packages/network-controller/tests/provider-api-tests/block-hash-in-response.ts
  packages/network-controller/tests/provider-api-tests/block-param.ts
  packages/network-controller/tests/provider-api-tests/helpers.ts
  packages/network-controller/tests/provider-api-tests/no-block-param.ts
  packages/profile-sync-controller/src/controllers/user-storage/network-syncing/controller-integration.update-network.test.ts
  packages/transaction-controller/src/TransactionControllerIntegration.test.ts
  tests/helpers.ts
Labels: team-wallet-framework

#5501 Expose error in NetworkController:rpcEndpointUnavailable event
  packages/network-controller/CHANGELOG.md
  packages/network-controller/src/NetworkController.ts
  packages/network-controller/src/create-network-client.ts
  packages/network-controller/src/index.ts
  packages/network-controller/src/rpc-service/rpc-service.ts
  packages/network-controller/tests/provider-api-tests/block-hash-in-response.ts
  packages/network-controller/tests/provider-api-tests/block-param.ts
  packages/network-controller/tests/provider-api-tests/no-block-param.ts
Labels: team-wallet-framework

#5436 feat: support incoming transaction polling on all chains
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/src/TransactionController.ts
  packages/transaction-controller/src/helpers/AccountsApiRemoteTransactionSource.test.ts
  packages/transaction-controller/src/helpers/AccountsApiRemoteTransactionSource.ts
  packages/transaction-controller/src/helpers/IncomingTransactionHelper.test.ts
  packages/transaction-controller/src/helpers/IncomingTransactionHelper.ts
  packages/transaction-controller/src/types.ts
Labels: team-confirmations

#5517 Add chainId to NetworkController:rpcEndpointDegraded
  packages/network-controller/CHANGELOG.md
  packages/network-controller/src/NetworkController.ts
  packages/network-controller/src/create-network-client.ts
Labels: team-wallet-framework

#5513 Release/337.0.0
  package.json
  packages/bridge-controller/CHANGELOG.md
  packages/bridge-controller/package.json
  packages/bridge-status-controller/CHANGELOG.md
  packages/bridge-status-controller/package.json
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/package.json
  packages/user-operation-controller/CHANGELOG.md
  packages/user-operation-controller/package.json
  yarn.lock
Labels: team-confirmations

#5520 Revert "feat: add `MegaEth Testnet` as default network"
  packages/assets-controllers/src/TokenDetectionController.test.ts
  packages/network-controller/src/NetworkController.ts
  packages/network-controller/tests/NetworkController.test.ts
  packages/transaction-controller/src/constants.ts
  tests/mock-network.ts
Labels: team-network-enablement

#5521 chore: bump `@metamask/create-relerase-branch` to `^4.1.1`
  package.json
  yarn.lock
Labels: team-wallet-framework

#5519 fix: gas estimation for type 4 transactions
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/src/TransactionController.test.ts
  packages/transaction-controller/src/TransactionController.ts
  packages/transaction-controller/src/utils/feature-flags.ts
  packages/transaction-controller/src/utils/gas.test.ts
  packages/transaction-controller/src/utils/gas.ts
  packages/transaction-controller/src/utils/simulation-api.ts
Labels: team-confirmations

#5401 feat: support publish batch hook
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/jest.config.js
  packages/transaction-controller/src/TransactionController.test.ts
  packages/transaction-controller/src/TransactionController.ts
  packages/transaction-controller/src/hooks/CollectPublishHook.test.ts
  packages/transaction-controller/src/hooks/CollectPublishHook.ts
  packages/transaction-controller/src/hooks/ExtraTransactionsPublishHook.test.ts
  packages/transaction-controller/src/hooks/ExtraTransactionsPublishHook.ts
  packages/transaction-controller/src/index.ts
  packages/transaction-controller/src/types.ts
  packages/transaction-controller/src/utils/batch.test.ts
  packages/transaction-controller/src/utils/batch.ts
  packages/transaction-controller/src/utils/eip7702.test.ts
  packages/transaction-controller/src/utils/eip7702.ts
  packages/transaction-controller/src/utils/gas.test.ts
  packages/transaction-controller/src/utils/gas.ts
  packages/transaction-controller/src/utils/nonce.test.ts
  packages/transaction-controller/src/utils/nonce.ts
Labels: team-confirmations

#5526 feat: transaction batch security validation
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/src/index.ts
  packages/transaction-controller/src/types.ts
  packages/transaction-controller/src/utils/batch.test.ts
  packages/transaction-controller/src/utils/batch.ts
Labels: team-confirmations

#5524 feat: add gas fee tokens to transaction metadata
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/src/TransactionController.test.ts
  packages/transaction-controller/src/TransactionController.ts
  packages/transaction-controller/src/index.ts
  packages/transaction-controller/src/types.ts
  packages/transaction-controller/src/utils/simulation-api.ts
  packages/transaction-controller/src/utils/simulation.test.ts
  packages/transaction-controller/src/utils/simulation.ts
Labels: team-confirmations

#5547 Release 344.0.0
  package.json
  packages/bridge-controller/package.json
  packages/bridge-status-controller/package.json
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/package.json
  packages/user-operation-controller/package.json
  yarn.lock
Labels: team-confirmations

#5552 fix: type-4 transaction simulation
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/src/TransactionController.test.ts
  packages/transaction-controller/src/TransactionController.ts
  packages/transaction-controller/src/utils/simulation.ts
Labels: team-confirmations

#5549 feat: Configure pending transaction polling intervals using remote fe…
  packages/transaction-controller/src/TransactionController.ts
  packages/transaction-controller/src/helpers/PendingTransactionTracker.test.ts
  packages/transaction-controller/src/helpers/PendingTransactionTracker.ts
  packages/transaction-controller/src/helpers/TransactionPoller.test.ts
  packages/transaction-controller/src/helpers/TransactionPoller.ts
  packages/transaction-controller/src/utils/feature-flags.test.ts
  packages/transaction-controller/src/utils/feature-flags.ts
Labels: team-confirmations

#5527 feat: add `MegaETH Testnet` to network-controller
  packages/network-controller/src/NetworkController.ts
  packages/network-controller/src/types.ts
  packages/network-controller/tests/NetworkController.test.ts
  packages/transaction-controller/src/constants.ts
  tests/mock-network.ts
Labels: team-network-enablement

#5563 fix: validation of EIP-7702 contract signatures with odd-length chain ID
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/src/utils/feature-flags.test.ts
  packages/transaction-controller/src/utils/feature-flags.ts
Labels: team-confirmations

#5111 Document new process for updating changelogs
  .github/pull_request_template.md
  docs/contributing.md
Labels: team-wallet-framework

#5557 Release/346.0.0
  package.json
  packages/bridge-controller/package.json
  packages/bridge-status-controller/package.json
  packages/sample-controllers/CHANGELOG.md
  packages/sample-controllers/package.json
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/package.json
  packages/user-operation-controller/package.json
  yarn.lock
Labels: team-confirmations

#5560 chore: remove `goerli` and `linea goerli` from `network-controller` as default network
  packages/assets-controllers/src/TokenDetectionController.test.ts
  packages/assets-controllers/src/TokenListController.test.ts
  packages/gas-fee-controller/src/GasFeeController.test.ts
  packages/network-controller/src/NetworkController.ts
  packages/network-controller/src/constants.ts
  packages/network-controller/tests/NetworkController.test.ts
  packages/network-controller/tests/helpers.ts
  packages/network-controller/tests/provider-api-tests/shared-tests.ts
  packages/selected-network-controller/tests/SelectedNetworkController.test.ts
  packages/transaction-controller/src/TransactionController.test.ts
  packages/transaction-controller/src/TransactionControllerIntegration.test.ts
Labels: team-network-enablement
