Repository MetaMask/core, pull requests merged in 2025-02, with the labels that each got.

#5244 chore(profile-sync): Rename `ControllerMessenger` to `Messenger`
  packages/profile-sync-controller/src/controllers/authentication/AuthenticationController.test.ts
  packages/profile-sync-controller/src/controllers/authentication/AuthenticationController.ts
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
  packages/profile-sync-controller/src/controllers/user-storage/__fixtures__/mockMessenger.ts
  packages/profile-sync-controller/src/controllers/user-storage/network-syncing/controller-integration.update-network.test.ts
Labels: team-wallet-framework

#5256 chore(selected-network): Rename `ControllerMessenger` to `Messenger`
  packages/selected-network-controller/src/SelectedNetworkController.ts
  packages/selected-network-controller/tests/SelectedNetworkController.test.ts
  packages/selected-network-controller/tests/SelectedNetworkMiddleware.test.ts
Labels: team-wallet-framework

#5170 chore: fix lint warnings in `KeyringController`
  eslint-warning-thresholds.json
  packages/keyring-controller/src/KeyringController.test.ts
  packages/keyring-controller/src/KeyringController.ts
Labels: team-wallet-framework

#5237 chore(signature): Rename `RestrictedControllerMessenger` to `RestrictedMessenger`
  packages/signature-controller/src/SignatureController.ts
Labels: team-wallet-framework

#5236 chore(name): Rename `RestrictedControllerMessenger` to `RestrictedMessenger`
  packages/name-controller/src/NameController.ts
Labels: team-wallet-framework

#5235 chore(logging): Rename `ControllerMessenger` to `Messenger`
  packages/logging-controller/src/LoggingController.test.ts
  packages/logging-controller/src/LoggingController.ts
Labels: team-wallet-framework

#5091 chore(address-book-controller): Rename `ControllerMessenger` to `Messenger`
  packages/address-book-controller/src/AddressBookController.test.ts
  packages/address-book-controller/src/AddressBookController.ts
Labels: team-wallet-framework

#5234 chore(transaction): Rename `ControllerMessenger` to `Messenger`
  packages/transaction-controller/src/TransactionController.test.ts
  packages/transaction-controller/src/TransactionController.ts
  packages/transaction-controller/src/TransactionControllerIntegration.test.ts
  packages/transaction-controller/src/utils/swaps.test.ts
Labels: team-wallet-framework

#5233 chore(message-manager): Rename `ControllerMessenger` to `Messenger`
  packages/message-manager/src/AbstractMessageManager.test.ts
  packages/message-manager/src/AbstractMessageManager.ts
  packages/message-manager/src/DecryptMessageManager.ts
  packages/message-manager/src/EncryptionPublicKeyManager.ts
Labels: team-wallet-framework

#5255 chore(rate-limit): Rename `ControllerMessenger` to `Messenger`
  packages/rate-limit-controller/src/RateLimitController.test.ts
  packages/rate-limit-controller/src/RateLimitController.ts
Labels: team-wallet-framework

#5253 chore(remote-feature-flag): Rename `ControllerMessenger` to `Messenger`
  packages/remote-feature-flag-controller/src/remote-feature-flag-controller.test.ts
  packages/remote-feature-flag-controller/src/remote-feature-flag-controller.ts
Labels: team-wallet-framework

#5254 chore(queued-request): Rename `ControllerMessenger` to `Messenger`
  packages/queued-request-controller/src/QueuedRequestController.test.ts
  packages/queued-request-controller/src/QueuedRequestController.ts
Labels: team-wallet-framework

#5226 Add ability to create RPC service chain
  packages/network-controller/src/rpc-service/rpc-service-chain.test.ts
  packages/network-controller/src/rpc-service/rpc-service-chain.ts
Labels: team-wallet-framework

#5262 fix: transaction resubmit on multiple endpoints
  eslint-warning-thresholds.json
  packages/transaction-controller/src/TransactionController.ts
  packages/transaction-controller/src/helpers/MultichainTrackingHelper.test.ts
  packages/transaction-controller/src/helpers/MultichainTrackingHelper.ts
  packages/transaction-controller/src/helpers/PendingTransactionTracker.test.ts
  packages/transaction-controller/src/helpers/PendingTransactionTracker.ts
Labels: team-confirmations

#5261 fix: eslint warnings & errors
  eslint-warning-thresholds.json
  packages/profile-sync-controller/jest.environment.js
  packages/profile-sync-controller/src/controllers/authentication/AuthenticationController.test.ts
  packages/profile-sync-controller/src/controllers/authentication/AuthenticationController.ts
  packages/profile-sync-controller/src/controllers/authentication/__fixtures__/mockResponses.ts
  packages/profile-sync-controller/src/controllers/authentication/services.ts
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
  packages/profile-sync-controller/src/controllers/user-storage/__fixtures__/mockMessenger.ts
  packages/profile-sync-controller/src/controllers/user-storage/__fixtures__/mockResponses.ts
  packages/profile-sync-controller/src/controllers/user-storage/__fixtures__/mockServices.ts
  packages/profile-sync-controller/src/controllers/user-storage/__fixtures__/test-utils.ts
  packages/profile-sync-controller/src/controllers/user-storage/account-syncing/__fixtures__/mockAccounts.ts
  packages/profile-sync-controller/src/controllers/user-storage/account-syncing/__fixtures__/test-utils.ts
  packages/profile-sync-controller/src/controllers/user-storage/account-syncing/controller-integration.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/account-syncing/controller-integration.ts
  packages/profile-sync-controller/src/controllers/user-storage/account-syncing/setup-subscriptions.ts
  packages/profile-sync-controller/src/controllers/user-storage/account-syncing/sync-utils.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/account-syncing/sync-utils.ts
  packages/profile-sync-controller/src/controllers/user-storage/account-syncing/types.ts
  packages/profile-sync-controller/src/controllers/user-storage/account-syncing/utils.ts
  packages/profile-sync-controller/src/controllers/user-storage/network-syncing/add-network-utils.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/network-syncing/add-network-utils.ts
  packages/profile-sync-controller/src/controllers/user-storage/network-syncing/controller-integration.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/network-syncing/controller-integration.ts
  packages/profile-sync-controller/src/controllers/user-storage/network-syncing/controller-integration.update-network.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/network-syncing/services.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/network-syncing/services.ts
  packages/profile-sync-controller/src/controllers/user-storage/network-syncing/sync-all.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/network-syncing/sync-all.ts
  packages/profile-sync-controller/src/controllers/user-storage/network-syncing/sync-mutations.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/network-syncing/sync-mutations.ts
  packages/profile-sync-controller/src/controllers/user-storage/network-syncing/update-network-utils.ts
  packages/profile-sync-controller/src/controllers/user-storage/services.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/services.ts
  packages/profile-sync-controller/src/controllers/user-storage/utils.ts
  packages/profile-sync-controller/src/sdk/__fixtures__/mock-auth.ts
  packages/profile-sync-controller/src/sdk/__fixtures__/mock-userstorage.ts
  packages/profile-sync-controller/src/sdk/__fixtures__/test-utils.ts
  packages/profile-sync-controller/src/sdk/authentication-jwt-bearer/flow-siwe.ts
  packages/profile-sync-controller/src/sdk/authentication-jwt-bearer/flow-srp.ts
  packages/profile-sync-controller/src/sdk/authentication-jwt-bearer/services.ts
  packages/profile-sync-controller/src/sdk/authentication.test.ts
  packages/profile-sync-controller/src/sdk/authentication.ts
  packages/profile-sync-controller/src/sdk/user-storage.test.ts
  packages/profile-sync-controller/src/sdk/user-storage.ts
  packages/profile-sync-controller/src/sdk/utils/eip-6963-metamask-provider.test.ts
  packages/profile-sync-controller/src/sdk/utils/eip-6963-metamask-provider.ts
  packages/profile-sync-controller/src/sdk/utils/messaging-signing-snap-requests.test.ts
  packages/profile-sync-controller/src/sdk/utils/validate-login-response.test.ts
  packages/profile-sync-controller/src/shared/encryption/constants.ts
  packages/profile-sync-controller/src/shared/encryption/encryption.ts
  packages/profile-sync-controller/src/shared/env.test.ts
Labels: team-identity

#5263 Export AbstractRpcService
  packages/network-controller/CHANGELOG.md
  packages/network-controller/src/index.ts
Labels: team-wallet-framework

#5266 chore(accounts): fix AccountsController eslint warnings & errors
  eslint-warning-thresholds.json
  packages/accounts-controller/src/AccountsController.ts
Labels: team-wallet-framework

#5265 chore: bump `@metamask/snaps-{sdk,utils,controllers}`
  packages/accounts-controller/CHANGELOG.md
  packages/accounts-controller/package.json
  packages/assets-controllers/CHANGELOG.md
  packages/assets-controllers/package.json
  packages/multichain-transactions-controller/CHANGELOG.md
  packages/multichain-transactions-controller/package.json
  packages/profile-sync-controller/CHANGELOG.md
  packages/profile-sync-controller/package.json
  yarn.lock
Labels: team-wallet-framework

#5268 chore(earn): Rename ControllerMessenger to Messenger
  packages/earn-controller/src/EarnController.test.ts
  packages/earn-controller/src/EarnController.ts
Labels: team-wallet-framework

#5159 Reorganize ESLint warning thresholds and output
  eslint-warning-thresholds.json
  scripts/run-eslint.ts
Labels: team-wallet-framework

#5278 feat: remove metametrics dependencies in UserStorageController
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
  packages/profile-sync-controller/src/controllers/user-storage/account-syncing/controller-integration.test.ts
Labels: team-identity

#5280 chore: bump `@metamask/{keyring-api,eth-snap-keyring}`
  packages/accounts-controller/CHANGELOG.md
  packages/accounts-controller/package.json
  packages/assets-controllers/CHANGELOG.md
  packages/assets-controllers/package.json
  packages/keyring-controller/CHANGELOG.md
  packages/keyring-controller/package.json
  packages/multichain-transactions-controller/CHANGELOG.md
  packages/multichain-transactions-controller/package.json
  packages/profile-sync-controller/CHANGELOG.md
  packages/profile-sync-controller/package.json
  yarn.lock
Labels: team-wallet-framework

#5282 chore(multichain-assets): Rename `ControllerMessenger` to `Messenger`
  packages/assets-controllers/src/MultichainAssetsController/MultichainAssetsController.test.ts
Labels: team-wallet-framework

#5284 Release 294.0.0
  package.json
  packages/notification-services-controller/CHANGELOG.md
  packages/notification-services-controller/package.json
  packages/profile-sync-controller/CHANGELOG.md
  packages/profile-sync-controller/package.json
  yarn.lock
Labels: team-identity

#5299 chore: Improve tag fetching in create-update-issues workflow
  .github/workflows/create-update-issues.yaml
Labels: team-wallet-framework

#5285 feat: support type 4 transactions
  eslint-warning-thresholds.json
  packages/transaction-controller/jest.config.js
  packages/transaction-controller/package.json
  packages/transaction-controller/src/TransactionController.ts
  packages/transaction-controller/src/gas-flows/OracleLayer1GasFeeFlow.ts
  packages/transaction-controller/src/index.ts
  packages/transaction-controller/src/types.ts
  packages/transaction-controller/src/utils/eip7702.test.ts
  packages/transaction-controller/src/utils/eip7702.ts
  packages/transaction-controller/src/utils/prepare.test.ts
  packages/transaction-controller/src/utils/prepare.ts
  packages/transaction-controller/src/utils/utils.ts
  packages/transaction-controller/src/utils/validation.test.ts
  packages/transaction-controller/src/utils/validation.ts
  yarn.config.cjs
  yarn.lock
Labels: team-confirmations

#5172 fix: throw explicit error when `KeyringController` is locked
  packages/keyring-controller/jest.config.js
  packages/keyring-controller/src/KeyringController.test.ts
  packages/keyring-controller/src/KeyringController.ts
  packages/keyring-controller/src/constants.ts
Labels: team-wallet-framework

#5216 feat: add new keyring type for oneKey
  packages/accounts-controller/src/AccountsController.test.ts
  packages/accounts-controller/src/utils.ts
  packages/keyring-controller/src/KeyringController.ts
Labels: team-hardware-wallets

#5311 feat: expose all user storage methods through messenger actions
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
Labels: team-identity

#5298 RpcService: Regard node-fetch errors as retriable
  packages/network-controller/package.json
  packages/network-controller/src/rpc-service/rpc-service.test.ts
  packages/network-controller/src/rpc-service/rpc-service.ts
  yarn.lock
Labels: team-wallet-framework

#5322 fix: change maxNumberOfAccountsToAdd default value from 100 to Infinity
  packages/profile-sync-controller/src/controllers/user-storage/account-syncing/controller-integration.ts
Labels: team-identity

#5324 fix: remove unused events from `UserStorageController`
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
Labels: team-identity

#5326 feat: add optional `validateAgainstSchema` option when creating user storage entry paths
  packages/profile-sync-controller/src/sdk/user-storage.ts
  packages/profile-sync-controller/src/shared/storage-schema.test.ts
  packages/profile-sync-controller/src/shared/storage-schema.ts
Labels: team-identity

#5290 Create RPC middleware using RPC services
  eslint-warning-thresholds.json
  packages/assets-controllers/src/AssetsContractController.test.ts
  packages/gas-fee-controller/src/GasFeeController.test.ts
  packages/network-controller/CHANGELOG.md
  packages/network-controller/package.json
  packages/network-controller/src/NetworkController.ts
  packages/network-controller/src/create-auto-managed-network-client.test.ts
  packages/network-controller/src/create-auto-managed-network-client.ts
  packages/network-controller/src/create-network-client.ts
  packages/network-controller/tests/NetworkController.test.ts
  packages/network-controller/tests/provider-api-tests/block-param.ts
  packages/network-controller/tests/provider-api-tests/helpers.ts
  packages/network-controller/tests/provider-api-tests/no-block-param.ts
  packages/network-controller/tests/provider-api-tests/shared-tests.ts
  packages/profile-sync-controller/src/controllers/user-storage/network-syncing/controller-integration.update-network.test.ts
  packages/transaction-controller/src/TransactionControllerIntegration.test.ts
  yarn.lock
Labels: team-wallet-framework

#5304 Discourage the use of barrel exports
  docs/contributing.md
  docs/controller-guidelines.md
  docs/package-guidelines.md
Labels: team-wallet-framework

#5342 Release/301.0.0
  package.json
  packages/earn-controller/CHANGELOG.md
  packages/earn-controller/package.json
Labels: team-earn

#5306 feat: support atomic batch transactions
  eslint-warning-thresholds.json
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/jest.config.js
  packages/transaction-controller/package.json
  packages/transaction-controller/src/TransactionController.test.ts
  packages/transaction-controller/src/TransactionController.ts
  packages/transaction-controller/src/TransactionControllerIntegration.test.ts
  packages/transaction-controller/src/constants.ts
  packages/transaction-controller/src/index.ts
  packages/transaction-controller/src/types.ts
  packages/transaction-controller/src/utils/batch.test.ts
  packages/transaction-controller/src/utils/batch.ts
  packages/transaction-controller/src/utils/eip7702.test.ts
  packages/transaction-controller/src/utils/eip7702.ts
  packages/transaction-controller/src/utils/feature-flags.test.ts
  packages/transaction-controller/src/utils/feature-flags.ts
  packages/transaction-controller/src/utils/validation.test.ts
  packages/transaction-controller/src/utils/validation.ts
  packages/transaction-controller/tsconfig.build.json
  packages/transaction-controller/tsconfig.json
  yarn.lock
Labels: team-confirmations

#5357 Release 303.0.0
  package.json
  packages/accounts-controller/package.json
  packages/assets-controllers/package.json
  packages/keyring-controller/CHANGELOG.md
  packages/keyring-controller/package.json
  packages/multichain-network-controller/package.json
  packages/multichain-transactions-controller/package.json
  packages/notification-services-controller/package.json
  packages/preferences-controller/package.json
  packages/profile-sync-controller/CHANGELOG.md
  packages/profile-sync-controller/package.json
  packages/signature-controller/package.json
  packages/user-operation-controller/package.json
  yarn.lock
Labels: team-identity

#5368 feat: STAKE-942: add pooled staking vault daily apys and vault apy averages to earn controller
  packages/earn-controller/src/EarnController.test.ts
  packages/earn-controller/src/EarnController.ts
Labels: team-earn

#5360 Integrate RPC failover into NetworkController
  eslint-warning-thresholds.json
  packages/assets-controllers/src/AssetsContractController.test.ts
  packages/assets-controllers/src/AssetsContractControllerWithNetworkClientId.test.ts
  packages/assets-controllers/src/NftDetectionController.test.ts
  packages/assets-controllers/src/TokenDetectionController.test.ts
  packages/network-controller/CHANGELOG.md
  packages/network-controller/src/NetworkController.ts
  packages/network-controller/src/create-auto-managed-network-client.test.ts
  packages/network-controller/src/create-network-client.ts
  packages/network-controller/src/types.ts
  packages/network-controller/tests/NetworkController.test.ts
  packages/network-controller/tests/helpers.ts
  packages/network-controller/tests/provider-api-tests/block-hash-in-response.ts
  packages/network-controller/tests/provider-api-tests/block-param.ts
  packages/network-controller/tests/provider-api-tests/helpers.ts
  packages/network-controller/tests/provider-api-tests/no-block-param.ts
  packages/profile-sync-controller/src/controllers/user-storage/network-syncing/__fixtures__/mockNetwork.ts
  packages/selected-network-controller/tests/SelectedNetworkController.test.ts
  packages/transaction-controller/src/TransactionControllerIntegration.test.ts
Labels: team-wallet-framework

#5410 chore: align keyring controller sign authorization action
  packages/transaction-controller/src/TransactionController.ts
  packages/transaction-controller/src/utils/eip7702.test.ts
  packages/transaction-controller/src/utils/eip7702.ts
Labels: team-confirmations
