Repository MetaMask/core, pull requests merged in 2025-01, with the labels that each got.

#5102 fix: match signature request and message params ID
  packages/signature-controller/src/SignatureController.test.ts
  packages/signature-controller/src/SignatureController.ts
Labels: team-confirmations

#5104 Release 276.0.0
  package.json
  packages/signature-controller/CHANGELOG.md
  packages/signature-controller/package.json
Labels: team-confirmations

#5078 feat: decouple account sync logic from `UserStorageController`
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
  packages/profile-sync-controller/src/controllers/user-storage/__fixtures__/test-utils.ts
  packages/profile-sync-controller/src/controllers/user-storage/account-syncing/__fixtures__/mockAccounts.ts
  packages/profile-sync-controller/src/controllers/user-storage/account-syncing/__fixtures__/test-utils.ts
  packages/profile-sync-controller/src/controllers/user-storage/account-syncing/constants.ts
  packages/profile-sync-controller/src/controllers/user-storage/account-syncing/controller-integration.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/account-syncing/controller-integration.ts
  packages/profile-sync-controller/src/controllers/user-storage/account-syncing/setup-subscriptions.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/account-syncing/setup-subscriptions.ts
  packages/profile-sync-controller/src/controllers/user-storage/account-syncing/sync-utils.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/account-syncing/sync-utils.ts
  packages/profile-sync-controller/src/controllers/user-storage/account-syncing/types.ts
  packages/profile-sync-controller/src/controllers/user-storage/account-syncing/utils.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/account-syncing/utils.ts
  packages/profile-sync-controller/src/controllers/user-storage/accounts/user-storage.test.ts
Labels: team-identity

#5117 Release 277.0.0
  package.json
  packages/notification-services-controller/package.json
  packages/profile-sync-controller/CHANGELOG.md
  packages/profile-sync-controller/package.json
  yarn.lock
Labels: team-identity

#4727 Bump `eslint` to `^9.11.1` and migrate to flat config
  .depcheckrc.yml
  .eslintrc.js
  eslint.config.mjs
  package.json
  packages/assets-controllers/jest.environment.js
  packages/build-utils/package.json
  packages/controller-utils/jest.environment.js
  packages/notification-services-controller/jest.environment.js
  packages/profile-sync-controller/jest.environment.js
  yarn.lock
Labels: team-wallet-framework

#5105 feat: add a `customProvider` option to the sdk `JwtBearerAuth` class
  packages/profile-sync-controller/src/sdk/__fixtures__/test-utils.ts
  packages/profile-sync-controller/src/sdk/authentication-jwt-bearer/flow-srp.ts
  packages/profile-sync-controller/src/sdk/authentication.test.ts
  packages/profile-sync-controller/src/sdk/authentication.ts
  packages/profile-sync-controller/src/sdk/utils/messaging-signing-snap-requests.test.ts
Labels: team-identity

#5123 fix: create-package script
  scripts/create-package/utils.test.ts
  scripts/create-package/utils.ts
Labels: team-wallet-framework

#5130 Release 279.0.0
  package.json
  packages/notification-services-controller/package.json
  packages/profile-sync-controller/CHANGELOG.md
  packages/profile-sync-controller/package.json
  yarn.lock
Labels: team-identity

#5139 feat: add sentry context to erroneous situation callbacks
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
  packages/profile-sync-controller/src/controllers/user-storage/account-syncing/controller-integration.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/account-syncing/controller-integration.ts
Labels: team-identity

#5144 Release 282.0.0
  package.json
  packages/notification-services-controller/package.json
  packages/profile-sync-controller/CHANGELOG.md
  packages/profile-sync-controller/package.json
  yarn.lock
Labels: team-identity

#5141 Start extracting service policy boilerplate to common function
  packages/controller-utils/CHANGELOG.md
  packages/controller-utils/jest.config.js
  packages/controller-utils/package.json
  packages/controller-utils/src/create-service-policy.test.ts
  packages/controller-utils/src/create-service-policy.ts
  packages/controller-utils/src/index.test.ts
  packages/controller-utils/src/index.ts
  yarn.lock
Labels: team-wallet-framework

#5147 feat: persist `isAccountSyncingReadyToBeDispatched` statue value
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
Labels: team-identity

#5148 Release 283.0.0
  package.json
  packages/notification-services-controller/package.json
  packages/profile-sync-controller/CHANGELOG.md
  packages/profile-sync-controller/package.json
  yarn.lock
Labels: team-identity

#5089 chore(docs): Rename `ControllerMessenger` to `Messenger`
  docs/writing-controllers.md
  examples/example-controllers/src/gas-prices-controller.test.ts
  examples/example-controllers/src/gas-prices-controller.ts
  examples/example-controllers/src/pet-names-controller.test.ts
  examples/example-controllers/src/pet-names-controller.ts
Labels: team-wallet-framework

#5158 Use dev Node to check for unsupported Node builtins in tests
  eslint-warning-thresholds.json
  eslint.config.mjs
Labels: team-wallet-framework

#5122 fix: Network controller race condition after state update
  packages/network-controller/src/NetworkController.ts
  packages/network-controller/tests/NetworkController.test.ts
Labels: team-wallet-api-platform

#4985 fix: if image starts with 'ipfs://', the return value should be string type
  packages/assets-controllers/src/Standards/NftStandards/ERC721/ERC721Standard.test.ts
  packages/assets-controllers/src/Standards/NftStandards/ERC721/ERC721Standard.ts
Labels: bug

#4813 feat: Add Multichain API to `@metamask/multichain`
  eslint-warning-thresholds.json
  packages/multichain/package.json
  packages/multichain/src/adapters/caip-permission-adapter-permittedChains.ts
  packages/multichain/src/adapters/caip-permission-adapter-session-scopes.test.ts
  packages/multichain/src/adapters/caip-permission-adapter-session-scopes.ts
  packages/multichain/src/handlers/wallet-getSession.test.ts
  packages/multichain/src/handlers/wallet-getSession.ts
  packages/multichain/src/handlers/wallet-invokeMethod.test.ts
  packages/multichain/src/handlers/wallet-invokeMethod.ts
  packages/multichain/src/handlers/wallet-revokeSession.test.ts
  packages/multichain/src/handlers/wallet-revokeSession.ts
  packages/multichain/src/index.test.ts
  packages/multichain/src/index.ts
  packages/multichain/src/middlewares/MultichainMiddlewareManager.test.ts
  packages/multichain/src/middlewares/MultichainMiddlewareManager.ts
  packages/multichain/src/middlewares/MultichainSubscriptionManager.test.ts
  packages/multichain/src/middlewares/MultichainSubscriptionManager.ts
  packages/multichain/src/middlewares/multichainMethodCallValidator.test.ts
  packages/multichain/src/middlewares/multichainMethodCallValidator.ts
  packages/multichain/src/scope/assert.test.ts
  packages/multichain/src/scope/assert.ts
  packages/multichain/src/scope/authorization.test.ts
  packages/multichain/src/scope/authorization.ts
  packages/multichain/src/scope/constants.test.ts
  packages/multichain/src/scope/constants.ts
  packages/multichain/src/scope/filter.test.ts
  packages/multichain/src/scope/filter.ts
  packages/multichain/src/scope/types.ts
  types/@metamask/eth-json-rpc-filters.d.ts
  yarn.lock
Labels: team-wallet-api-platform, team-wallet-framework

#5149 Complete `createServicePolicy`
  eslint-warning-thresholds.json
  packages/controller-utils/CHANGELOG.md
  packages/controller-utils/src/create-service-policy.test.ts
  packages/controller-utils/src/create-service-policy.ts
  packages/controller-utils/src/index.test.ts
  packages/controller-utils/src/index.ts
Labels: team-wallet-framework

#5188 createServicePolicy: Convert callbacks to methods
  packages/controller-utils/CHANGELOG.md
  packages/controller-utils/src/create-service-policy.test.ts
  packages/controller-utils/src/create-service-policy.ts
  packages/controller-utils/src/index.ts
Labels: team-wallet-framework

#5193 Fix NetworkController Redux selectors
  eslint-warning-thresholds.json
  packages/network-controller/CHANGELOG.md
  packages/network-controller/src/NetworkController.ts
  packages/network-controller/tests/NetworkController.test.ts
Labels: team-wallet-framework

#5192 Update `createServicePolicy` to expose sub-policies; add re-exports from `cockatiel`
  packages/controller-utils/CHANGELOG.md
  packages/controller-utils/jest.config.js
  packages/controller-utils/src/create-service-policy.ts
  packages/controller-utils/src/index.test.ts
  packages/controller-utils/src/index.ts
Labels: team-wallet-framework

#5109 Refactor services to align with eventual RpcService
  eslint-warning-thresholds.json
  packages/assets-controllers/CHANGELOG.md
  packages/assets-controllers/package.json
  packages/assets-controllers/src/TokenRatesController.test.ts
  packages/assets-controllers/src/TokenRatesController.ts
  packages/assets-controllers/src/token-prices-service/abstract-token-prices-service.ts
  packages/assets-controllers/src/token-prices-service/codefi-v2.test.ts
  packages/assets-controllers/src/token-prices-service/codefi-v2.ts
  packages/remote-feature-flag-controller/CHANGELOG.md
  packages/remote-feature-flag-controller/package.json
  packages/remote-feature-flag-controller/src/client-config-api-service/abstract-client-config-api-service.ts
  packages/remote-feature-flag-controller/src/client-config-api-service/client-config-api-service.test.ts
  packages/remote-feature-flag-controller/src/client-config-api-service/client-config-api-service.ts
  packages/remote-feature-flag-controller/src/remote-feature-flag-controller.ts
  yarn.lock
Labels: team-wallet-framework

#5163 NetworkController: Add RPC service class
  eslint-warning-thresholds.json
  packages/network-controller/src/rpc-service/abstract-rpc-service.ts
  packages/network-controller/src/rpc-service/rpc-service.test.ts
  packages/network-controller/src/rpc-service/rpc-service.ts
  packages/network-controller/src/rpc-service/shared.ts
Labels: team-wallet-framework

#5116 Fix NetworkController to handle clearing of messenger
  eslint-warning-thresholds.json
  packages/network-controller/CHANGELOG.md
  packages/network-controller/src/NetworkController.ts
  packages/network-controller/tests/NetworkController.test.ts
Labels: team-wallet-framework

#5202 Add failover support to RpcService
  packages/network-controller/src/rpc-service/rpc-service.test.ts
  packages/network-controller/src/rpc-service/rpc-service.ts
Labels: team-wallet-framework

#5223 feat: bump @metamask/utils to v11.1.0
  examples/example-controllers/package.json
  package.json
  packages/accounts-controller/package.json
  packages/address-book-controller/package.json
  packages/approval-controller/package.json
  packages/assets-controllers/package.json
  packages/base-controller/package.json
  packages/build-utils/package.json
  packages/controller-utils/package.json
  packages/ens-controller/package.json
  packages/eth-json-rpc-provider/package.json
  packages/gas-fee-controller/package.json
  packages/json-rpc-engine/package.json
  packages/json-rpc-middleware-stream/package.json
  packages/keyring-controller/package.json
  packages/message-manager/package.json
  packages/multichain-transactions-controller/package.json
  packages/multichain/package.json
  packages/name-controller/package.json
  packages/network-controller/package.json
  packages/notification-services-controller/package.json
  packages/permission-controller/package.json
  packages/permission-log-controller/package.json
  packages/polling-controller/package.json
  packages/queued-request-controller/package.json
  packages/rate-limit-controller/package.json
  packages/remote-feature-flag-controller/package.json
  packages/selected-network-controller/package.json
  packages/signature-controller/package.json
  packages/token-search-discovery-controller/package.json
  packages/transaction-controller/package.json
  packages/user-operation-controller/package.json
  yarn.lock
Labels: team-assets

#5090 chore(accounts): Rename `ControllerMessenger` to `Messenger`
  packages/accounts-controller/src/AccountsController.test.ts
  packages/accounts-controller/src/AccountsController.ts
Labels: team-wallet-framework

#5092 chore(accouncement): Rename `ControllerMessenger` to `Messenger`
  packages/announcement-controller/src/AnnouncementController.test.ts
  packages/announcement-controller/src/AnnouncementController.ts
  packages/announcement-controller/src/index.ts
Labels: team-wallet-framework

#5228 chore(approval): Rename `ControllerMessenger` to `Messenger`
  packages/approval-controller/src/ApprovalController.test.ts
  packages/approval-controller/src/ApprovalController.ts
Labels: team-wallet-framework

#5231 chore(ens): Rename `ControllerMessenger` to `Messenger`
  packages/ens-controller/src/EnsController.test.ts
  packages/ens-controller/src/EnsController.ts
Labels: team-wallet-framework

#5230 chore(composable): Rename `ControllerMessenger` to `Messenger`
  packages/composable-controller/src/ComposableController.test.ts
  packages/composable-controller/src/ComposableController.ts
Labels: team-wallet-framework

#5240 chore(multichain-transactions): Rename `RestrictedControllerMessenger` to `RestrictedMessenger`
  packages/multichain-transactions-controller/src/MultichainTransactionsController.test.ts
  packages/multichain-transactions-controller/src/MultichainTransactionsController.ts
Labels: team-wallet-framework

#5239 chore(keyring): Rename `RestrictedControllerMessenger` to `RestrictedMessenger`
  packages/keyring-controller/src/KeyringController.test.ts
  packages/keyring-controller/src/KeyringController.ts
Labels: team-wallet-framework

#5229 chore(assets): Rename `ControllerMessenger` to `Messenger`
  packages/assets-controllers/src/AccountTrackerController.test.ts
  packages/assets-controllers/src/AccountTrackerController.ts
  packages/assets-controllers/src/AssetsContractController.test.ts
  packages/assets-controllers/src/AssetsContractController.ts
  packages/assets-controllers/src/CurrencyRateController.test.ts
  packages/assets-controllers/src/CurrencyRateController.ts
  packages/assets-controllers/src/MultichainBalancesController/MultichainBalancesController.test.ts
  packages/assets-controllers/src/MultichainBalancesController/MultichainBalancesController.ts
  packages/assets-controllers/src/NftController.test.ts
  packages/assets-controllers/src/NftController.ts
  packages/assets-controllers/src/NftDetectionController.test.ts
  packages/assets-controllers/src/NftDetectionController.ts
  packages/assets-controllers/src/RatesController/RatesController.test.ts
  packages/assets-controllers/src/RatesController/types.ts
  packages/assets-controllers/src/TokenBalancesController.test.ts
  packages/assets-controllers/src/TokenBalancesController.ts
  packages/assets-controllers/src/TokenDetectionController.test.ts
  packages/assets-controllers/src/TokenDetectionController.ts
  packages/assets-controllers/src/TokenListController.test.ts
  packages/assets-controllers/src/TokenListController.ts
  packages/assets-controllers/src/TokenRatesController.test.ts
  packages/assets-controllers/src/TokenRatesController.ts
  packages/assets-controllers/src/TokensController.test.ts
  packages/assets-controllers/src/TokensController.ts
Labels: team-wallet-framework

#5242 chore(notification-services): Rename `ControllerMessenger` to `Messenger`
  packages/notification-services-controller/src/NotificationServicesController/NotificationServicesController.test.ts
  packages/notification-services-controller/src/NotificationServicesController/NotificationServicesController.ts
  packages/notification-services-controller/src/NotificationServicesPushController/NotificationServicesPushController.test.ts
  packages/notification-services-controller/src/NotificationServicesPushController/NotificationServicesPushController.ts
Labels: team-wallet-framework

#5249 chore(polling): Rename `ControllerMessenger` to `Messenger`
  packages/polling-controller/src/BlockTrackerPollingController.test.ts
  packages/polling-controller/src/StaticIntervalPollingController.test.ts
Labels: team-wallet-framework

#5247 chore(permission-log): Rename `ControllerMessenger` to `Messenger`
  packages/permission-log-controller/src/PermissionLogController.ts
  packages/permission-log-controller/tests/PermissionLogController.test.ts
Labels: team-wallet-framework

#5246 chore(base): Rename `ControllerMessenger` to `Messenger`
  packages/base-controller/src/BaseControllerV1.test.ts
  packages/base-controller/src/BaseControllerV2.test.ts
  packages/base-controller/src/BaseControllerV2.ts
  packages/base-controller/src/Messenger.ts
  packages/base-controller/tests/helpers.ts
Labels: team-wallet-framework

#5245 chore(permission): Rename `ControllerMessenger` to `Messenger`
  packages/permission-controller/ARCHITECTURE.md
  packages/permission-controller/src/PermissionController.test.ts
  packages/permission-controller/src/PermissionController.ts
  packages/permission-controller/src/SubjectMetadataController.test.ts
  packages/permission-controller/src/SubjectMetadataController.ts
Labels: team-wallet-framework

#5251 chore(preferences): Rename `ControllerMessenger` to `Messenger`
  packages/preferences-controller/src/PreferencesController.test.ts
  packages/preferences-controller/src/PreferencesController.ts
Labels: team-wallet-framework

#5241 chore(network): Rename `ControllerMessenger` to `Messenger`
  packages/network-controller/src/NetworkController.ts
  packages/network-controller/tests/NetworkController.test.ts
Labels: team-wallet-framework

#5248 chore(phishing): Rename `ControllerMessenger` to `Messenger`
  packages/phishing-controller/src/PhishingController.test.ts
  packages/phishing-controller/src/PhishingController.ts
Labels: team-wallet-framework
