Repository MetaMask/core, pull requests merged in 2025-04, with the labels that each got.

#5561 NetworkController: Make failover URLs optional
  packages/network-controller/CHANGELOG.md
  packages/network-controller/src/NetworkController.ts
  packages/network-controller/src/create-network-client.ts
  packages/network-controller/src/types.ts
Labels: team-wallet-framework

#5556 feat: add chain specific gas estimation fallbacks using remote feature flags
  packages/transaction-controller/src/TransactionController.test.ts
  packages/transaction-controller/src/TransactionController.ts
  packages/transaction-controller/src/utils/feature-flags.test.ts
  packages/transaction-controller/src/utils/feature-flags.ts
  packages/transaction-controller/src/utils/gas.test.ts
  packages/transaction-controller/src/utils/gas.ts
Labels: team-confirmations

#5584 chore: add gas payment transaction type
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/src/types.ts
Labels: team-confirmations

#5585 Release 348.0.0
  package.json
  packages/bridge-controller/CHANGELOG.md
  packages/bridge-controller/package.json
  packages/bridge-status-controller/CHANGELOG.md
  packages/bridge-status-controller/package.json
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/package.json
  packages/user-operation-controller/CHANGELOG.md
  packages/user-operation-controller/package.json
  yarn.lock
Labels: team-confirmations

#5586 skip origin validation for batch transactions
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/src/utils/batch.ts
  packages/transaction-controller/src/utils/validation.ts
Labels: team-confirmations

#5600 feat: extend isAtomicBatchSupported result
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/src/TransactionController.ts
  packages/transaction-controller/src/index.ts
  packages/transaction-controller/src/types.ts
  packages/transaction-controller/src/utils/batch.test.ts
  packages/transaction-controller/src/utils/batch.ts
Labels: team-confirmations

#5615 Release 354.0.0
  package.json
  packages/bridge-controller/CHANGELOG.md
  packages/bridge-controller/package.json
  packages/bridge-status-controller/CHANGELOG.md
  packages/bridge-status-controller/package.json
  packages/earn-controller/package.json
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/package.json
  packages/user-operation-controller/CHANGELOG.md
  packages/user-operation-controller/package.json
  yarn.lock
Labels: team-confirmations

#5289 Fix unmocked block tracker warning in NetworkController tests
  packages/network-controller/tests/NetworkController.test.ts
Labels: team-wallet-framework

#5582 fix: cache incoming transaction timestamps
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/src/helpers/AccountsApiRemoteTransactionSource.test.ts
  packages/transaction-controller/src/helpers/AccountsApiRemoteTransactionSource.ts
  packages/transaction-controller/src/types.ts
Labels: team-confirmations

#5629 feat: remove `isAccountSyncingEnabled` `env` property from `UserStorageController` constructor
  packages/profile-sync-controller/CHANGELOG.md
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
  packages/profile-sync-controller/src/controllers/user-storage/account-syncing/controller-integration.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/account-syncing/controller-integration.ts
  packages/profile-sync-controller/src/controllers/user-storage/account-syncing/setup-subscriptions.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/account-syncing/setup-subscriptions.ts
  packages/profile-sync-controller/src/controllers/user-storage/account-syncing/sync-utils.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/account-syncing/sync-utils.ts
  packages/profile-sync-controller/src/controllers/user-storage/account-syncing/types.ts
Labels: team-identity

#5633 Update to use latest workflow
  .github/workflows/add-wallet-framework-team-prs-and-issues-to-project.yml
Labels: no-changelog

#5636 feat: add backup and sync granular feature control
  packages/profile-sync-controller/CHANGELOG.md
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
  packages/profile-sync-controller/src/controllers/user-storage/account-syncing/controller-integration.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/account-syncing/sync-utils.test.ts
  packages/profile-sync-controller/src/controllers/user-storage/account-syncing/sync-utils.ts
  packages/profile-sync-controller/src/controllers/user-storage/constants.ts
  packages/profile-sync-controller/src/controllers/user-storage/index.ts
Labels: team-identity

#5638 feat: remove unused action handlers
  packages/profile-sync-controller/CHANGELOG.md
  packages/profile-sync-controller/src/controllers/user-storage/UserStorageController.ts
Labels: team-identity

#5635 feat: enhance batch support
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/src/TransactionController.ts
  packages/transaction-controller/src/utils/batch.ts
  packages/transaction-controller/src/utils/validation.test.ts
  packages/transaction-controller/src/utils/validation.ts
Labels: team-confirmations

#5644 Release 357.0.0
  package.json
  packages/notification-services-controller/CHANGELOG.md
  packages/notification-services-controller/package.json
  packages/profile-sync-controller/CHANGELOG.md
  packages/profile-sync-controller/package.json
  yarn.lock
Labels: team-identity, no-changelog

#5637 feat: use feature flags for gas estimation buffers
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/src/TransactionController.test.ts
  packages/transaction-controller/src/constants.ts
  packages/transaction-controller/src/utils/feature-flags.test.ts
  packages/transaction-controller/src/utils/feature-flags.ts
  packages/transaction-controller/src/utils/gas.test.ts
  packages/transaction-controller/src/utils/gas.ts
Labels: team-confirmations

#5646 Fix: not used fixed gas limit for transactions of type 0x4
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/src/utils/gas.test.ts
  packages/transaction-controller/src/utils/gas.ts
Labels: team-confirmations

#5648 Release 358.0.0
  package.json
  packages/bridge-controller/package.json
  packages/bridge-status-controller/package.json
  packages/earn-controller/package.json
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/package.json
  packages/user-operation-controller/package.json
  yarn.lock
Labels: team-confirmations, no-changelog

#5649 Release/359.0.0
  package.json
  packages/bridge-controller/CHANGELOG.md
  packages/bridge-controller/package.json
  packages/multichain-network-controller/CHANGELOG.md
  packages/multichain-network-controller/package.json
  yarn.lock
Labels: no-changelog

#5653 Release/360.0.0
  package.json
  packages/token-search-discovery-controller/CHANGELOG.md
  packages/token-search-discovery-controller/package.json
Labels: no-changelog

#5655 Release/361.0.0
  package.json
  packages/token-search-discovery-controller/CHANGELOG.md
  packages/token-search-discovery-controller/package.json
Labels: no-changelog

#5592 feat: add delegation controller
  .github/CODEOWNERS
  packages/delegation-controller/CHANGELOG.md
  packages/delegation-controller/LICENSE
  packages/delegation-controller/README.md
  packages/delegation-controller/jest.config.js
  packages/delegation-controller/package.json
  packages/delegation-controller/src/DelegationController.test.ts
  packages/delegation-controller/src/DelegationController.ts
  packages/delegation-controller/src/constants.ts
  packages/delegation-controller/src/index.ts
  packages/delegation-controller/src/types.ts
  packages/delegation-controller/src/utils.ts
  packages/delegation-controller/tsconfig.build.json
  packages/delegation-controller/tsconfig.json
  packages/delegation-controller/typedoc.json
  teams.json
  tsconfig.build.json
  tsconfig.json
  yarn.lock
Labels: team-vault

#5657 Release/362.0.0
  package.json
  packages/bridge-controller/CHANGELOG.md
  packages/bridge-controller/package.json
  packages/bridge-status-controller/CHANGELOG.md
  packages/bridge-status-controller/package.json
  yarn.lock
Labels: no-changelog

#5658 Release 363.0.0
  package.json
  packages/accounts-controller/package.json
  packages/assets-controllers/package.json
  packages/delegation-controller/package.json
  packages/keyring-controller/CHANGELOG.md
  packages/keyring-controller/package.json
  packages/multichain-network-controller/package.json
  packages/multichain-transactions-controller/package.json
  packages/notification-services-controller/package.json
  packages/preferences-controller/package.json
  packages/profile-sync-controller/package.json
  packages/signature-controller/package.json
  packages/user-operation-controller/package.json
  yarn.lock
Labels: no-changelog

#5651 chore: remove branch filtering from changelog check workflow
  .github/workflows/changelog-check.yml
Labels: team-wallet-framework

#5661 feat: use new api field for protocol name
  packages/assets-controllers/src/DeFiPositionsController/__fixtures__/mock-responses.ts
  packages/assets-controllers/src/DeFiPositionsController/fetch-positions.ts
  packages/assets-controllers/src/DeFiPositionsController/group-defi-positions.test.ts
  packages/assets-controllers/src/DeFiPositionsController/group-defi-positions.ts
Labels: no-changelog

#5665 Release/365.0.0
  package.json
  packages/assets-controllers/CHANGELOG.md
  packages/assets-controllers/package.json
  packages/bridge-controller/CHANGELOG.md
  packages/bridge-controller/package.json
  packages/bridge-status-controller/CHANGELOG.md
  packages/bridge-status-controller/package.json
  yarn.lock
Labels: no-changelog

#5666 Release/366.0.0
  package.json
  packages/delegation-controller/CHANGELOG.md
  packages/delegation-controller/package.json
Labels: team-vault, no-changelog

#5669 Release/367.0.0
  package.json
  packages/bridge-controller/CHANGELOG.md
  packages/bridge-controller/package.json
  packages/multichain-network-controller/CHANGELOG.md
  packages/multichain-network-controller/package.json
  yarn.lock
Labels: no-changelog

#5672 Release/368.0.0
  package.json
  packages/assets-controllers/CHANGELOG.md
  packages/assets-controllers/package.json
  packages/bridge-controller/CHANGELOG.md
  packages/bridge-controller/package.json
  packages/bridge-status-controller/CHANGELOG.md
  packages/bridge-status-controller/package.json
  yarn.lock
Labels: no-changelog

#5673 Release/369.0.0
  package.json
  packages/bridge-status-controller/CHANGELOG.md
  packages/bridge-status-controller/package.json
Labels: no-changelog

#5674 Release/370.0.0
  package.json
  packages/chain-agnostic-permission/CHANGELOG.md
  packages/chain-agnostic-permission/package.json
  packages/eip1193-permission-middleware/CHANGELOG.md
  packages/eip1193-permission-middleware/package.json
  packages/multichain-api-middleware/CHANGELOG.md
  packages/multichain-api-middleware/package.json
  yarn.lock
Labels: no-changelog

#5676 chore: bump `@metamask/create-release-branch` to `^4.1.2`
  package.json
  yarn.lock
Labels: team-wallet-framework

#5690 Release/372.0.0
  package.json
  packages/phishing-controller/CHANGELOG.md
  packages/phishing-controller/package.json
Labels: no-changelog

#5696 fix: native EVM exchange rates and snap handler calls
  packages/bridge-controller/src/bridge-controller.test.ts
  packages/bridge-controller/src/bridge-controller.ts
  packages/bridge-controller/src/selectors.test.ts
  packages/bridge-controller/src/selectors.ts
  packages/bridge-status-controller/CHANGELOG.md
  packages/bridge-status-controller/src/__snapshots__/bridge-status-controller.test.ts.snap
  packages/bridge-status-controller/src/bridge-status-controller.test.ts
  packages/bridge-status-controller/src/bridge-status-controller.ts
  packages/bridge-status-controller/src/utils/transaction.ts
Labels: no-changelog

#5700 Release/373.0.0
  package.json
  packages/bridge-controller/CHANGELOG.md
  packages/bridge-controller/package.json
  packages/bridge-status-controller/CHANGELOG.md
  packages/bridge-status-controller/package.json
  yarn.lock
Labels: no-changelog

#5692 feat: Add afterAdd hook to transaction controller
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/src/TransactionController.test.ts
  packages/transaction-controller/src/TransactionController.ts
  packages/transaction-controller/src/index.ts
  packages/transaction-controller/src/types.ts
Labels: team-confirmations

#5703 chore: remove private syntax in transaction controller
  packages/transaction-controller/src/TransactionController.test.ts
  packages/transaction-controller/src/TransactionController.ts
Labels: team-confirmations, no-changelog

#5705 Release 374.0.0
  package.json
  packages/assets-controllers/package.json
  packages/bridge-controller/package.json
  packages/bridge-status-controller/package.json
  packages/earn-controller/package.json
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/package.json
  packages/user-operation-controller/package.json
  yarn.lock
Labels: team-confirmations, no-changelog

#5710 fix: ensure no duplicate accounts are persisted
  eslint-warning-thresholds.json
  packages/keyring-controller/CHANGELOG.md
  packages/keyring-controller/jest.config.js
  packages/keyring-controller/src/KeyringController.test.ts
  packages/keyring-controller/src/KeyringController.ts
Labels: team-wallet-framework

#5712 Release/375.0.0
  package.json
  packages/assets-controllers/CHANGELOG.md
  packages/assets-controllers/package.json
  packages/bridge-controller/CHANGELOG.md
  packages/bridge-controller/package.json
  packages/bridge-status-controller/CHANGELOG.md
  packages/bridge-status-controller/package.json
  yarn.lock
Labels: no-changelog

#5681 feat: add `gasTransfer` to `GasFeeToken`
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/src/TransactionController.test.ts
  packages/transaction-controller/src/api/simulation-api.test.ts
  packages/transaction-controller/src/api/simulation-api.ts
  packages/transaction-controller/src/types.ts
  packages/transaction-controller/src/utils/gas.test.ts
  packages/transaction-controller/src/utils/gas.ts
  packages/transaction-controller/src/utils/simulation.test.ts
  packages/transaction-controller/src/utils/simulation.ts
Labels: team-confirmations

#5713 Release 376.0.0
  package.json
  packages/accounts-controller/package.json
  packages/assets-controllers/package.json
  packages/delegation-controller/package.json
  packages/keyring-controller/CHANGELOG.md
  packages/keyring-controller/package.json
  packages/multichain-network-controller/package.json
  packages/multichain-transactions-controller/package.json
  packages/notification-services-controller/package.json
  packages/preferences-controller/package.json
  packages/profile-sync-controller/package.json
  packages/signature-controller/package.json
  packages/user-operation-controller/package.json
  yarn.lock
Labels: no-changelog

#5715 Release/377.0.0
  package.json
  packages/chain-agnostic-permission/CHANGELOG.md
  packages/chain-agnostic-permission/package.json
  packages/eip1193-permission-middleware/package.json
  packages/multichain-api-middleware/package.json
  yarn.lock
Labels: no-changelog

#5717 Release/378.0.0
  package.json
  packages/assets-controllers/CHANGELOG.md
  packages/assets-controllers/package.json
  packages/bridge-controller/CHANGELOG.md
  packages/bridge-controller/package.json
  packages/bridge-status-controller/CHANGELOG.md
  packages/bridge-status-controller/package.json
  yarn.lock
Labels: no-changelog

#5668 NetworkController: Add flag for controlling RPC failover behavior
  packages/network-controller/CHANGELOG.md
  packages/network-controller/src/NetworkController.ts
  packages/network-controller/src/create-auto-managed-network-client.test.ts
  packages/network-controller/src/create-auto-managed-network-client.ts
  packages/network-controller/src/create-network-client.ts
  packages/network-controller/tests/NetworkController.test.ts
  packages/network-controller/tests/provider-api-tests/block-hash-in-response.ts
  packages/network-controller/tests/provider-api-tests/block-param.ts
  packages/network-controller/tests/provider-api-tests/helpers.ts
  packages/network-controller/tests/provider-api-tests/no-block-param.ts
  packages/network-controller/tests/provider-api-tests/rpc-failover.ts
Labels: team-wallet-framework

#5729 Release 381.0.0
  package.json
  packages/accounts-controller/package.json
  packages/assets-controllers/package.json
  packages/bridge-controller/package.json
  packages/bridge-status-controller/package.json
  packages/chain-agnostic-permission/CHANGELOG.md
  packages/chain-agnostic-permission/package.json
  packages/earn-controller/package.json
  packages/ens-controller/package.json
  packages/gas-fee-controller/package.json
  packages/multichain-api-middleware/CHANGELOG.md
  packages/multichain-api-middleware/package.json
  packages/multichain-network-controller/package.json
  packages/multichain/package.json
  packages/network-controller/CHANGELOG.md
  packages/network-controller/package.json
  packages/polling-controller/package.json
  packages/profile-sync-controller/package.json
  packages/queued-request-controller/package.json
  packages/sample-controllers/package.json
  packages/selected-network-controller/package.json
  packages/signature-controller/package.json
  packages/transaction-controller/package.json
  packages/user-operation-controller/package.json
  yarn.lock
Labels: team-wallet-framework, no-changelog

#5618 chore: add metadata to account controller options for EVM HD accounts
  packages/accounts-controller/CHANGELOG.md
  packages/accounts-controller/src/AccountsController.test.ts
  packages/accounts-controller/src/AccountsController.ts
  packages/accounts-controller/src/tests/mocks.ts
  packages/accounts-controller/src/utils.ts
Labels: team-identity

#5707 feat: remove internal transaction account validation
  packages/transaction-controller/CHANGELOG.md
  packages/transaction-controller/src/TransactionController.test.ts
  packages/transaction-controller/src/TransactionController.ts
  packages/transaction-controller/src/utils/validation.test.ts
  packages/transaction-controller/src/utils/validation.ts
Labels: team-confirmations

#5736 Release/382.0.0
  package.json
  packages/bridge-controller/CHANGELOG.md
  packages/bridge-controller/package.json
  packages/bridge-status-controller/CHANGELOG.md
  packages/bridge-status-controller/package.json
  yarn.lock
Labels: no-changelog
